// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for Activities in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using System;
using System.ComponentModel.DataAnnotations;

namespace CRM.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object for Activity timeline/event.
    /// </summary>
    public class ActivityDto
    {
        /// <summary>Unique identifier for the activity.</summary>
        public int Id { get; set; }

        /// <summary>Activity type (see ActivityType enum).</summary>
        [Required]
        public int ActivityType { get; set; }

        /// <summary>Short title or subject for the activity.</summary>
        [Required, MaxLength(200)]
        public string Title { get; set; } = string.Empty;

        /// <summary>Optional description or summary.</summary>
        [MaxLength(2000)]
        public string? Description { get; set; }

        /// <summary>Optional JSON for additional details.</summary>
        public string? Details { get; set; }

        /// <summary>Date/time the activity occurred (ISO 8601).</summary>
        [Required]
        public DateTime ActivityDate { get; set; }

        /// <summary>Duration in minutes (if applicable).</summary>
        public int? DurationMinutes { get; set; }

        /// <summary>User ID of the actor (nullable for system events).</summary>
        public int? UserId { get; set; }

        /// <summary>User display name (denormalized).</summary>
        public string? UserName { get; set; }

        /// <summary>User email (denormalized).</summary>
        public string? UserEmail { get; set; }

        /// <summary>Entity type (Account, Contact, etc.).</summary>
        public string? EntityType { get; set; }

        /// <summary>Entity ID (AccountId, ContactId, etc.).</summary>
        public int? EntityId { get; set; }

        /// <summary>Entity display name.</summary>
        public string? EntityName { get; set; }

        /// <summary>Secondary entity type (optional).</summary>
        public string? SecondaryEntityType { get; set; }

        /// <summary>Secondary entity ID (optional).</summary>
        public int? SecondaryEntityId { get; set; }

        /// <summary>Secondary entity display name (optional).</summary>
        public string? SecondaryEntityName { get; set; }

        /// <summary>Account ID (if related).</summary>
        public int? AccountId { get; set; }

        /// <summary>Contact ID (if related).</summary>
        public int? ContactId { get; set; }

        /// <summary>Opportunity ID (if related).</summary>
        public int? OpportunityId { get; set; }

        /// <summary>Campaign ID (if related).</summary>
        public int? CampaignId { get; set; }

        /// <summary>Product ID (if related).</summary>
        public int? ProductId { get; set; }

        /// <summary>Task ID (if related).</summary>
        public int? TaskId { get; set; }

        /// <summary>Quote ID (if related).</summary>
        public int? QuoteId { get; set; }

        /// <summary>Interaction ID (if related).</summary>
        public int? InteractionId { get; set; }

        /// <summary>Note ID (if related).</summary>
        public int? NoteId { get; set; }

        /// <summary>Old value (for audit/change tracking).</summary>
        public string? OldValue { get; set; }

        /// <summary>New value (for audit/change tracking).</summary>
        public string? NewValue { get; set; }

        /// <summary>Fields changed (for audit/change tracking).</summary>
        public string? FieldsChanged { get; set; }

        /// <summary>System-generated flag.</summary>
        public bool IsSystem { get; set; }

        /// <summary>Private flag (not visible to all users).</summary>
        public bool IsPrivate { get; set; }

        /// <summary>Important flag (highlight in UI).</summary>
        public bool IsImportant { get; set; }

        /// <summary>Tags (comma-separated).</summary>
        public string? Tags { get; set; }

        /// <summary>Category (optional).</summary>
        public string? Category { get; set; }

        /// <summary>Source (optional).</summary>
        public string? Source { get; set; }

        /// <summary>Created timestamp (ISO 8601).</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Updated timestamp (ISO 8601).</summary>
        public DateTime UpdatedAt { get; set; }

        /// <summary>Soft delete flag.</summary>
        public bool IsDeleted { get; set; }

        /// <summary>Row version for concurrency.</summary>
        public byte[]? RowVersion { get; set; }
    }

    /// <summary>
    /// DTO for creating an Activity.
    /// </summary>
    public class CreateActivityDto
    {
        [Required]
        public int ActivityType { get; set; }

        [Required, MaxLength(200)]
        public string Title { get; set; } = string.Empty;

        [MaxLength(2000)]
        public string? Description { get; set; }

        public string? Details { get; set; }

        public DateTime? ActivityDate { get; set; }

        public int? DurationMinutes { get; set; }

        public int? UserId { get; set; }

        public string? EntityType { get; set; }

        public int? EntityId { get; set; }

        public int? AccountId { get; set; }

        public int? ContactId { get; set; }

        public int? OpportunityId { get; set; }

        public bool IsSystem { get; set; }

        public bool IsPrivate { get; set; }

        public bool IsImportant { get; set; }

        public string? Tags { get; set; }

        public string? Source { get; set; }
    }

    /// <summary>
    /// DTO for updating an Activity.
    /// </summary>
    public class UpdateActivityDto
    {
        public string? Title { get; set; }

        public string? Description { get; set; }

        public string? Details { get; set; }

        public DateTime? ActivityDate { get; set; }

        public int? DurationMinutes { get; set; }

        public int? UserId { get; set; }

        public int? AccountId { get; set; }

        public int? ContactId { get; set; }

        public int? OpportunityId { get; set; }

        public bool? IsPrivate { get; set; }

        public bool? IsImportant { get; set; }

        public string? Tags { get; set; }
    }
}
