// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for Activities in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

// ------------------------------------------------------------------------------
// <summary>
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for Activities in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace CRM.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object for Activity.
    /// </summary>
    public class ActivityDto
    {
        public int Id { get; set; }
        public int ActivityType { get; set; }
        public string? Subject { get; set; }
        public string? Description { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public int? AccountId { get; set; }
        public int? ContactId { get; set; }
        public int? OpportunityId { get; set; }
        public int OwnerUserId { get; set; }
        public int CreatedByUserId { get; set; }
        public string? CreatedAt { get; set; }
        public string? UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public byte[]? RowVersion { get; set; }
    }

    /// <summary>
    /// DTO for creating an Activity.
    /// </summary>
    public class CreateActivityDto
    {
        public int ActivityType { get; set; }
        public string? Subject { get; set; }
        public string? Description { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public int? AccountId { get; set; }
        public int? ContactId { get; set; }
        public int? OpportunityId { get; set; }
        public int OwnerUserId { get; set; }
    }

    /// <summary>
    /// DTO for updating an Activity.
    /// </summary>
    public class UpdateActivityDto
    {
        public int ActivityType { get; set; }
        public string? Subject { get; set; }
        public string? Description { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public int? AccountId { get; set; }
        public int? ContactId { get; set; }
        public int? OpportunityId { get; set; }
        public int OwnerUserId { get; set; }
    }
    }

    /// <summary>
    /// DTO for updating an Activity.
    /// </summary>
    public class UpdateActivityDto
    {
        public int ActivityType { get; set; }
        public string? Subject { get; set; }
        public string? Description { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public int? AccountId { get; set; }
        public int? ContactId { get; set; }
        public int? OpportunityId { get; set; }
        public int OwnerUserId { get; set; }
    }
