// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This software is source-available. Non-commercial use is permitted under
// the terms of the LICENSE file. Commercial use requires a separate license.
// See the LICENSE file in the root directory for full terms.
#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for CRM Tasks in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace CRM.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object for CRM Task.
    /// </summary>
    public class CrmTaskDto
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public string? DueDate { get; set; }
        public string? CompletedDate { get; set; }
        public int OwnerUserId { get; set; }
        public int CreatedByUserId { get; set; }
        public string CreatedAt { get; set; } = string.Empty;
        public string UpdatedAt { get; set; } = string.Empty;
        public bool IsDeleted { get; set; }
        public byte[]? RowVersion { get; set; }
    }

    /// <summary>
    /// DTO for creating a CRM Task.
    /// </summary>
    public class CreateCrmTaskDto
    {
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public int Priority { get; set; } = 1;
        public string? DueDate { get; set; }
        public int? OwnerUserId { get; set; }
        public int? AccountId { get; set; }
        public int? OpportunityId { get; set; }
        public int? AssignedToUserId { get; set; }
        // Add other fields as needed
    }

    /// <summary>
    /// DTO for updating a CRM Task.
    /// </summary>
    public class UpdateCrmTaskDto
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public int? Status { get; set; }
        public int? Priority { get; set; }
        public string? DueDate { get; set; }
        public string? CompletedDate { get; set; }
        public int? AssignedToUserId { get; set; }
        // Add other updatable fields as needed
    }
}





