// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This software is source-available. Non-commercial use is permitted under
// the terms of the LICENSE file. Commercial use requires a separate license.
// See the LICENSE file in the root directory for full terms.
#pragma warning disable SA1649 // file name should match first type name
#nullable enable
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for CRM Tasks in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace CRM.Core.Dtos
{
    /// <summary>
    /// Data Transfer Object for CRM Task.
    /// </summary>
    public class CrmTaskDto
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public string? DueDate { get; set; }
        public string? CompletedDate { get; set; }
        public int OwnerUserId { get; set; }
        public int CreatedByUserId { get; set; }
        public string CreatedAt { get; set; } = string.Empty;
        public string UpdatedAt { get; set; } = string.Empty;
        public bool IsDeleted { get; set; }
        public byte[]? RowVersion { get; set; }

        // Dates & Timing
        public string? ReminderDate { get; set; }
        public bool HasReminder { get; set; }

        // Progress & Effort
        public int PercentComplete { get; set; }
        public int? ActualMinutes { get; set; }

        // Recurrence
        public bool IsRecurring { get; set; }
        public string? RecurrencePattern { get; set; }
        public string? RecurrenceEndDate { get; set; }
        public int? ParentTaskId { get; set; }

        // Relationships
        public int? ContactId { get; set; }
        public int? CampaignId { get; set; }
        public int? AssignedToGroupId { get; set; }

        // Classification & Metadata
        public string? Tags { get; set; }
        public string? Category { get; set; }
        public string? Attachments { get; set; }
        public string? CustomFields { get; set; }

        /// <summary>Type of task (CrmTaskType enum, int)</summary>
        public int TaskType { get; set; }

        /// <summary>Planned start date (ISO 8601 string)</summary>
        public string? StartDate { get; set; }

        /// <summary>Estimated effort in minutes</summary>
        public int? EstimatedMinutes { get; set; }

        /// <summary>Associated account ID</summary>
        public int? AccountId { get; set; }

        /// <summary>Associated opportunity ID</summary>
        public int? OpportunityId { get; set; }
    }

    /// <summary>
    /// DTO for creating a CRM Task.
    /// </summary>
    public class CreateCrmTaskDto
    {
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public int Priority { get; set; } = 1;
        public string? DueDate { get; set; }
        public int? OwnerUserId { get; set; }
        public int? AccountId { get; set; }
        public int? OpportunityId { get; set; }
        public int? AssignedToUserId { get; set; }

        // Dates & Timing
        public string? ReminderDate { get; set; }
        public bool HasReminder { get; set; }

        // Progress & Effort
        public int PercentComplete { get; set; }
        public int? ActualMinutes { get; set; }

        // Recurrence
        public bool IsRecurring { get; set; }
        public string? RecurrencePattern { get; set; }
        public string? RecurrenceEndDate { get; set; }
        public int? ParentTaskId { get; set; }

        // Relationships
        public int? ContactId { get; set; }
        public int? CampaignId { get; set; }
        public int? AssignedToGroupId { get; set; }

        // Classification & Metadata
        public string? Tags { get; set; }
        public string? Category { get; set; }
        public string? Attachments { get; set; }
        public string? CustomFields { get; set; }
    }

    /// <summary>
    /// DTO for updating a CRM Task.
    /// </summary>
    public class UpdateCrmTaskDto
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public int? Status { get; set; }
        public int? Priority { get; set; }
        public string? DueDate { get; set; }
        public string? CompletedDate { get; set; }
        public int? AssignedToUserId { get; set; }

        // Dates & Timing
        public string? ReminderDate { get; set; }
        public bool? HasReminder { get; set; }

        // Progress & Effort
        public int? PercentComplete { get; set; }
        public int? ActualMinutes { get; set; }

        // Recurrence
        public bool? IsRecurring { get; set; }
        public string? RecurrencePattern { get; set; }
        public string? RecurrenceEndDate { get; set; }
        public int? ParentTaskId { get; set; }

        // Relationships
        public int? ContactId { get; set; }
        public int? CampaignId { get; set; }
        public int? AssignedToGroupId { get; set; }

        // Classification & Metadata
        public string? Tags { get; set; }
        public string? Category { get; set; }
        public string? Attachments { get; set; }
        public string? CustomFields { get; set; }
    }
}
