
// ------------------------------------------------------------------------------
// <summary>
//   Data Transfer Objects (DTOs) for Opportunities in CRM Solution.
//   Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//   Licensed under the MIT License. See LICENSE in the project root for license information.
// </summary>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CRM.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object for Opportunity.
    /// </summary>
    /// <summary>
    /// Data Transfer Object for Opportunity.
    /// </summary>
    public class OpportunityDto
    {
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        public string? Description { get; set; }
        public int Stage { get; set; }
        public int Status { get; set; }
        public int Probability { get; set; }
        public decimal EstimatedValue { get; set; }
        // ------------------------------------------------------------------------------
        // <auto-generated>
        //     This file contains Data Transfer Objects (DTOs) for Opportunities in CRM.
        //     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
        //     Licensed under the MIT License. See LICENSE in the project root for license information.
        // </auto-generated>
        // ------------------------------------------------------------------------------

        using System;
        using System.Collections.Generic;

        namespace CRM.Core.DTOs
        {
            /// <summary>
            /// Data Transfer Object for Opportunity.
            /// </summary>
            public class OpportunityDto
            {
                public int Id { get; set; }
                public string? Name { get; set; }
                public string? Description { get; set; }
                public int Stage { get; set; }
                public int Status { get; set; }
                public int Probability { get; set; }
                public decimal EstimatedValue { get; set; }
                public decimal? ActualValue { get; set; }
                public string? ExpectedCloseDate { get; set; }
                public string? ActualCloseDate { get; set; }
                public int AccountId { get; set; }
                public int? PrimaryContactId { get; set; }
                public int OwnerUserId { get; set; }
                public int Source { get; set; }
                public int? CampaignId { get; set; }
                public List<OpportunityProductDto>? Products { get; set; }
                public string? CreatedAt { get; set; }
                public string? UpdatedAt { get; set; }
                public bool IsDeleted { get; set; }
                public byte[]? RowVersion { get; set; }
            }

            /// <summary>
            /// DTO for creating an Opportunity.
            /// </summary>
            public class CreateOpportunityDto
            {
                public string? Name { get; set; }
                public string? Description { get; set; }
                public int Stage { get; set; }
                public int Probability { get; set; }
                public decimal EstimatedValue { get; set; }
                public string? ExpectedCloseDate { get; set; }
                public int AccountId { get; set; }
                public int? PrimaryContactId { get; set; }
                public int OwnerUserId { get; set; }
                public int Source { get; set; }
                public int? CampaignId { get; set; }
                public List<CreateOpportunityProductDto>? Products { get; set; }
            }

            /// <summary>
            /// DTO for updating an Opportunity.
            /// </summary>
            public class UpdateOpportunityDto
            {
                public string? Name { get; set; }
                public string? Description { get; set; }
                public int Stage { get; set; }
                public int Status { get; set; }
                public int Probability { get; set; }
                public decimal EstimatedValue { get; set; }
                public decimal? ActualValue { get; set; }
                public string? ExpectedCloseDate { get; set; }
                public string? ActualCloseDate { get; set; }
                public int AccountId { get; set; }
                public int? PrimaryContactId { get; set; }
                public int OwnerUserId { get; set; }
                public int Source { get; set; }
                public int? CampaignId { get; set; }
                public List<UpdateOpportunityProductDto>? Products { get; set; }
            }

            /// <summary>
            /// DTO for Opportunity Product.
            /// </summary>
            public class OpportunityProductDto
            {
                public int Id { get; set; }
                public int OpportunityId { get; set; }
                public int ProductId { get; set; }
                public string? ProductName { get; set; }
                public decimal Quantity { get; set; }
                public decimal UnitPrice { get; set; }
                public decimal Discount { get; set; }
                public decimal TaxAmount { get; set; }
                public decimal TotalPrice { get; set; }
                public string? Notes { get; set; }
            }

            /// <summary>
            /// DTO for creating an Opportunity Product.
            /// </summary>
            public class CreateOpportunityProductDto
            {
                public int ProductId { get; set; }
                public decimal Quantity { get; set; }
                public decimal UnitPrice { get; set; }
                public decimal Discount { get; set; }
                public decimal TaxAmount { get; set; }
                public string? Notes { get; set; }
            }

            /// <summary>
            /// DTO for updating an Opportunity Product.
            /// </summary>
            public class UpdateOpportunityProductDto
            {
                public int Id { get; set; }
                public decimal Quantity { get; set; }
                public decimal UnitPrice { get; set; }
                public decimal Discount { get; set; }
                public decimal TaxAmount { get; set; }
                public string? Notes { get; set; }
            }
        }
    /// </summary>
    /// <summary>
    /// DTO for updating an Opportunity Product.
    /// </summary>
    public class UpdateOpportunityProductDto
    {
        public int Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal TaxAmount { get; set; }
        public string? Notes { get; set; }
    }
}
