
#nullable enable

// ------------------------------------------------------------------------------
// <auto-generated>
//     This file contains Data Transfer Objects (DTOs) for Quotes in CRM.
//     Copyright (c) 2026 CRM Solution Contributors. All rights reserved.
//     Licensed under the MIT License. See LICENSE in the project root for license information.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CRM.Core.DTOs
{
    /// <summary>
    /// Data Transfer Object representing a sales quote.
    /// </summary>
    public class QuoteDto
    {
        public int Id { get; set; }
        public string? QuoteNumber { get; set; }
        public string? Title { get; set; }
        public int AccountId { get; set; }
        public string? AccountName { get; set; }
        public int? ContactId { get; set; }
        public string? ContactName { get; set; }
        public int Status { get; set; } // Was QuoteStatus
        public string? Currency { get; set; }
        public string? IssuedDate { get; set; }
        public string? ExpirationDate { get; set; }
        public string? Notes { get; set; }
        public decimal Subtotal { get; set; }
        public decimal DiscountTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal GrandTotal { get; set; }
        public List<QuoteLineItemDto>? LineItems { get; set; }
        public string? CreatedAt { get; set; }
        public string? UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public byte[]? RowVersion { get; set; }
        public int CreatedByUserId { get; set; }
        public int? UpdatedByUserId { get; set; }
    }

    /// <summary>
    /// DTO for creating a Quote.
    /// </summary>
    public class CreateQuoteDto
    {
        public string? Title { get; set; }
        public int AccountId { get; set; }
        public int? ContactId { get; set; }
        public string? Currency { get; set; }
        public string? IssuedDate { get; set; }
        public string? ExpirationDate { get; set; }
        public string? Notes { get; set; }
        public List<CreateQuoteLineItemDto>? LineItems { get; set; }
    }

    /// <summary>
    /// DTO for updating a Quote.
    /// </summary>
    public class UpdateQuoteDto
    {
        public string? Title { get; set; }
        public int AccountId { get; set; }
        public int? ContactId { get; set; }
        public int Status { get; set; } // Was QuoteStatus
        public string? Currency { get; set; }
        public string? IssuedDate { get; set; }
        public string? ExpirationDate { get; set; }
        public string? Notes { get; set; }
        public List<UpdateQuoteLineItemDto>? LineItems { get; set; }
    }

    /// <summary>
    /// DTO for Quote Line Item.
    /// </summary>
    public class QuoteLineItemDto
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public int ProductId { get; set; }
        public string? ProductName { get; set; }
        public string? Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal LineTotal { get; set; }
    }

    /// <summary>
    /// DTO for creating a Quote Line Item.
    /// </summary>
    public class CreateQuoteLineItemDto
    {
        public int ProductId { get; set; }
        public string? Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
    }

    /// <summary>
    /// DTO for updating a Quote Line Item.
    /// </summary>
    public class UpdateQuoteLineItemDto
    {
        public int Id { get; set; }
        public string? Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
    }
}
