apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crm-monolith.fullname" . }}-secrets
  labels:
    {{- include "crm-monolith.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  JWT_ISSUER: {{ .Values.secrets.JWT_ISSUER | quote }}
  JWT_AUDIENCE: {{ .Values.secrets.JWT_AUDIENCE | quote }}
  DB_CONNECTION_STRING: {{ default (printf "Server=%s-db;Port=3306;Database=%s;User=%s;Password=%s;" (include "crm-monolith.fullname" .) .Values.db.database .Values.db.user .Values.db.password) .Values.secrets.DB_CONNECTION_STRING | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_ROOT_PASSWORD: {{ .Values.db.rootPassword | quote }}
  DB_NAME: {{ .Values.db.database | quote }}
