-- ============================================================================
-- CRM Solution Database Seed Data - Module UI Configurations
-- Version: 1.0
-- Date: 2026-01-23
-- Description: Full navigation configuration with all modules enabled
-- ============================================================================

SET NAMES utf8mb4;

-- Clear existing module configurations
DELETE FROM ModuleUIConfigs WHERE IsDeleted = 0;

-- ----------------------------------------------------------------------------
-- Module UI Configurations - All Modules Enabled
-- ----------------------------------------------------------------------------
INSERT INTO ModuleUIConfigs (Id, ModuleName, IsEnabled, DisplayName, Description, IconName, DisplayOrder, TabsConfig, LinkedEntitiesConfig, ListViewConfig, DetailViewConfig, QuickCreateConfig, SearchFilterConfig, ModuleSettings, CreatedAt, IsDeleted) VALUES
(1, 'Dashboard', 1, 'Dashboard', 'Analytics and overview', 'Dashboard', 0, 
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "analytics", "label": "Analytics", "enabled": true}, {"id": "reports", "label": "Reports", "enabled": true}]}',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '{"showStatistics": true, "refreshInterval": 60}',
  NOW(), 0),

(2, 'Customers', 1, 'Customers', 'Customer management', 'People', 1,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "contacts", "label": "Contacts", "enabled": true}, {"id": "addresses", "label": "Addresses", "enabled": true}, {"id": "activities", "label": "Activities", "enabled": true}, {"id": "opportunities", "label": "Opportunities", "enabled": true}, {"id": "servicerequests", "label": "Service Requests", "enabled": true}]}',
  '{"linkedEntities": ["Contacts", "Addresses", "Opportunities", "ServiceRequests", "Activities", "Notes"]}',
  '{"columns": ["name", "type", "industry", "email", "phone", "status", "owner"], "defaultSort": "name", "sortDirection": "asc"}',
  '{"sections": ["overview", "contacts", "addresses", "timeline"]}',
  '{"fields": ["name", "type", "industry", "email", "phone"]}',
  '{"filters": ["type", "industry", "status", "owner", "createdAt"]}',
  '{"enableMerge": true, "enableImport": true, "enableExport": true}',
  NOW(), 0),

(3, 'Contacts', 1, 'Contacts', 'Contact information', 'Contacts', 2,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "activities", "label": "Activities", "enabled": true}, {"id": "opportunities", "label": "Opportunities", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Opportunities", "Activities", "Notes"]}',
  '{"columns": ["fullName", "email", "phone", "company", "jobTitle", "status"], "defaultSort": "fullName", "sortDirection": "asc"}',
  '{"sections": ["overview", "company", "timeline"]}',
  '{"fields": ["firstName", "lastName", "email", "phone", "company"]}',
  '{"filters": ["status", "company", "createdAt"]}',
  '{"enableMerge": true, "enableImport": true, "enableExport": true}',
  NOW(), 0),

(4, 'Leads', 1, 'Leads', 'Lead management', 'PersonAdd', 3,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "activities", "label": "Activities", "enabled": true}, {"id": "qualification", "label": "Qualification", "enabled": true}]}',
  '{"linkedEntities": ["Activities", "Notes"]}',
  '{"columns": ["name", "company", "source", "status", "rating", "owner"], "defaultSort": "createdAt", "sortDirection": "desc"}',
  '{"sections": ["overview", "qualification", "timeline"]}',
  '{"fields": ["firstName", "lastName", "email", "company", "source"]}',
  '{"filters": ["source", "status", "rating", "owner"]}',
  '{"enableConversion": true, "enableScoring": true}',
  NOW(), 0),

(5, 'Opportunities', 1, 'Opportunities', 'Sales opportunities', 'TrendingUp', 4,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "products", "label": "Products", "enabled": true}, {"id": "activities", "label": "Activities", "enabled": true}, {"id": "quotes", "label": "Quotes", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Products", "Quotes", "Activities", "Notes"]}',
  '{"columns": ["name", "customer", "stage", "amount", "probability", "closeDate", "owner"], "defaultSort": "closeDate", "sortDirection": "asc"}',
  '{"sections": ["overview", "products", "timeline", "competitors"]}',
  '{"fields": ["name", "customer", "amount", "closeDate", "stage"]}',
  '{"filters": ["stage", "amount", "closeDate", "owner"]}',
  '{"enablePipeline": true, "enableForecasting": true}',
  NOW(), 0),

(6, 'Products', 1, 'Products', 'Product catalog', 'Inventory2', 5,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "pricing", "label": "Pricing", "enabled": true}, {"id": "inventory", "label": "Inventory", "enabled": true}]}',
  '{"linkedEntities": ["Opportunities", "Quotes"]}',
  '{"columns": ["code", "name", "category", "price", "stock", "status"], "defaultSort": "name", "sortDirection": "asc"}',
  '{"sections": ["overview", "pricing", "inventory"]}',
  '{"fields": ["code", "name", "category", "price"]}',
  '{"filters": ["category", "status", "priceRange"]}',
  '{"enableBundling": true, "enablePriceBooks": true}',
  NOW(), 0),

(7, 'Services', 1, 'Services', 'Service offerings', 'Build', 6,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "pricing", "label": "Pricing", "enabled": true}]}',
  '{"linkedEntities": ["Opportunities", "Quotes"]}',
  '{"columns": ["code", "name", "category", "price", "status"], "defaultSort": "name", "sortDirection": "asc"}',
  '{"sections": ["overview", "pricing"]}',
  '{"fields": ["code", "name", "category", "price"]}',
  '{"filters": ["category", "status"]}',
  '{"enableRecurring": true}',
  NOW(), 0),

(8, 'Campaigns', 1, 'Campaigns', 'Marketing campaigns', 'Campaign', 7,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "members", "label": "Members", "enabled": true}, {"id": "metrics", "label": "Metrics", "enabled": true}]}',
  '{"linkedEntities": ["Leads", "Contacts", "Activities"]}',
  '{"columns": ["name", "type", "status", "startDate", "endDate", "budget", "roi"], "defaultSort": "startDate", "sortDirection": "desc"}',
  '{"sections": ["overview", "members", "metrics"]}',
  '{"fields": ["name", "type", "startDate", "endDate", "budget"]}',
  '{"filters": ["type", "status", "startDate"]}',
  '{"enableAutomation": true, "enableTracking": true}',
  NOW(), 0),

(9, 'Quotes', 1, 'Quotes', 'Quotations', 'Description', 8,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "lineItems", "label": "Line Items", "enabled": true}, {"id": "terms", "label": "Terms", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Opportunities", "Products"]}',
  '{"columns": ["quoteNumber", "customer", "total", "status", "validUntil", "owner"], "defaultSort": "createdAt", "sortDirection": "desc"}',
  '{"sections": ["overview", "lineItems", "terms", "addresses"]}',
  '{"fields": ["customer", "opportunity", "validUntil"]}',
  '{"filters": ["status", "customer", "createdAt"]}',
  '{"enablePdf": true, "enableEmail": true}',
  NOW(), 0),

(10, 'Tasks', 1, 'Tasks', 'Task management', 'Assignment', 9,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Opportunities"]}',
  '{"columns": ["subject", "relatedTo", "dueDate", "priority", "status", "owner"], "defaultSort": "dueDate", "sortDirection": "asc"}',
  '{"sections": ["overview", "related"]}',
  '{"fields": ["subject", "dueDate", "priority", "assignedTo"]}',
  '{"filters": ["status", "priority", "dueDate", "owner"]}',
  '{"enableRecurring": true, "enableReminders": true}',
  NOW(), 0),

(11, 'Activities', 1, 'Activities', 'Activity logging', 'Timeline', 10,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Opportunities", "ServiceRequests"]}',
  '{"columns": ["type", "subject", "relatedTo", "date", "status", "owner"], "defaultSort": "createdAt", "sortDirection": "desc"}',
  '{"sections": ["overview", "related"]}',
  '{"fields": ["type", "subject", "date", "description"]}',
  '{"filters": ["type", "status", "date", "owner"]}',
  '{"enableCalendar": true}',
  NOW(), 0),

(12, 'Notes', 1, 'Notes', 'Notes and docs', 'Note', 11,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Opportunities", "ServiceRequests"]}',
  '{"columns": ["title", "relatedTo", "createdBy", "createdAt"], "defaultSort": "createdAt", "sortDirection": "desc"}',
  '{"sections": ["content", "related"]}',
  '{"fields": ["title", "content", "relatedTo"]}',
  '{"filters": ["relatedTo", "createdBy", "createdAt"]}',
  '{"enableAttachments": true, "enablePinning": true}',
  NOW(), 0),

(13, 'Workflows', 1, 'Workflows', 'Automation rules', 'AutoAwesome', 12,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "steps", "label": "Steps", "enabled": true}, {"id": "history", "label": "History", "enabled": true}]}',
  NULL,
  '{"columns": ["name", "entityType", "triggerType", "status", "lastRun"], "defaultSort": "name", "sortDirection": "asc"}',
  '{"sections": ["overview", "steps", "triggers", "history"]}',
  '{"fields": ["name", "entityType", "triggerType"]}',
  '{"filters": ["entityType", "status", "triggerType"]}',
  '{"enableVersioning": true, "enableScheduling": true}',
  NOW(), 0),

(14, 'Reports', 1, 'Reports', 'Reports and analytics', 'Assessment', 13,
  '{"tabs": [{"id": "standard", "label": "Standard Reports", "enabled": true}, {"id": "custom", "label": "Custom Reports", "enabled": true}, {"id": "scheduled", "label": "Scheduled", "enabled": true}]}',
  NULL,
  '{"columns": ["name", "category", "lastRun", "schedule", "owner"], "defaultSort": "name", "sortDirection": "asc"}',
  '{"sections": ["overview", "filters", "output"]}',
  '{"fields": ["name", "category", "description"]}',
  '{"filters": ["category", "type"]}',
  '{"enableExport": true, "enableScheduling": true, "enableDashboard": true}',
  NOW(), 0),

(15, 'ServiceRequests', 1, 'Service Requests', 'Customer service tickets', 'SupportAgent', 14,
  '{"tabs": [{"id": "overview", "label": "Overview", "enabled": true}, {"id": "activities", "label": "Activities", "enabled": true}, {"id": "resolution", "label": "Resolution", "enabled": true}]}',
  '{"linkedEntities": ["Customers", "Contacts", "Activities", "Notes"]}',
  '{"columns": ["ticketNumber", "subject", "category", "priority", "status", "customer", "assignedTo", "createdAt"], "defaultSort": "createdAt", "sortDirection": "desc"}',
  '{"sections": ["overview", "customer", "resolution", "timeline"]}',
  '{"fields": ["subject", "description", "category", "priority", "customer"]}',
  '{"filters": ["category", "status", "priority", "assignedTo", "createdAt"]}',
  '{"enableSla": true, "enableEscalation": true, "enableKnowledgeBase": true}',
  NOW(), 0);
