// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This software is source-available. Non-commercial use is permitted under
// the terms of the LICENSE file. Commercial use requires a separate license.
// See the LICENSE file in the root directory for full terms.

namespace CRM.Core.Interfaces;

/// <summary>
/// Service for generating meeting summaries from interaction records.
/// Implements TODO-AI-08.
/// </summary>
public interface IMeetingSummaryService
{
    /// <summary>
    /// Generates a structured summary for a meeting interaction.
    /// </summary>
    /// <param name="interactionId">The interaction record ID.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Meeting summary DTO, or null if interaction not found.</returns>
    Task<MeetingSummaryDto?> GenerateSummaryAsync(int interactionId, CancellationToken ct = default);
}

/// <summary>
/// Structured summary of a meeting interaction.
/// </summary>
public class MeetingSummaryDto
{
    /// <summary>Interaction ID this summary was generated from.</summary>
    public int InteractionId { get; set; }

    /// <summary>Executive summary of the meeting.</summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>Action items identified during the meeting.</summary>
    public string[] ActionItems { get; set; } = Array.Empty<string>();

    /// <summary>Meeting attendees extracted from the interaction record.</summary>
    public string[] Attendees { get; set; } = Array.Empty<string>();

    /// <summary>Suggested date for the next follow-up meeting.</summary>
    public DateTime? NextMeetingDate { get; set; }

    /// <summary>Whether the summary was generated by AI or extracted from notes.</summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>When the summary was generated.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}
