{{- if .Values.services.sales.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crm-microservices.fullname" . }}-sales
  labels:
    {{- include "crm-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: sales
spec:
  type: ClusterIP
  selector:
    {{- include "crm-microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sales
  ports:
  - port: {{ .Values.services.sales.port }}
    targetPort: {{ .Values.services.sales.port }}
    name: http
{{- end }}
