// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This software is source-available. Non-commercial use is permitted under
// the terms of the LICENSE file. Commercial use requires a separate license.
// See the LICENSE file in the root directory for full terms.
using CRM.Tests.Helpers;
using FluentAssertions;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Xunit;

namespace CRM.Backend.Tests.Integration.Controllers
{
    public class CommunicationsControllerTests : IClassFixture<ApiTestFactory>
    {
        private readonly HttpClient _client;
        public CommunicationsControllerTests(ApiTestFactory factory) => _client = factory.CreateClient();

        [Fact]
        public async Task Crud_Communications_Succeeds()
        {
            var create = new
            {
                ChannelType = "Test",
                Name = "Test",
                Status = "Test",
                IsEnabled = true,
                IsDefault = true,
                SocialUsername = "Test",
                FromEmail = "Test",
                LastConnectedAt = DateTime.UtcNow,
                SmtpServer = "Test",
                SmtpPort = 1,
                SmtpUseSsl = true,
                SmtpUsername = "Test",
                ImapServer = "Test",
                ImapPort = 1,
                ImapUseSsl = true,
                FromName = "Test",
                WhatsAppBusinessAccountId = "Test",
                WhatsAppPhoneNumberId = "Test",
                SocialAccountId = "Test",
                WebhookUrl = "Test",
                WebhookEnabled = true,
                LastError = "Test",
                ApiKey = "Test",
                ApiSecret = "Test",
                ClientId = "Test",
                ClientSecret = "Test",
                AccessToken = "Test",
                RefreshToken = "Test",
                SmtpPassword = "Test",
                WhatsAppVerifyToken = "Test",
                PageAccessToken = "Test",
                Subject = "Test",
                BodyPreview = "Test",
                Direction = "Test",
                FromAddress = "Test",
                ToAddress = "Test",
                ToName = "Test",
                AttachmentCount = 1,
                IsRead = true,
                IsStarred = true,
                SentAt = DateTime.UtcNow,
                ReceivedAt = DateTime.UtcNow,
                AccountId = 1,
                AccountName = "Test",
                ContactId = 1,
                ContactName = "Test",
                ChannelId = 1,
                ChannelName = "Test",
                Body = "Test",
                HtmlBody = "Test",
                Priority = "Test",
                ConversationId = "Test",
                ParentMessageId = 1,
                LeadId = 1,
                OpportunityId = 1,
                DeliveredAt = DateTime.UtcNow,
                ReadAt = DateTime.UtcNow,
                OpenCount = 1,
                ClickCount = 1,
                IsPublicPost = true,
                LikeCount = 1,
                ShareCount = 1,
                CommentCount = 1,
                IsArchived = true,
                ErrorMessage = "Test",
                FileName = "Test",
                ContentType = "Test",
                Size = 1,
                Url = "Test",
                ScheduledAt = DateTime.UtcNow,
                TrackOpens = true,
                TrackClicks = true,
                EmailTemplateId = 1,
                InReplyToId = "Test",
                IsRetweet = true,
                IsQuoteRetweet = true,
                ToPhoneNumber = "Test",
                MessageType = "Test",
                MediaUrl = "Test",
                TemplateName = "Test",
                Description = "Test",
                Category = "Test",
                IsActive = true,
                IsSystem = true,
                UsageCount = 1,
                LastUsedAt = DateTime.UtcNow,
                PlainTextBody = "Test",
                ReplyToEmail = "Test",
                PreviewText = "Test",
                LastMessagePreview = "Test",
                ParticipantAddress = "Test",
                ParticipantName = "Test",
                MessageCount = 1,
                UnreadCount = 1,
                LastMessageAt = DateTime.UtcNow,
                IsPinned = true,
                AssignedToUserId = 1,
                FirstMessageAt = DateTime.UtcNow,
                IsMuted = true,
                TotalMessages = 1,
                TotalInbound = 1,
                TotalOutbound = 1,
                OpenConversations = 1,
                PendingMessages = 1,
                EmailStats = (object?)null,
                WhatsAppStats = (object?)null,
                TwitterStats = (object?)null,
                FacebookStats = (object?)null,
                Inbound = 1,
                Outbound = 1,
                Unread = 1,
                Pending = 1,
                Failed = 1,
                OpenRate = 1,
                ClickRate = 1
            };
            var cRes = await _client.PostAsJsonAsync("/api/communications", create);
            cRes.StatusCode.Should().Be(HttpStatusCode.Created);
            var item = await cRes.Content.ReadFromJsonAsync<JsonElement>();
            var id = item.GetProperty("id").GetInt32();

            var getRes = await _client.GetAsync($"/api/communications/{id}");
            getRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var patch = new
            {
                ChannelType = "Test2",
                Name = "Test",
                Status = "Test",
                IsEnabled = true,
                IsDefault = true,
                SocialUsername = "Test",
                FromEmail = "Test",
                LastConnectedAt = DateTime.UtcNow,
                SmtpServer = "Test",
                SmtpPort = 1,
                SmtpUseSsl = true,
                SmtpUsername = "Test",
                ImapServer = "Test",
                ImapPort = 1,
                ImapUseSsl = true,
                FromName = "Test",
                WhatsAppBusinessAccountId = "Test",
                WhatsAppPhoneNumberId = "Test",
                SocialAccountId = "Test",
                WebhookUrl = "Test",
                WebhookEnabled = true,
                LastError = "Test",
                ApiKey = "Test",
                ApiSecret = "Test",
                ClientId = "Test",
                ClientSecret = "Test",
                AccessToken = "Test",
                RefreshToken = "Test",
                SmtpPassword = "Test",
                WhatsAppVerifyToken = "Test",
                PageAccessToken = "Test",
                Subject = "Test",
                BodyPreview = "Test",
                Direction = "Test",
                FromAddress = "Test",
                ToAddress = "Test",
                ToName = "Test",
                AttachmentCount = 1,
                IsRead = true,
                IsStarred = true,
                SentAt = DateTime.UtcNow,
                ReceivedAt = DateTime.UtcNow,
                AccountId = 1,
                AccountName = "Test",
                ContactId = 1,
                ContactName = "Test",
                ChannelId = 1,
                ChannelName = "Test",
                Body = "Test",
                HtmlBody = "Test",
                Priority = "Test",
                ConversationId = "Test",
                ParentMessageId = 1,
                LeadId = 1,
                OpportunityId = 1,
                DeliveredAt = DateTime.UtcNow,
                ReadAt = DateTime.UtcNow,
                OpenCount = 1,
                ClickCount = 1,
                IsPublicPost = true,
                LikeCount = 1,
                ShareCount = 1,
                CommentCount = 1,
                IsArchived = true,
                ErrorMessage = "Test",
                FileName = "Test",
                ContentType = "Test",
                Size = 1,
                Url = "Test",
                ScheduledAt = DateTime.UtcNow,
                TrackOpens = true,
                TrackClicks = true,
                EmailTemplateId = 1,
                InReplyToId = "Test",
                IsRetweet = true,
                IsQuoteRetweet = true,
                ToPhoneNumber = "Test",
                MessageType = "Test",
                MediaUrl = "Test",
                TemplateName = "Test",
                Description = "Test",
                Category = "Test",
                IsActive = true,
                IsSystem = true,
                UsageCount = 1,
                LastUsedAt = DateTime.UtcNow,
                PlainTextBody = "Test",
                ReplyToEmail = "Test",
                PreviewText = "Test",
                LastMessagePreview = "Test",
                ParticipantAddress = "Test",
                ParticipantName = "Test",
                MessageCount = 1,
                UnreadCount = 1,
                LastMessageAt = DateTime.UtcNow,
                IsPinned = true,
                AssignedToUserId = 1,
                FirstMessageAt = DateTime.UtcNow,
                IsMuted = true,
                TotalMessages = 1,
                TotalInbound = 1,
                TotalOutbound = 1,
                OpenConversations = 1,
                PendingMessages = 1,
                EmailStats = (object?)null,
                WhatsAppStats = (object?)null,
                TwitterStats = (object?)null,
                FacebookStats = (object?)null,
                Inbound = 1,
                Outbound = 1,
                Unread = 1,
                Pending = 1,
                Failed = 1,
                OpenRate = 1,
                ClickRate = 1
            };
            var pRes = await _client.PatchAsJsonAsync($"/api/communications/{id}", patch);
            pRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var del = await _client.DeleteAsync($"/api/communications/{id}");
            del.StatusCode.Should().Be(HttpStatusCode.NoContent);
            var nf = await _client.GetAsync($"/api/communications/{id}");
            nf.StatusCode.Should().Be(HttpStatusCode.NotFound);
        }

        [Fact]
        public async Task Get_Nonexistent_Returns404()
        {
            var res = await _client.GetAsync("/api/communications/999999");
            Assert.Equal(HttpStatusCode.NotFound, res.StatusCode);
        }
    }
}
