using CRM.Tests.Helpers;
using FluentAssertions;
using System.Net;
using System.Net.Http.Json;
using Xunit;

namespace CRM.Backend.Tests.Integration.Controllers
{
    public class CommunicationsControllerTests : IClassFixture<ApiTestFactory>
    {
        private readonly HttpClient _client;
        public CommunicationsControllerTests(ApiTestFactory factory) => _client = factory.CreateClient();

        [Fact]
        public async Task Crud_Communications_Succeeds()
        {
            var create = new { ChannelType = "Test", Name = "Test", Status = "Test", IsEnabled = true, IsDefault = true, SocialUsername = "Test", FromEmail = "Test", LastConnectedAt = DateTime.UtcNow, ChannelType = "Test", Name = "Test", Status = "Test", IsEnabled = true, IsDefault = true, SmtpServer = "Test", SmtpPort = 1, SmtpUseSsl = true, SmtpUsername = "Test", ImapServer = "Test", ImapPort = 1, ImapUseSsl = true, FromEmail = "Test", FromName = "Test", WhatsAppBusinessAccountId = "Test", WhatsAppPhoneNumberId = "Test", SocialAccountId = "Test", SocialUsername = "Test", WebhookUrl = "Test", WebhookEnabled = true, LastConnectedAt = DateTime.UtcNow, LastError = "Test", ChannelType = "Test", Name = "Test", IsEnabled = true, IsDefault = true, ApiKey = "Test", ApiSecret = "Test", ClientId = "Test", ClientSecret = "Test", AccessToken = "Test", RefreshToken = "Test", SmtpServer = "Test", SmtpPort = 1, SmtpUseSsl = true, SmtpUsername = "Test", SmtpPassword = "Test", ImapServer = "Test", ImapPort = 1, ImapUseSsl = true, FromEmail = "Test", FromName = "Test", WhatsAppBusinessAccountId = "Test", WhatsAppPhoneNumberId = "Test", WhatsAppVerifyToken = "Test", SocialAccountId = "Test", SocialUsername = "Test", PageAccessToken = "Test", ChannelType = "Test", Subject = "Test", BodyPreview = "Test", Direction = "Test", Status = "Test", FromAddress = "Test", FromName = "Test", ToAddress = "Test", ToName = "Test", AttachmentCount = 1, IsRead = true, IsStarred = true, SentAt = DateTime.UtcNow, ReceivedAt = DateTime.UtcNow, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", ChannelId = 1, ChannelType = "Test", ChannelName = "Test", Subject = "Test", Body = "Test", HtmlBody = "Test", Direction = "Test", Status = "Test", Priority = "Test", FromAddress = "Test", FromName = "Test", ToAddress = "Test", ToName = "Test", AttachmentCount = 1, ConversationId = "Test", ParentMessageId = 1, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", LeadId = 1, OpportunityId = 1, SentAt = DateTime.UtcNow, DeliveredAt = DateTime.UtcNow, ReadAt = DateTime.UtcNow, ReceivedAt = DateTime.UtcNow, OpenCount = 1, ClickCount = 1, IsPublicPost = true, LikeCount = 1, ShareCount = 1, CommentCount = 1, IsRead = true, IsStarred = true, IsArchived = true, ErrorMessage = "Test", FileName = "Test", ContentType = "Test", Size = 1, Url = "Test", ChannelId = 1, Subject = "Test", Body = "Test", HtmlBody = "Test", ToAddress = "Test", ToName = "Test", Priority = "Test", ScheduledAt = DateTime.UtcNow, TrackOpens = true, TrackClicks = true, EmailTemplateId = 1, AccountId = 1, ContactId = 1, LeadId = 1, OpportunityId = 1, ParentMessageId = 1, ConversationId = "Test", ChannelId = 1, Body = "Test", ScheduledAt = DateTime.UtcNow, InReplyToId = "Test", IsRetweet = true, IsQuoteRetweet = true, ChannelId = 1, ToPhoneNumber = "Test", MessageType = "Test", Body = "Test", MediaUrl = "Test", TemplateName = "Test", AccountId = 1, ContactId = 1, LeadId = 1, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", IsActive = true, IsSystem = true, UsageCount = 1, LastUsedAt = DateTime.UtcNow, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", PlainTextBody = "Test", HtmlBody = "Test", IsActive = true, IsSystem = true, FromEmail = "Test", FromName = "Test", ReplyToEmail = "Test", PreviewText = "Test", UsageCount = 1, LastUsedAt = DateTime.UtcNow, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", PlainTextBody = "Test", HtmlBody = "Test", IsActive = true, FromEmail = "Test", FromName = "Test", ReplyToEmail = "Test", PreviewText = "Test", ConversationId = "Test", ChannelType = "Test", Subject = "Test", LastMessagePreview = "Test", Status = "Test", ParticipantAddress = "Test", ParticipantName = "Test", MessageCount = 1, UnreadCount = 1, LastMessageAt = DateTime.UtcNow, IsStarred = true, IsPinned = true, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", ConversationId = "Test", ChannelType = "Test", Subject = "Test", Status = "Test", Priority = "Test", ParticipantAddress = "Test", ParticipantName = "Test", AccountId = 1, ContactId = 1, LeadId = 1, AssignedToUserId = 1, MessageCount = 1, UnreadCount = 1, FirstMessageAt = DateTime.UtcNow, LastMessageAt = DateTime.UtcNow, IsStarred = true, IsMuted = true, IsPinned = true, TotalMessages = 1, TotalInbound = 1, TotalOutbound = 1, UnreadCount = 1, OpenConversations = 1, PendingMessages = 1, EmailStats = null, WhatsAppStats = null, TwitterStats = null, FacebookStats = null, ChannelType = "Test", TotalMessages = 1, Inbound = 1, Outbound = 1, Unread = 1, Pending = 1, Failed = 1, OpenRate = 1, ClickRate = 1 };
            var cRes = await _client.PostAsJsonAsync("/api/communications", create);
            cRes.StatusCode.Should().Be(HttpStatusCode.Created);
            var item = await cRes.Content.ReadFromJsonAsync<dynamic>();

            item.ChannelType.Should().Be(create.ChannelType);
            item.Name.Should().Be(create.Name);
            item.Status.Should().Be(create.Status);
            item.IsEnabled.Should().Be(create.IsEnabled);
            item.IsDefault.Should().Be(create.IsDefault);
            item.SocialUsername.Should().Be(create.SocialUsername);
            item.FromEmail.Should().Be(create.FromEmail);
            item.LastConnectedAt.Should().Be(create.LastConnectedAt);
            item.ChannelType.Should().Be(create.ChannelType);
            item.Name.Should().Be(create.Name);
            item.Status.Should().Be(create.Status);
            item.IsEnabled.Should().Be(create.IsEnabled);
            item.IsDefault.Should().Be(create.IsDefault);
            item.SmtpServer.Should().Be(create.SmtpServer);
            item.SmtpPort.Should().Be(create.SmtpPort);
            item.SmtpUseSsl.Should().Be(create.SmtpUseSsl);
            item.SmtpUsername.Should().Be(create.SmtpUsername);
            item.ImapServer.Should().Be(create.ImapServer);
            item.ImapPort.Should().Be(create.ImapPort);
            item.ImapUseSsl.Should().Be(create.ImapUseSsl);
            item.FromEmail.Should().Be(create.FromEmail);
            item.FromName.Should().Be(create.FromName);
            item.WhatsAppBusinessAccountId.Should().Be(create.WhatsAppBusinessAccountId);
            item.WhatsAppPhoneNumberId.Should().Be(create.WhatsAppPhoneNumberId);
            item.SocialAccountId.Should().Be(create.SocialAccountId);
            item.SocialUsername.Should().Be(create.SocialUsername);
            item.WebhookUrl.Should().Be(create.WebhookUrl);
            item.WebhookEnabled.Should().Be(create.WebhookEnabled);
            item.LastConnectedAt.Should().Be(create.LastConnectedAt);
            item.LastError.Should().Be(create.LastError);
            item.ChannelType.Should().Be(create.ChannelType);
            item.Name.Should().Be(create.Name);
            item.IsEnabled.Should().Be(create.IsEnabled);
            item.IsDefault.Should().Be(create.IsDefault);
            item.ApiKey.Should().Be(create.ApiKey);
            item.ApiSecret.Should().Be(create.ApiSecret);
            item.ClientId.Should().Be(create.ClientId);
            item.ClientSecret.Should().Be(create.ClientSecret);
            item.AccessToken.Should().Be(create.AccessToken);
            item.RefreshToken.Should().Be(create.RefreshToken);
            item.SmtpServer.Should().Be(create.SmtpServer);
            item.SmtpPort.Should().Be(create.SmtpPort);
            item.SmtpUseSsl.Should().Be(create.SmtpUseSsl);
            item.SmtpUsername.Should().Be(create.SmtpUsername);
            item.SmtpPassword.Should().Be(create.SmtpPassword);
            item.ImapServer.Should().Be(create.ImapServer);
            item.ImapPort.Should().Be(create.ImapPort);
            item.ImapUseSsl.Should().Be(create.ImapUseSsl);
            item.FromEmail.Should().Be(create.FromEmail);
            item.FromName.Should().Be(create.FromName);
            item.WhatsAppBusinessAccountId.Should().Be(create.WhatsAppBusinessAccountId);
            item.WhatsAppPhoneNumberId.Should().Be(create.WhatsAppPhoneNumberId);
            item.WhatsAppVerifyToken.Should().Be(create.WhatsAppVerifyToken);
            item.SocialAccountId.Should().Be(create.SocialAccountId);
            item.SocialUsername.Should().Be(create.SocialUsername);
            item.PageAccessToken.Should().Be(create.PageAccessToken);
            item.ChannelType.Should().Be(create.ChannelType);
            item.Subject.Should().Be(create.Subject);
            item.BodyPreview.Should().Be(create.BodyPreview);
            item.Direction.Should().Be(create.Direction);
            item.Status.Should().Be(create.Status);
            item.FromAddress.Should().Be(create.FromAddress);
            item.FromName.Should().Be(create.FromName);
            item.ToAddress.Should().Be(create.ToAddress);
            item.ToName.Should().Be(create.ToName);
            item.AttachmentCount.Should().Be(create.AttachmentCount);
            item.IsRead.Should().Be(create.IsRead);
            item.IsStarred.Should().Be(create.IsStarred);
            item.SentAt.Should().Be(create.SentAt);
            item.ReceivedAt.Should().Be(create.ReceivedAt);
            item.AccountId.Should().Be(create.AccountId);
            item.AccountName.Should().Be(create.AccountName);
            item.ContactId.Should().Be(create.ContactId);
            item.ContactName.Should().Be(create.ContactName);
            item.ChannelId.Should().Be(create.ChannelId);
            item.ChannelType.Should().Be(create.ChannelType);
            item.ChannelName.Should().Be(create.ChannelName);
            item.Subject.Should().Be(create.Subject);
            item.Body.Should().Be(create.Body);
            item.HtmlBody.Should().Be(create.HtmlBody);
            item.Direction.Should().Be(create.Direction);
            item.Status.Should().Be(create.Status);
            item.Priority.Should().Be(create.Priority);
            item.FromAddress.Should().Be(create.FromAddress);
            item.FromName.Should().Be(create.FromName);
            item.ToAddress.Should().Be(create.ToAddress);
            item.ToName.Should().Be(create.ToName);
            item.AttachmentCount.Should().Be(create.AttachmentCount);
            item.ConversationId.Should().Be(create.ConversationId);
            item.ParentMessageId.Should().Be(create.ParentMessageId);
            item.AccountId.Should().Be(create.AccountId);
            item.AccountName.Should().Be(create.AccountName);
            item.ContactId.Should().Be(create.ContactId);
            item.ContactName.Should().Be(create.ContactName);
            item.LeadId.Should().Be(create.LeadId);
            item.OpportunityId.Should().Be(create.OpportunityId);
            item.SentAt.Should().Be(create.SentAt);
            item.DeliveredAt.Should().Be(create.DeliveredAt);
            item.ReadAt.Should().Be(create.ReadAt);
            item.ReceivedAt.Should().Be(create.ReceivedAt);
            item.OpenCount.Should().Be(create.OpenCount);
            item.ClickCount.Should().Be(create.ClickCount);
            item.IsPublicPost.Should().Be(create.IsPublicPost);
            item.LikeCount.Should().Be(create.LikeCount);
            item.ShareCount.Should().Be(create.ShareCount);
            item.CommentCount.Should().Be(create.CommentCount);
            item.IsRead.Should().Be(create.IsRead);
            item.IsStarred.Should().Be(create.IsStarred);
            item.IsArchived.Should().Be(create.IsArchived);
            item.ErrorMessage.Should().Be(create.ErrorMessage);
            item.FileName.Should().Be(create.FileName);
            item.ContentType.Should().Be(create.ContentType);
            item.Size.Should().Be(create.Size);
            item.Url.Should().Be(create.Url);
            item.ChannelId.Should().Be(create.ChannelId);
            item.Subject.Should().Be(create.Subject);
            item.Body.Should().Be(create.Body);
            item.HtmlBody.Should().Be(create.HtmlBody);
            item.ToAddress.Should().Be(create.ToAddress);
            item.ToName.Should().Be(create.ToName);
            item.Priority.Should().Be(create.Priority);
            item.ScheduledAt.Should().Be(create.ScheduledAt);
            item.TrackOpens.Should().Be(create.TrackOpens);
            item.TrackClicks.Should().Be(create.TrackClicks);
            item.EmailTemplateId.Should().Be(create.EmailTemplateId);
            item.AccountId.Should().Be(create.AccountId);
            item.ContactId.Should().Be(create.ContactId);
            item.LeadId.Should().Be(create.LeadId);
            item.OpportunityId.Should().Be(create.OpportunityId);
            item.ParentMessageId.Should().Be(create.ParentMessageId);
            item.ConversationId.Should().Be(create.ConversationId);
            item.ChannelId.Should().Be(create.ChannelId);
            item.Body.Should().Be(create.Body);
            item.ScheduledAt.Should().Be(create.ScheduledAt);
            item.InReplyToId.Should().Be(create.InReplyToId);
            item.IsRetweet.Should().Be(create.IsRetweet);
            item.IsQuoteRetweet.Should().Be(create.IsQuoteRetweet);
            item.ChannelId.Should().Be(create.ChannelId);
            item.ToPhoneNumber.Should().Be(create.ToPhoneNumber);
            item.MessageType.Should().Be(create.MessageType);
            item.Body.Should().Be(create.Body);
            item.MediaUrl.Should().Be(create.MediaUrl);
            item.TemplateName.Should().Be(create.TemplateName);
            item.AccountId.Should().Be(create.AccountId);
            item.ContactId.Should().Be(create.ContactId);
            item.LeadId.Should().Be(create.LeadId);
            item.Name.Should().Be(create.Name);
            item.Description.Should().Be(create.Description);
            item.Category.Should().Be(create.Category);
            item.Subject.Should().Be(create.Subject);
            item.IsActive.Should().Be(create.IsActive);
            item.IsSystem.Should().Be(create.IsSystem);
            item.UsageCount.Should().Be(create.UsageCount);
            item.LastUsedAt.Should().Be(create.LastUsedAt);
            item.Name.Should().Be(create.Name);
            item.Description.Should().Be(create.Description);
            item.Category.Should().Be(create.Category);
            item.Subject.Should().Be(create.Subject);
            item.PlainTextBody.Should().Be(create.PlainTextBody);
            item.HtmlBody.Should().Be(create.HtmlBody);
            item.IsActive.Should().Be(create.IsActive);
            item.IsSystem.Should().Be(create.IsSystem);
            item.FromEmail.Should().Be(create.FromEmail);
            item.FromName.Should().Be(create.FromName);
            item.ReplyToEmail.Should().Be(create.ReplyToEmail);
            item.PreviewText.Should().Be(create.PreviewText);
            item.UsageCount.Should().Be(create.UsageCount);
            item.LastUsedAt.Should().Be(create.LastUsedAt);
            item.Name.Should().Be(create.Name);
            item.Description.Should().Be(create.Description);
            item.Category.Should().Be(create.Category);
            item.Subject.Should().Be(create.Subject);
            item.PlainTextBody.Should().Be(create.PlainTextBody);
            item.HtmlBody.Should().Be(create.HtmlBody);
            item.IsActive.Should().Be(create.IsActive);
            item.FromEmail.Should().Be(create.FromEmail);
            item.FromName.Should().Be(create.FromName);
            item.ReplyToEmail.Should().Be(create.ReplyToEmail);
            item.PreviewText.Should().Be(create.PreviewText);
            item.ConversationId.Should().Be(create.ConversationId);
            item.ChannelType.Should().Be(create.ChannelType);
            item.Subject.Should().Be(create.Subject);
            item.LastMessagePreview.Should().Be(create.LastMessagePreview);
            item.Status.Should().Be(create.Status);
            item.ParticipantAddress.Should().Be(create.ParticipantAddress);
            item.ParticipantName.Should().Be(create.ParticipantName);
            item.MessageCount.Should().Be(create.MessageCount);
            item.UnreadCount.Should().Be(create.UnreadCount);
            item.LastMessageAt.Should().Be(create.LastMessageAt);
            item.IsStarred.Should().Be(create.IsStarred);
            item.IsPinned.Should().Be(create.IsPinned);
            item.AccountId.Should().Be(create.AccountId);
            item.AccountName.Should().Be(create.AccountName);
            item.ContactId.Should().Be(create.ContactId);
            item.ContactName.Should().Be(create.ContactName);
            item.ConversationId.Should().Be(create.ConversationId);
            item.ChannelType.Should().Be(create.ChannelType);
            item.Subject.Should().Be(create.Subject);
            item.Status.Should().Be(create.Status);
            item.Priority.Should().Be(create.Priority);
            item.ParticipantAddress.Should().Be(create.ParticipantAddress);
            item.ParticipantName.Should().Be(create.ParticipantName);
            item.AccountId.Should().Be(create.AccountId);
            item.ContactId.Should().Be(create.ContactId);
            item.LeadId.Should().Be(create.LeadId);
            item.AssignedToUserId.Should().Be(create.AssignedToUserId);
            item.MessageCount.Should().Be(create.MessageCount);
            item.UnreadCount.Should().Be(create.UnreadCount);
            item.FirstMessageAt.Should().Be(create.FirstMessageAt);
            item.LastMessageAt.Should().Be(create.LastMessageAt);
            item.IsStarred.Should().Be(create.IsStarred);
            item.IsMuted.Should().Be(create.IsMuted);
            item.IsPinned.Should().Be(create.IsPinned);
            item.TotalMessages.Should().Be(create.TotalMessages);
            item.TotalInbound.Should().Be(create.TotalInbound);
            item.TotalOutbound.Should().Be(create.TotalOutbound);
            item.UnreadCount.Should().Be(create.UnreadCount);
            item.OpenConversations.Should().Be(create.OpenConversations);
            item.PendingMessages.Should().Be(create.PendingMessages);
            item.EmailStats.Should().Be(create.EmailStats);
            item.WhatsAppStats.Should().Be(create.WhatsAppStats);
            item.TwitterStats.Should().Be(create.TwitterStats);
            item.FacebookStats.Should().Be(create.FacebookStats);
            item.ChannelType.Should().Be(create.ChannelType);
            item.TotalMessages.Should().Be(create.TotalMessages);
            item.Inbound.Should().Be(create.Inbound);
            item.Outbound.Should().Be(create.Outbound);
            item.Unread.Should().Be(create.Unread);
            item.Pending.Should().Be(create.Pending);
            item.Failed.Should().Be(create.Failed);
            item.OpenRate.Should().Be(create.OpenRate);
            item.ClickRate.Should().Be(create.ClickRate);

            var getRes = await _client.GetAsync($"/api/communications/{{item.Id}}");
            getRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var patch = new { ChannelType = "Test2", Name = "Test", Status = "Test", IsEnabled = true, IsDefault = true, SocialUsername = "Test", FromEmail = "Test", LastConnectedAt = DateTime.UtcNow, ChannelType = "Test2", Name = "Test", Status = "Test", IsEnabled = true, IsDefault = true, SmtpServer = "Test", SmtpPort = 1, SmtpUseSsl = true, SmtpUsername = "Test", ImapServer = "Test", ImapPort = 1, ImapUseSsl = true, FromEmail = "Test", FromName = "Test", WhatsAppBusinessAccountId = "Test", WhatsAppPhoneNumberId = "Test", SocialAccountId = "Test", SocialUsername = "Test", WebhookUrl = "Test", WebhookEnabled = true, LastConnectedAt = DateTime.UtcNow, LastError = "Test", ChannelType = "Test2", Name = "Test", IsEnabled = true, IsDefault = true, ApiKey = "Test", ApiSecret = "Test", ClientId = "Test", ClientSecret = "Test", AccessToken = "Test", RefreshToken = "Test", SmtpServer = "Test", SmtpPort = 1, SmtpUseSsl = true, SmtpUsername = "Test", SmtpPassword = "Test", ImapServer = "Test", ImapPort = 1, ImapUseSsl = true, FromEmail = "Test", FromName = "Test", WhatsAppBusinessAccountId = "Test", WhatsAppPhoneNumberId = "Test", WhatsAppVerifyToken = "Test", SocialAccountId = "Test", SocialUsername = "Test", PageAccessToken = "Test", ChannelType = "Test2", Subject = "Test", BodyPreview = "Test", Direction = "Test", Status = "Test", FromAddress = "Test", FromName = "Test", ToAddress = "Test", ToName = "Test", AttachmentCount = 1, IsRead = true, IsStarred = true, SentAt = DateTime.UtcNow, ReceivedAt = DateTime.UtcNow, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", ChannelId = 1, ChannelType = "Test2", ChannelName = "Test", Subject = "Test", Body = "Test", HtmlBody = "Test", Direction = "Test", Status = "Test", Priority = "Test", FromAddress = "Test", FromName = "Test", ToAddress = "Test", ToName = "Test", AttachmentCount = 1, ConversationId = "Test", ParentMessageId = 1, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", LeadId = 1, OpportunityId = 1, SentAt = DateTime.UtcNow, DeliveredAt = DateTime.UtcNow, ReadAt = DateTime.UtcNow, ReceivedAt = DateTime.UtcNow, OpenCount = 1, ClickCount = 1, IsPublicPost = true, LikeCount = 1, ShareCount = 1, CommentCount = 1, IsRead = true, IsStarred = true, IsArchived = true, ErrorMessage = "Test", FileName = "Test", ContentType = "Test", Size = 1, Url = "Test", ChannelId = 1, Subject = "Test", Body = "Test", HtmlBody = "Test", ToAddress = "Test", ToName = "Test", Priority = "Test", ScheduledAt = DateTime.UtcNow, TrackOpens = true, TrackClicks = true, EmailTemplateId = 1, AccountId = 1, ContactId = 1, LeadId = 1, OpportunityId = 1, ParentMessageId = 1, ConversationId = "Test", ChannelId = 1, Body = "Test", ScheduledAt = DateTime.UtcNow, InReplyToId = "Test", IsRetweet = true, IsQuoteRetweet = true, ChannelId = 1, ToPhoneNumber = "Test", MessageType = "Test", Body = "Test", MediaUrl = "Test", TemplateName = "Test", AccountId = 1, ContactId = 1, LeadId = 1, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", IsActive = true, IsSystem = true, UsageCount = 1, LastUsedAt = DateTime.UtcNow, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", PlainTextBody = "Test", HtmlBody = "Test", IsActive = true, IsSystem = true, FromEmail = "Test", FromName = "Test", ReplyToEmail = "Test", PreviewText = "Test", UsageCount = 1, LastUsedAt = DateTime.UtcNow, Name = "Test", Description = "Test", Category = "Test", Subject = "Test", PlainTextBody = "Test", HtmlBody = "Test", IsActive = true, FromEmail = "Test", FromName = "Test", ReplyToEmail = "Test", PreviewText = "Test", ConversationId = "Test", ChannelType = "Test2", Subject = "Test", LastMessagePreview = "Test", Status = "Test", ParticipantAddress = "Test", ParticipantName = "Test", MessageCount = 1, UnreadCount = 1, LastMessageAt = DateTime.UtcNow, IsStarred = true, IsPinned = true, AccountId = 1, AccountName = "Test", ContactId = 1, ContactName = "Test", ConversationId = "Test", ChannelType = "Test2", Subject = "Test", Status = "Test", Priority = "Test", ParticipantAddress = "Test", ParticipantName = "Test", AccountId = 1, ContactId = 1, LeadId = 1, AssignedToUserId = 1, MessageCount = 1, UnreadCount = 1, FirstMessageAt = DateTime.UtcNow, LastMessageAt = DateTime.UtcNow, IsStarred = true, IsMuted = true, IsPinned = true, TotalMessages = 1, TotalInbound = 1, TotalOutbound = 1, UnreadCount = 1, OpenConversations = 1, PendingMessages = 1, EmailStats = null, WhatsAppStats = null, TwitterStats = null, FacebookStats = null, ChannelType = "Test2", TotalMessages = 1, Inbound = 1, Outbound = 1, Unread = 1, Pending = 1, Failed = 1, OpenRate = 1, ClickRate = 1 };
            var pRes = await _client.PatchAsJsonAsync($"/api/communications/{{item.Id}}", patch);
            pRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var del = await _client.DeleteAsync($"/api/communications/{{item.Id}}");
            del.StatusCode.Should().Be(HttpStatusCode.NoContent);
            var nf = await _client.GetAsync($"/api/communications/{{item.Id}}");
            nf.StatusCode.Should().Be(HttpStatusCode.NotFound);
        }

        [Fact]
        public async Task Get_Nonexistent_Returns404()
        {
            var res = await _client.GetAsync("/api/communications/999999");
            Assert.Equal(HttpStatusCode.NotFound, res.StatusCode);
        }
    }
}

