// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This software is source-available. Non-commercial use is permitted under
// the terms of the LICENSE file. Commercial use requires a separate license.
// See the LICENSE file in the root directory for full terms.
using CRM.Tests.Helpers;
using FluentAssertions;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Xunit;

namespace CRM.Backend.Tests.Integration.Controllers
{
    public class ServiceRequestsControllerTests : IClassFixture<ApiTestFactory>
    {
        private readonly HttpClient _client;
        public ServiceRequestsControllerTests(ApiTestFactory factory) => _client = factory.CreateClient();

        [Fact]
        public async Task Crud_ServiceRequests_Succeeds()
        {
            var create = new
            {
                Name = "Test",
                Description = "Test",
                DisplayOrder = 1,
                IsActive = true,
                IconName = "Test",
                ColorCode = "Test",
                DefaultResponseTimeHours = 1,
                DefaultResolutionTimeHours = 1,
                SubcategoryCount = 1,
                ServiceRequestCount = 1,
                CategoryId = 1,
                CategoryName = "Test",
                ResponseTimeHours = 1,
                ResolutionTimeHours = 1,
                DefaultPriority = (object?)null,
                DefaultWorkflowId = 1,
                DefaultWorkflowName = "Test",
                FieldKey = "Test",
                FieldType = (object?)null,
                IsRequired = true,
                DefaultValue = "Test",
                Placeholder = "Test",
                HelpText = "Test",
                DropdownOptions = "Test",
                MinValue = 1,
                MaxValue = 1,
                MaxLength = 1,
                ValidationPattern = "Test",
                ValidationMessage = "Test",
                SubcategoryId = 1,
                SubcategoryName = "Test",
                ServiceRequestId = 1,
                CustomFieldDefinitionId = 1,
                FieldName = "Test",
                TextValue = "Test",
                NumericValue = 1,
                DateValue = DateTime.UtcNow,
                BooleanValue = true,
                DisplayValue = (object?)null,
                TicketNumber = "Test",
                Subject = "Test",
                Channel = (object?)null,
                ChannelName = "Test",
                Status = (object?)null,
                StatusName = "Test",
                Priority = (object?)null,
                PriorityName = "Test",
                AccountId = 1,
                AccountName = "Test",
                ContactId = 1,
                ContactName = "Test",
                RequesterName = "Test",
                RequesterEmail = "Test",
                RequesterPhone = "Test",
                AssignedToUserId = 1,
                AssignedToUserName = "Test",
                AssignedToGroupId = 1,
                AssignedToGroupName = "Test",
                CreatedByUserId = 1,
                CreatedByUserName = "Test",
                WorkflowId = 1,
                WorkflowName = "Test",
                CurrentWorkflowStep = "Test",
                ResponseDueDate = DateTime.UtcNow,
                ResolutionDueDate = DateTime.UtcNow,
                FirstResponseDate = DateTime.UtcNow,
                ResolvedDate = DateTime.UtcNow,
                ClosedDate = DateTime.UtcNow,
                ResponseSlaBreached = true,
                ResolutionSlaBreached = true,
                ExternalReferenceId = "Test",
                SourcePhoneNumber = "Test",
                SourceEmailAddress = "Test",
                ResolutionSummary = "Test",
                ResolutionCode = "Test",
                RootCause = "Test",
                SatisfactionRating = 1,
                CustomerFeedback = "Test",
                RelatedOpportunityId = 1,
                RelatedOpportunityName = "Test",
                RelatedProductId = 1,
                RelatedProductName = "Test",
                ParentServiceRequestId = 1,
                ParentTicketNumber = "Test",
                Tags = "Test",
                InternalNotes = "Test",
                EscalationLevel = 1,
                ReopenCount = 1,
                IsVipAccount = true,
                EstimatedEffortHours = 1,
                ActualEffortHours = 1,
                IsOpen = true,
                AgeInHours = 1,
                TimeToFirstResponseHours = 1,
                TimeToResolutionHours = 1,
                IsResponseSlaAtRisk = true,
                IsResolutionSlaAtRisk = true,
                ChildRequestCount = 1,
                ConversationId = "Test",
                SearchTerm = "Test",
                CreatedFrom = DateTime.UtcNow,
                CreatedTo = DateTime.UtcNow,
                ResolvedFrom = DateTime.UtcNow,
                ResolvedTo = DateTime.UtcNow,
                Page = 1,
                PageSize = 1,
                SortBy = "Test",
                SortDescending = true,
                TotalCount = 1,
                RequestType = "Test",
                DetailedDescription = "Test",
                PossibleResolutions = "Test",
                FinalCustomerResolutions = "Test",
                TotalRequests = 1,
                OpenRequests = 1,
                NewRequests = 1,
                InProgressRequests = 1,
                PendingRequests = 1,
                EscalatedRequests = 1,
                ResolvedToday = 1,
                CreatedToday = 1,
                SlaBreachedCount = 1,
                SlaAtRiskCount = 1,
                AverageResolutionTimeHours = 1,
                AverageFirstResponseTimeHours = 1,
                CustomerSatisfactionAverage = 1
            };
            var cRes = await _client.PostAsJsonAsync("/api/servicerequests", create);
            cRes.StatusCode.Should().Be(HttpStatusCode.Created);
            var item = await cRes.Content.ReadFromJsonAsync<JsonElement>();
            var id = item.GetProperty("id").GetInt32();

            var getRes = await _client.GetAsync($"/api/servicerequests/{id}");
            getRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var patch = new
            {
                Name = "Test2",
                Description = "Test",
                DisplayOrder = 1,
                IsActive = true,
                IconName = "Test",
                ColorCode = "Test",
                DefaultResponseTimeHours = 1,
                DefaultResolutionTimeHours = 1,
                SubcategoryCount = 1,
                ServiceRequestCount = 1,
                CategoryId = 1,
                CategoryName = "Test",
                ResponseTimeHours = 1,
                ResolutionTimeHours = 1,
                DefaultPriority = (object?)null,
                DefaultWorkflowId = 1,
                DefaultWorkflowName = "Test",
                FieldKey = "Test",
                FieldType = (object?)null,
                IsRequired = true,
                DefaultValue = "Test",
                Placeholder = "Test",
                HelpText = "Test",
                DropdownOptions = "Test",
                MinValue = 1,
                MaxValue = 1,
                MaxLength = 1,
                ValidationPattern = "Test",
                ValidationMessage = "Test",
                SubcategoryId = 1,
                SubcategoryName = "Test",
                ServiceRequestId = 1,
                CustomFieldDefinitionId = 1,
                FieldName = "Test",
                TextValue = "Test",
                NumericValue = 1,
                DateValue = DateTime.UtcNow,
                BooleanValue = true,
                DisplayValue = (object?)null,
                TicketNumber = "Test",
                Subject = "Test",
                Channel = (object?)null,
                ChannelName = "Test",
                Status = (object?)null,
                StatusName = "Test",
                Priority = (object?)null,
                PriorityName = "Test",
                AccountId = 1,
                AccountName = "Test",
                ContactId = 1,
                ContactName = "Test",
                RequesterName = "Test",
                RequesterEmail = "Test",
                RequesterPhone = "Test",
                AssignedToUserId = 1,
                AssignedToUserName = "Test",
                AssignedToGroupId = 1,
                AssignedToGroupName = "Test",
                CreatedByUserId = 1,
                CreatedByUserName = "Test",
                WorkflowId = 1,
                WorkflowName = "Test",
                CurrentWorkflowStep = "Test",
                ResponseDueDate = DateTime.UtcNow,
                ResolutionDueDate = DateTime.UtcNow,
                FirstResponseDate = DateTime.UtcNow,
                ResolvedDate = DateTime.UtcNow,
                ClosedDate = DateTime.UtcNow,
                ResponseSlaBreached = true,
                ResolutionSlaBreached = true,
                ExternalReferenceId = "Test",
                SourcePhoneNumber = "Test",
                SourceEmailAddress = "Test",
                ResolutionSummary = "Test",
                ResolutionCode = "Test",
                RootCause = "Test",
                SatisfactionRating = 1,
                CustomerFeedback = "Test",
                RelatedOpportunityId = 1,
                RelatedOpportunityName = "Test",
                RelatedProductId = 1,
                RelatedProductName = "Test",
                ParentServiceRequestId = 1,
                ParentTicketNumber = "Test",
                Tags = "Test",
                InternalNotes = "Test",
                EscalationLevel = 1,
                ReopenCount = 1,
                IsVipAccount = true,
                EstimatedEffortHours = 1,
                ActualEffortHours = 1,
                IsOpen = true,
                AgeInHours = 1,
                TimeToFirstResponseHours = 1,
                TimeToResolutionHours = 1,
                IsResponseSlaAtRisk = true,
                IsResolutionSlaAtRisk = true,
                ChildRequestCount = 1,
                ConversationId = "Test",
                SearchTerm = "Test",
                CreatedFrom = DateTime.UtcNow,
                CreatedTo = DateTime.UtcNow,
                ResolvedFrom = DateTime.UtcNow,
                ResolvedTo = DateTime.UtcNow,
                Page = 1,
                PageSize = 1,
                SortBy = "Test",
                SortDescending = true,
                TotalCount = 1,
                RequestType = "Test",
                DetailedDescription = "Test",
                PossibleResolutions = "Test",
                FinalCustomerResolutions = "Test",
                TotalRequests = 1,
                OpenRequests = 1,
                NewRequests = 1,
                InProgressRequests = 1,
                PendingRequests = 1,
                EscalatedRequests = 1,
                ResolvedToday = 1,
                CreatedToday = 1,
                SlaBreachedCount = 1,
                SlaAtRiskCount = 1,
                AverageResolutionTimeHours = 1,
                AverageFirstResponseTimeHours = 1,
                CustomerSatisfactionAverage = 1
            };
            var pRes = await _client.PatchAsJsonAsync($"/api/servicerequests/{id}", patch);
            pRes.StatusCode.Should().Be(HttpStatusCode.OK);
            var del = await _client.DeleteAsync($"/api/servicerequests/{id}");
            del.StatusCode.Should().Be(HttpStatusCode.NoContent);
            var nf = await _client.GetAsync($"/api/servicerequests/{id}");
            nf.StatusCode.Should().Be(HttpStatusCode.NotFound);
        }

        [Fact]
        public async Task Get_Nonexistent_Returns404()
        {
            var res = await _client.GetAsync("/api/servicerequests/999999");
            Assert.Equal(HttpStatusCode.NotFound, res.StatusCode);
        }
    }
}
