-- Create missing tables for CRM database
-- These tables were part of migration 20260214195347 which partially failed

-- 1. Quotes

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `Quotes` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `QuoteNumber` varchar(50) NOT NULL,
  `ExternalQuoteId` varchar(100) NULL,
  `Version` int NOT NULL DEFAULT 1,
  `Name` varchar(255) NOT NULL,
  `Description` text NULL,
  `Status` int NOT NULL DEFAULT 0,
  `QuoteDate` datetime(6) NOT NULL,
  `ExpirationDate` datetime(6) NULL,
  `SentDate` datetime(6) NULL,
  `ViewedDate` datetime(6) NULL,
  `AcceptedDate` datetime(6) NULL,
  `RejectedDate` datetime(6) NULL,
  `Subtotal` decimal(65,30) NOT NULL DEFAULT 0,
  `Discount` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountReason` varchar(500) NULL,
  `Tax` decimal(65,30) NOT NULL DEFAULT 0,
  `TaxRate` decimal(65,30) NOT NULL DEFAULT 0,
  `ShippingCost` decimal(65,30) NOT NULL DEFAULT 0,
  `Total` decimal(65,30) NOT NULL DEFAULT 0,
  `CurrencyCode` varchar(3) NULL,
  `PaymentTerms` varchar(200) NULL,
  `DeliveryTerms` varchar(500) NULL,
  `TermsAndConditions` text NULL,
  `Warranty` text NULL,
  `ValidityDays` int NULL,
  `LineItems` text NULL,
  `BillingName` varchar(200) NULL,
  `BillingAddress` varchar(500) NULL,
  `BillingCity` varchar(100) NULL,
  `BillingState` varchar(100) NULL,
  `BillingZipCode` varchar(20) NULL,
  `BillingCountry` varchar(100) NULL,
  `ShippingName` varchar(200) NULL,
  `ShippingAddress` varchar(500) NULL,
  `ShippingCity` varchar(100) NULL,
  `ShippingState` varchar(100) NULL,
  `ShippingZipCode` varchar(20) NULL,
  `ShippingCountry` varchar(100) NULL,
  `ContactName` varchar(200) NULL,
  `ContactEmail` varchar(200) NULL,
  `ContactPhone` varchar(50) NULL,
  `AccountId` int NULL,
  `ContactId` int NULL,
  `OpportunityId` int NULL,
  `AssignedToUserId` int NULL,
  `CreatedByUserId` int NULL,
  `ApprovedByUserId` int NULL,
  `ParentQuoteId` int NULL,
  `RelationshipManagerId` int NULL,
  `RequiresApproval` tinyint(1) NOT NULL DEFAULT 0,
  `IsApproved` tinyint(1) NOT NULL DEFAULT 0,
  `ApprovalDate` datetime(6) NULL,
  `ApprovalNotes` varchar(2000) NULL,
  `SubmittedForApprovalDate` datetime(6) NULL,
  `IsSigned` tinyint(1) NOT NULL DEFAULT 0,
  `SignedDate` datetime(6) NULL,
  `SignedBy` varchar(200) NULL,
  `SignatureUrl` varchar(1000) NULL,
  `Notes` text NULL,
  `InternalNotes` text NULL,
  `Attachments` text NULL,
  `QuotePdfUrl` varchar(1000) NULL,
  `Tags` varchar(500) NULL,
  `Category` varchar(100) NULL,
  `ExpectedDeliveryDate` datetime(6) NULL,
  `ActualDeliveryDate` datetime(6) NULL,
  `WarrantyMonths` int NULL,
  `WarrantyEndDate` datetime(6) NULL,
  `ServiceStartDate` datetime(6) NULL,
  `ServiceEndDate` datetime(6) NULL,
  `CustomFields` text NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. QuoteLineItems
CREATE TABLE IF NOT EXISTS `QuoteLineItems` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `QuoteId` int NOT NULL,
  `LineNumber` int NOT NULL DEFAULT 0,
  `ProductId` int NULL,
  `SKU` varchar(100) NULL,
  `Name` varchar(255) NOT NULL,
  `Description` varchar(2000) NULL,
  `Category` varchar(100) NULL,
  `Quantity` decimal(18,4) NOT NULL DEFAULT 0,
  `UnitOfMeasure` varchar(50) NULL,
  `UnitPrice` decimal(18,2) NOT NULL DEFAULT 0,
  `ListPrice` decimal(18,2) NULL,
  `CostPrice` decimal(18,2) NULL,
  `DiscountType` int NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(5,2) NOT NULL DEFAULT 0,
  `DiscountAmount` decimal(18,2) NOT NULL DEFAULT 0,
  `DiscountReason` varchar(500) NULL,
  `DiscountRequiresApproval` tinyint(1) NOT NULL DEFAULT 0,
  `DiscountApproved` tinyint(1) NOT NULL DEFAULT 0,
  `TaxRate` decimal(5,2) NOT NULL DEFAULT 0,
  `IsTaxable` tinyint(1) NOT NULL DEFAULT 1,
  `TaxCode` varchar(50) NULL,
  `Subtotal` decimal(18,2) NOT NULL DEFAULT 0,
  `TotalDiscount` decimal(18,2) NOT NULL DEFAULT 0,
  `TaxAmount` decimal(18,2) NOT NULL DEFAULT 0,
  `Total` decimal(18,2) NOT NULL DEFAULT 0,
  `Margin` decimal(18,2) NULL,
  `BillingPeriod` varchar(50) NULL,
  `WarrantyMonths` int NULL,
  `DeliveryDate` datetime(6) NULL,
  `ServiceStartDate` datetime(6) NULL,
  `ServiceEndDate` datetime(6) NULL,
  `IsOptional` tinyint(1) NOT NULL DEFAULT 0,
  `IsIncluded` tinyint(1) NOT NULL DEFAULT 1,
  `ParentLineItemId` int NULL,
  `IsBundle` tinyint(1) NOT NULL DEFAULT 0,
  `InternalNotes` varchar(2000) NULL,
  `QuoteNotes` varchar(2000) NULL,
  `CustomFields` text NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_QuoteLineItems_Quotes_QuoteId` FOREIGN KEY (`QuoteId`) REFERENCES `Quotes` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Subscriptions
CREATE TABLE IF NOT EXISTS `Subscriptions` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `SubscriptionNumber` varchar(100) NOT NULL,
  `AccountId` int NOT NULL,
  `ProductId` int NULL,
  `SubscriptionStatus` int NOT NULL DEFAULT 0,
  `MRR` decimal(65,30) NULL,
  `ARR` decimal(65,30) NULL,
  `OneTimeFee` decimal(65,30) NULL,
  `Currency` varchar(10) NULL,
  `CurrencyLookupId` int NULL,
  `BillingCycle` varchar(50) NULL,
  `BillingStartDate` datetime(6) NULL,
  `BillingEndDate` datetime(6) NULL,
  `ContractReference` varchar(200) NULL,
  `ContractStartDate` datetime(6) NULL,
  `ContractEndDate` datetime(6) NULL,
  `TermCategory` int NULL,
  `ServiceTier` int NULL,
  `SLA` varchar(255) NULL,
  `ContractNotes` text NULL,
  `BillingAddress` varchar(255) NULL,
  `BillingCity` varchar(100) NULL,
  `BillingState` varchar(100) NULL,
  `BillingZip` varchar(20) NULL,
  `BillingCountry` varchar(100) NULL,
  `BillingContactName` varchar(255) NULL,
  `BillingContactEmail` varchar(255) NULL,
  `BillingContactPhone` varchar(30) NULL,
  `ContractFileName` varchar(1000) NULL,
  `ContractFilePath` varchar(2000) NULL,
  `ContractContentType` varchar(200) NULL,
  `ContractFileSize` bigint NULL,
  `IsAutoRenew` tinyint(1) NOT NULL DEFAULT 0,
  `RenewalDate` datetime(6) NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `SubscriptionOwner` varchar(255) NULL,
  `SubscriptionManagerId` int NULL,
  `Tags` varchar(500) NULL,
  `ExternalReference` varchar(50) NULL,
  `OrderId` int NULL,
  `Amount` decimal(65,30) NOT NULL DEFAULT 0,
  `StartDate` datetime(6) NULL,
  `EndDate` datetime(6) NULL,
  `NextBillingDate` datetime(6) NULL,
  `CurrentPeriodEnd` datetime(6) NULL,
  `CurrentPeriodStart` datetime(6) NULL,
  `CancelledAt` datetime(6) NULL,
  `CancellationReason` text NULL,
  `CancelAtPeriodEnd` tinyint(1) NOT NULL DEFAULT 0,
  `PausedAt` datetime(6) NULL,
  `PauseReason` text NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Subscriptions_Accounts_AccountId` FOREIGN KEY (`AccountId`) REFERENCES `Accounts` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Invoices
CREATE TABLE IF NOT EXISTS `Invoices` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `InvoiceNumber` varchar(50) NOT NULL,
  `ExternalInvoiceId` varchar(100) NULL,
  `ReferenceNumber` varchar(100) NULL,
  `BatchNumber` varchar(50) NULL,
  `Description` varchar(1000) NULL,
  `Status` int NOT NULL DEFAULT 0,
  `InvoiceType` int NOT NULL DEFAULT 0,
  `PaymentTerms` int NOT NULL DEFAULT 0,
  `PaymentTermsDescription` varchar(500) NULL,
  `InvoiceDate` datetime(6) NOT NULL,
  `DueDate` datetime(6) NOT NULL,
  `SentDate` datetime(6) NULL,
  `ViewedDate` datetime(6) NULL,
  `PaidDate` datetime(6) NULL,
  `VoidedDate` datetime(6) NULL,
  `ServicePeriodStart` datetime(6) NULL,
  `ServicePeriodEnd` datetime(6) NULL,
  `Subtotal` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(65,30) NOT NULL DEFAULT 0,
  `TaxAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `TaxRate` decimal(65,30) NOT NULL DEFAULT 0,
  `ShippingAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `FeesAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `TotalAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `AmountPaid` decimal(65,30) NOT NULL DEFAULT 0,
  `AmountCredited` decimal(65,30) NOT NULL DEFAULT 0,
  `CurrencyCode` varchar(3) NOT NULL DEFAULT 'USD',
  `ExchangeRate` decimal(65,30) NULL,
  `EarlyPaymentDiscountPercent` decimal(65,30) NULL,
  `EarlyPaymentDiscountDays` int NULL,
  `EarlyPaymentDiscountAmount` decimal(65,30) NULL,
  `LateFeePercent` decimal(65,30) NULL,
  `LateFeeAmount` decimal(65,30) NULL,
  `LateFeeTotal` decimal(65,30) NOT NULL DEFAULT 0,
  `BillingName` varchar(255) NULL,
  `BillingCompany` varchar(255) NULL,
  `BillingStreet` varchar(500) NULL,
  `BillingCity` varchar(100) NULL,
  `BillingState` varchar(100) NULL,
  `BillingPostalCode` varchar(20) NULL,
  `BillingCountry` varchar(100) NULL,
  `BillingEmail` varchar(255) NULL,
  `BillingPhone` varchar(30) NULL,
  `ReminderCount` int NOT NULL DEFAULT 0,
  `LastReminderDate` datetime(6) NULL,
  `NextReminderDate` datetime(6) NULL,
  `InCollections` tinyint(1) NOT NULL DEFAULT 0,
  `CollectionsDate` datetime(6) NULL,
  `CollectionsReference` varchar(100) NULL,
  `AccountId` int NOT NULL,
  `OrderId` int NULL,
  `SubscriptionId` int NULL,
  `ContactId` int NULL,
  `VoidedById` int NULL,
  `OriginalInvoiceId` int NULL,
  `Notes` varchar(2000) NULL,
  `InternalNotes` varchar(2000) NULL,
  `Footer` varchar(1000) NULL,
  `TermsAndConditions` text NULL,
  `VoidReason` varchar(500) NULL,
  `DisputeReason` varchar(500) NULL,
  `PdfUrl` varchar(500) NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Invoices_Accounts_AccountId` FOREIGN KEY (`AccountId`) REFERENCES `Accounts` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. InvoiceLineItems
CREATE TABLE IF NOT EXISTS `InvoiceLineItems` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `LineNumber` int NOT NULL DEFAULT 0,
  `ExternalLineId` varchar(100) NULL,
  `Name` varchar(255) NOT NULL,
  `Description` varchar(1000) NULL,
  `SKU` varchar(50) NULL,
  `ProductCode` varchar(50) NULL,
  `Quantity` decimal(65,30) NOT NULL DEFAULT 0,
  `UnitOfMeasure` varchar(50) NULL,
  `UnitPrice` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(65,30) NOT NULL DEFAULT 0,
  `ExtendedAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `TaxAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `TaxRate` decimal(65,30) NULL,
  `TotalAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `ServiceStartDate` datetime(6) NULL,
  `ServiceEndDate` datetime(6) NULL,
  `RevenueRecognitionStartDate` datetime(6) NULL,
  `RevenueRecognitionEndDate` datetime(6) NULL,
  `DeferredRevenue` decimal(65,30) NULL,
  `RecognizedRevenue` decimal(65,30) NULL,
  `InvoiceId` int NOT NULL,
  `ProductId` int NULL,
  `OrderLineItemId` int NULL,
  `SubscriptionId` int NULL,
  `Notes` varchar(1000) NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_InvoiceLineItems_Invoices_InvoiceId` FOREIGN KEY (`InvoiceId`) REFERENCES `Invoices` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Contracts
CREATE TABLE IF NOT EXISTS `Contracts` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ContractNumber` text NOT NULL,
  `Name` text NOT NULL,
  `Description` text NULL,
  `Status` int NOT NULL DEFAULT 0,
  `ContractType` int NOT NULL DEFAULT 0,
  `AccountId` int NOT NULL,
  `ContactId` int NULL,
  `OwnerId` int NULL,
  `ParentContractId` int NULL,
  `OpportunityId` int NULL,
  `QuoteId` int NULL,
  `StartDate` datetime(6) NOT NULL,
  `EndDate` datetime(6) NOT NULL,
  `SignedDate` datetime(6) NULL,
  `ActivatedDate` datetime(6) NULL,
  `TerminatedDate` datetime(6) NULL,
  `Value` decimal(65,30) NOT NULL DEFAULT 0,
  `CurrencyCode` text NULL,
  `BillingFrequency` text NULL,
  `AutoRenew` tinyint(1) NOT NULL DEFAULT 0,
  `RenewalNoticeDays` int NOT NULL DEFAULT 30,
  `RenewalNoticeSent` tinyint(1) NOT NULL DEFAULT 0,
  `RenewalNoticeSentDate` datetime(6) NULL,
  `RenewalInitiatedAt` datetime(6) NULL,
  `RenewalCompletedAt` datetime(6) NULL,
  `Terms` text NULL,
  `SpecialConditions` text NULL,
  `TerminationClause` text NULL,
  `ContractFileUrl` text NULL,
  `ContractFileName` text NULL,
  `ContractFileSize` bigint NULL,
  `ContractFileMimeType` text NULL,
  `SignedContractFileUrl` text NULL,
  `SignedContractFileName` text NULL,
  `ApprovedByUserId` int NULL,
  `ApprovedDate` datetime(6) NULL,
  `RejectionReason` text NULL,
  `SuspensionReason` text NULL,
  `SuspendedDate` datetime(6) NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Contracts_Accounts_AccountId` FOREIGN KEY (`AccountId`) REFERENCES `Accounts` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Payments
CREATE TABLE IF NOT EXISTS `Payments` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `PaymentNumber` text NOT NULL,
  `ExternalPaymentId` text NULL,
  `GatewayTransactionId` text NULL,
  `GatewayReference` text NULL,
  `AuthorizationCode` text NULL,
  `CheckNumber` text NULL,
  `Description` text NULL,
  `Status` int NOT NULL DEFAULT 0,
  `PaymentMethod` int NOT NULL DEFAULT 0,
  `PaymentType` int NOT NULL DEFAULT 0,
  `Amount` decimal(65,30) NOT NULL DEFAULT 0,
  `AmountApplied` decimal(65,30) NOT NULL DEFAULT 0,
  `ProcessingFee` decimal(65,30) NOT NULL DEFAULT 0,
  `RefundedAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `CurrencyCode` text NOT NULL,
  `ExchangeRate` decimal(65,30) NULL,
  `PaymentDate` datetime(6) NOT NULL,
  `ProcessedDate` datetime(6) NULL,
  `SettledDate` datetime(6) NULL,
  `RefundDate` datetime(6) NULL,
  `DepositDate` datetime(6) NULL,
  `CardBrand` text NULL,
  `CardLast4` text NULL,
  `CardExpMonth` int NULL,
  `CardExpYear` int NULL,
  `CardholderName` text NULL,
  `BankName` text NULL,
  `AccountLast4` text NULL,
  `AccountType` text NULL,
  `RoutingNumberLast4` text NULL,
  `Gateway` text NULL,
  `GatewayResponseCode` text NULL,
  `GatewayResponseMessage` text NULL,
  `AvsResponseCode` text NULL,
  `CvvResponseCode` text NULL,
  `RiskScore` decimal(65,30) NULL,
  `GatewayResponseRaw` text NULL,
  `FraudFlagged` tinyint(1) NOT NULL DEFAULT 0,
  `FraudNotes` text NULL,
  `IpAddress` text NULL,
  `DeviceFingerprint` text NULL,
  `AccountId` int NOT NULL,
  `InvoiceId` int NULL,
  `OrderId` int NULL,
  `SubscriptionId` int NULL,
  `OriginalPaymentId` int NULL,
  `ProcessedById` int NULL,
  `ScheduledDate` datetime(6) NULL,
  `RetryCount` int NOT NULL DEFAULT 0,
  `BankReference` text NULL,
  `IsReconciled` tinyint(1) NOT NULL DEFAULT 0,
  `ReconciledDate` datetime(6) NULL,
  `Notes` text NULL,
  `InternalNotes` text NULL,
  `FailureReason` text NULL,
  `RefundReason` text NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Payments_Accounts_AccountId` FOREIGN KEY (`AccountId`) REFERENCES `Accounts` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Payments_Invoices_InvoiceId` FOREIGN KEY (`InvoiceId`) REFERENCES `Invoices` (`Id`),
  CONSTRAINT `FK_Payments_Orders_OrderId` FOREIGN KEY (`OrderId`) REFERENCES `Orders` (`Id`),
  CONSTRAINT `FK_Payments_Payments_OriginalPaymentId` FOREIGN KEY (`OriginalPaymentId`) REFERENCES `Payments` (`Id`),
  CONSTRAINT `FK_Payments_Subscriptions_SubscriptionId` FOREIGN KEY (`SubscriptionId`) REFERENCES `Subscriptions` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Commissions
CREATE TABLE IF NOT EXISTS `Commissions` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `CommissionNumber` text NOT NULL,
  `Status` int NOT NULL DEFAULT 0,
  `CommissionPeriod` text NOT NULL,
  `PeriodStartDate` datetime(6) NOT NULL,
  `PeriodEndDate` datetime(6) NOT NULL,
  `DealAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `CommissionableAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `CommissionRate` decimal(65,30) NOT NULL DEFAULT 0,
  `CommissionAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `SplitPercent` decimal(65,30) NOT NULL DEFAULT 0,
  `FinalCommissionAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `CurrencyCode` text NOT NULL,
  `QuotaAmount` decimal(65,30) NULL,
  `AttainmentPercent` decimal(65,30) NULL,
  `TierName` text NULL,
  `Multiplier` decimal(65,30) NULL,
  `EarnedDate` datetime(6) NOT NULL,
  `ApprovedDate` datetime(6) NULL,
  `PaidDate` datetime(6) NULL,
  `ClawbackEndDate` datetime(6) NULL,
  `ClawbackDate` datetime(6) NULL,
  `AdjustmentAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `AdjustmentReason` text NULL,
  `ClawbackAmount` decimal(65,30) NOT NULL DEFAULT 0,
  `ClawbackReason` text NULL,
  `UserId` int NOT NULL,
  `CommissionPlanId` int NOT NULL,
  `OpportunityId` int NULL,
  `OrderId` int NULL,
  `InvoiceId` int NULL,
  `SubscriptionId` int NULL,
  `OriginalCommissionId` int NULL,
  `ApprovedById` int NULL,
  `Notes` text NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Commissions_CommissionPlans_CommissionPlanId` FOREIGN KEY (`CommissionPlanId`) REFERENCES `CommissionPlans` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Commissions_Users_UserId` FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;