-- =============================================
-- CRM Database Creation Script - MySQL/MariaDB
-- Version: 1.0.0
-- Generated: 2024
-- =============================================

-- Create the database
CREATE DATABASE IF NOT EXISTS crm_database 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

USE crm_database;

-- =============================================
-- Core Tables
-- =============================================

-- Departments Table
CREATE TABLE IF NOT EXISTS Departments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NULL,
    DepartmentCode VARCHAR(20) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    ParentDepartmentId INT NULL,
    ManagerId INT NULL,
    Budget DECIMAL(18,2) NULL,
    CostCenter VARCHAR(50) NULL,
    Location VARCHAR(200) NULL,
    PhoneExtension VARCHAR(20) NULL,
    Email VARCHAR(255) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Departments_Parent FOREIGN KEY (ParentDepartmentId) REFERENCES Departments(Id)
) ENGINE=InnoDB;

-- UserProfiles Table
CREATE TABLE IF NOT EXISTS UserProfiles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Bio TEXT NULL,
    AvatarUrl VARCHAR(500) NULL,
    PhoneNumber VARCHAR(50) NULL,
    JobTitle VARCHAR(100) NULL,
    Department VARCHAR(100) NULL,
    Location VARCHAR(200) NULL,
    Timezone VARCHAR(100) NULL,
    Language VARCHAR(20) NULL,
    DateFormat VARCHAR(50) NULL,
    Theme VARCHAR(50) NULL,
    NotificationPreferences TEXT NULL,
    SocialLinks TEXT NULL,
    Skills TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Users Table
CREATE TABLE IF NOT EXISTS Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(500) NOT NULL,
    FirstName VARCHAR(100) NULL,
    LastName VARCHAR(100) NULL,
    MiddleName VARCHAR(100) NULL,
    Role INT NOT NULL DEFAULT 0,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    EmailVerified BOOLEAN NOT NULL DEFAULT FALSE,
    EmailVerificationToken VARCHAR(500) NULL,
    PasswordResetToken VARCHAR(500) NULL,
    PasswordResetExpires DATETIME NULL,
    TwoFactorEnabled BOOLEAN NOT NULL DEFAULT FALSE,
    TwoFactorSecret VARCHAR(500) NULL,
    LastLoginAt DATETIME NULL,
    LastLoginIp VARCHAR(50) NULL,
    LoginAttempts INT NOT NULL DEFAULT 0,
    LockoutEnd DATETIME NULL,
    DepartmentId INT NULL,
    ManagerId INT NULL,
    ProfileId INT NULL,
    RefreshToken VARCHAR(500) NULL,
    RefreshTokenExpiry DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Users_Username UNIQUE (Username),
    CONSTRAINT UQ_Users_Email UNIQUE (Email),
    CONSTRAINT FK_Users_Department FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
    CONSTRAINT FK_Users_Manager FOREIGN KEY (ManagerId) REFERENCES Users(Id),
    CONSTRAINT FK_Users_Profile FOREIGN KEY (ProfileId) REFERENCES UserProfiles(Id)
) ENGINE=InnoDB;

-- UserGroups Table
CREATE TABLE IF NOT EXISTS UserGroups (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NULL,
    GroupType INT NOT NULL DEFAULT 0,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    ParentGroupId INT NULL,
    Permissions TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_UserGroups_Name UNIQUE (Name),
    CONSTRAINT FK_UserGroups_Parent FOREIGN KEY (ParentGroupId) REFERENCES UserGroups(Id)
) ENGINE=InnoDB;

-- UserGroupMembers Table
CREATE TABLE IF NOT EXISTS UserGroupMembers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    GroupId INT NOT NULL,
    Role VARCHAR(50) NULL,
    JoinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AddedByUserId INT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT FK_UserGroupMembers_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserGroupMembers_Group FOREIGN KEY (GroupId) REFERENCES UserGroups(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserGroupMembers_AddedBy FOREIGN KEY (AddedByUserId) REFERENCES Users(Id)
) ENGINE=InnoDB;

-- UserApprovalRequests Table
CREATE TABLE IF NOT EXISTS UserApprovalRequests (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Email VARCHAR(255) NOT NULL,
    FirstName VARCHAR(100) NULL,
    LastName VARCHAR(100) NULL,
    RequestedRole INT NOT NULL,
    RequestedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Status INT NOT NULL DEFAULT 0,
    ReviewedByUserId INT NULL,
    ReviewedAt DATETIME NULL,
    ReviewNotes VARCHAR(500) NULL,
    RejectionReason VARCHAR(500) NULL,
    CONSTRAINT FK_UserApprovalRequests_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserApprovalRequests_ReviewedBy FOREIGN KEY (ReviewedByUserId) REFERENCES Users(Id)
) ENGINE=InnoDB;

-- OAuthTokens Table
CREATE TABLE IF NOT EXISTS OAuthTokens (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Provider VARCHAR(50) NOT NULL,
    AccessToken TEXT NOT NULL,
    RefreshToken TEXT NULL,
    TokenType VARCHAR(50) NULL,
    ExpiresAt DATETIME NULL,
    Scope VARCHAR(500) NULL,
    ProviderUserId VARCHAR(255) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_OAuthTokens_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- DatabaseBackups Table
CREATE TABLE IF NOT EXISTS DatabaseBackups (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FileName VARCHAR(500) NOT NULL,
    FilePath VARCHAR(1000) NOT NULL,
    FileSize BIGINT NOT NULL,
    BackupType VARCHAR(50) NOT NULL,
    Status VARCHAR(50) NOT NULL,
    StartedAt DATETIME NOT NULL,
    CompletedAt DATETIME NULL,
    ErrorMessage TEXT NULL,
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    RetentionDays INT NOT NULL DEFAULT 30,
    IsEncrypted BOOLEAN NOT NULL DEFAULT FALSE,
    ChecksumMD5 VARCHAR(100) NULL,
    CONSTRAINT FK_DatabaseBackups_User FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id)
) ENGINE=InnoDB;

-- =============================================
-- CRM Tables
-- =============================================

-- Customers Table
CREATE TABLE IF NOT EXISTS Customers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(100) NULL,
    Prefix VARCHAR(20) NULL,
    Suffix VARCHAR(20) NULL,
    FullName VARCHAR(300) NULL,
    Email VARCHAR(255) NOT NULL,
    SecondaryEmail VARCHAR(255) NULL,
    Phone VARCHAR(50) NULL,
    MobilePhone VARCHAR(50) NULL,
    WorkPhone VARCHAR(50) NULL,
    Fax VARCHAR(50) NULL,
    Company VARCHAR(200) NULL,
    LegalName VARCHAR(200) NULL,
    DBA VARCHAR(200) NULL,
    TaxId VARCHAR(50) NULL,
    DunsNumber VARCHAR(20) NULL,
    Industry VARCHAR(100) NULL,
    SubIndustry VARCHAR(100) NULL,
    SICCode VARCHAR(20) NULL,
    NAICSCode VARCHAR(20) NULL,
    NumberOfEmployees INT NULL,
    AnnualRevenue DECIMAL(18,2) NULL,
    OwnershipType VARCHAR(50) NULL,
    YearFounded INT NULL,
    FiscalYearEnd VARCHAR(20) NULL,
    JobTitle VARCHAR(100) NULL,
    Department VARCHAR(100) NULL,
    ReportsTo VARCHAR(100) NULL,
    Website VARCHAR(500) NULL,
    LinkedIn VARCHAR(500) NULL,
    Twitter VARCHAR(500) NULL,
    Facebook VARCHAR(500) NULL,
    Address VARCHAR(500) NULL,
    AddressLine2 VARCHAR(500) NULL,
    City VARCHAR(100) NULL,
    State VARCHAR(100) NULL,
    ZipCode VARCHAR(20) NULL,
    Country VARCHAR(100) NULL,
    ShippingAddress VARCHAR(500) NULL,
    ShippingAddressLine2 VARCHAR(500) NULL,
    ShippingCity VARCHAR(100) NULL,
    ShippingState VARCHAR(100) NULL,
    ShippingZipCode VARCHAR(20) NULL,
    ShippingCountry VARCHAR(100) NULL,
    CustomerType INT NOT NULL DEFAULT 0,
    Priority INT NOT NULL DEFAULT 0,
    LifecycleStage INT NOT NULL DEFAULT 0,
    LeadSource VARCHAR(100) NULL,
    FirstContactDate DATETIME NULL,
    LastContactDate DATETIME NULL,
    LeadScore INT NULL,
    CustomerHealthScore INT NULL,
    PreferredContactMethod INT NOT NULL DEFAULT 0,
    PreferredLanguage VARCHAR(20) NULL,
    Timezone VARCHAR(100) NULL,
    CurrencyCode VARCHAR(10) NULL,
    PaymentTerms VARCHAR(100) NULL,
    CreditLimit DECIMAL(18,2) NULL,
    AccountBalance DECIMAL(18,2) NULL,
    LifetimeValue DECIMAL(18,2) NULL,
    TotalPurchases INT NULL,
    AverageOrderValue DECIMAL(18,2) NULL,
    LastPurchaseDate DATETIME NULL,
    ReferralSource VARCHAR(200) NULL,
    ReferredBy VARCHAR(200) NULL,
    AssignedToUserId INT NULL,
    ParentAccountId INT NULL,
    DoNotCall BOOLEAN NOT NULL DEFAULT FALSE,
    DoNotEmail BOOLEAN NOT NULL DEFAULT FALSE,
    DoNotMail BOOLEAN NOT NULL DEFAULT FALSE,
    OptInEmail BOOLEAN NOT NULL DEFAULT TRUE,
    OptInPhone BOOLEAN NOT NULL DEFAULT TRUE,
    OptInSMS BOOLEAN NOT NULL DEFAULT FALSE,
    GDPRConsent BOOLEAN NOT NULL DEFAULT FALSE,
    GDPRConsentDate DATETIME NULL,
    Tags TEXT NULL,
    Notes TEXT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Customers_Email UNIQUE (Email),
    CONSTRAINT FK_Customers_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Customers_ParentAccount FOREIGN KEY (ParentAccountId) REFERENCES Customers(Id)
) ENGINE=InnoDB;

-- Products Table
CREATE TABLE IF NOT EXISTS Products (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Description TEXT NULL,
    ShortDescription VARCHAR(500) NULL,
    SKU VARCHAR(100) NULL,
    Barcode VARCHAR(100) NULL,
    GTIN VARCHAR(50) NULL,
    MPN VARCHAR(100) NULL,
    ProductType INT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    Category VARCHAR(100) NULL,
    SubCategory VARCHAR(100) NULL,
    Brand VARCHAR(100) NULL,
    Manufacturer VARCHAR(200) NULL,
    Vendor VARCHAR(200) NULL,
    VendorPartNumber VARCHAR(100) NULL,
    Price DECIMAL(18,2) NOT NULL,
    ListPrice DECIMAL(18,2) NULL,
    Cost DECIMAL(18,2) NULL,
    CompareAtPrice DECIMAL(18,2) NULL,
    Margin DECIMAL(18,2) NULL,
    MarkupPercent DECIMAL(18,4) NULL,
    MinPrice DECIMAL(18,2) NULL,
    MaxDiscount DECIMAL(18,4) NULL,
    IsTaxable BOOLEAN NOT NULL DEFAULT TRUE,
    TaxRate DECIMAL(18,4) NULL,
    TaxCode VARCHAR(50) NULL,
    Quantity INT NOT NULL DEFAULT 0,
    ReservedQuantity INT NOT NULL DEFAULT 0,
    AvailableQuantity INT NOT NULL DEFAULT 0,
    MinQuantity INT NULL,
    MaxQuantity INT NULL,
    ReorderLevel INT NULL,
    ReorderQuantity INT NULL,
    LeadTimeDays INT NULL,
    WarehouseLocation VARCHAR(100) NULL,
    BinNumber VARCHAR(50) NULL,
    TrackInventory BOOLEAN NOT NULL DEFAULT TRUE,
    AllowBackorder BOOLEAN NOT NULL DEFAULT FALSE,
    Weight DECIMAL(18,4) NULL,
    WeightUnit VARCHAR(20) NULL,
    Length DECIMAL(18,4) NULL,
    Width DECIMAL(18,4) NULL,
    Height DECIMAL(18,4) NULL,
    DimensionUnit VARCHAR(20) NULL,
    ShippingClass VARCHAR(50) NULL,
    RequiresShipping BOOLEAN NOT NULL DEFAULT TRUE,
    ImageUrl VARCHAR(1000) NULL,
    ThumbnailUrl VARCHAR(1000) NULL,
    MediaGallery TEXT NULL,
    VideoUrl VARCHAR(1000) NULL,
    DocumentUrl VARCHAR(1000) NULL,
    MetaTitle VARCHAR(200) NULL,
    MetaDescription VARCHAR(500) NULL,
    MetaKeywords VARCHAR(500) NULL,
    Slug VARCHAR(300) NULL,
    TotalSold INT NOT NULL DEFAULT 0,
    TotalRevenue DECIMAL(18,2) NOT NULL DEFAULT 0,
    ViewCount INT NOT NULL DEFAULT 0,
    AverageRating DOUBLE NULL,
    ReviewCount INT NOT NULL DEFAULT 0,
    IsFeatured BOOLEAN NOT NULL DEFAULT FALSE,
    IsNew BOOLEAN NOT NULL DEFAULT FALSE,
    IsBestSeller BOOLEAN NOT NULL DEFAULT FALSE,
    IsOnSale BOOLEAN NOT NULL DEFAULT FALSE,
    SaleStartDate DATETIME NULL,
    SaleEndDate DATETIME NULL,
    WarrantyPeriod VARCHAR(50) NULL,
    ReturnPolicy VARCHAR(500) NULL,
    SupportUrl VARCHAR(500) NULL,
    CustomField1 VARCHAR(500) NULL,
    CustomField2 VARCHAR(500) NULL,
    CustomField3 VARCHAR(500) NULL,
    CustomField4 VARCHAR(500) NULL,
    CustomField5 VARCHAR(500) NULL,
    Tags TEXT NULL,
    Notes TEXT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX IX_Products_SKU (SKU),
    INDEX IX_Products_Category (Category),
    INDEX IX_Products_Status (Status)
) ENGINE=InnoDB;

-- MarketingCampaigns Table
CREATE TABLE IF NOT EXISTS MarketingCampaigns (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Description TEXT NULL,
    Objective VARCHAR(500) NULL,
    CampaignType INT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    Priority INT NOT NULL DEFAULT 0,
    StartDate DATETIME NULL,
    EndDate DATETIME NULL,
    ActualStartDate DATETIME NULL,
    ActualEndDate DATETIME NULL,
    Budget DECIMAL(18,2) NULL,
    ActualCost DECIMAL(18,2) NULL,
    ExpectedRevenue DECIMAL(18,2) NULL,
    ActualRevenue DECIMAL(18,2) NULL,
    ROI DOUBLE NULL,
    ROAS DOUBLE NULL,
    TargetAudience INT NULL,
    ReachActual INT NULL,
    Impressions INT NULL,
    Clicks INT NULL,
    CTR DOUBLE NULL,
    Conversions INT NULL,
    ConversionRate DOUBLE NULL,
    CostPerClick DECIMAL(18,2) NULL,
    CostPerConversion DECIMAL(18,2) NULL,
    CostPerLead DECIMAL(18,2) NULL,
    CostPerAcquisition DECIMAL(18,2) NULL,
    LeadsGenerated INT NULL,
    OpportunitiesCreated INT NULL,
    CustomersAcquired INT NULL,
    EmailsSent INT NULL,
    EmailsDelivered INT NULL,
    EmailsOpened INT NULL,
    EmailOpenRate DOUBLE NULL,
    EmailsClicked INT NULL,
    EmailClickRate DOUBLE NULL,
    EmailsBounced INT NULL,
    EmailBounceRate DOUBLE NULL,
    Unsubscribes INT NULL,
    UnsubscribeRate DOUBLE NULL,
    SocialShares INT NULL,
    SocialLikes INT NULL,
    SocialComments INT NULL,
    SocialReach INT NULL,
    WebsiteVisits INT NULL,
    PageViews INT NULL,
    BounceRate DOUBLE NULL,
    AvgSessionDuration DOUBLE NULL,
    OwnerId INT NULL,
    CreatedByUserId INT NULL,
    Channel VARCHAR(100) NULL,
    SubChannel VARCHAR(100) NULL,
    TargetRegion VARCHAR(200) NULL,
    TargetIndustry VARCHAR(200) NULL,
    TargetJobTitles VARCHAR(500) NULL,
    TargetCompanySize VARCHAR(200) NULL,
    ABTestVariant VARCHAR(50) NULL,
    ControlGroup BOOLEAN NOT NULL DEFAULT FALSE,
    ParentCampaignId INT NULL,
    LandingPageUrl VARCHAR(1000) NULL,
    TrackingCode VARCHAR(200) NULL,
    UTMSource VARCHAR(100) NULL,
    UTMCampaign VARCHAR(100) NULL,
    UTMContent VARCHAR(100) NULL,
    Tags TEXT NULL,
    Notes TEXT NULL,
    IsArchived BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MarketingCampaigns_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id),
    CONSTRAINT FK_MarketingCampaigns_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_MarketingCampaigns_Parent FOREIGN KEY (ParentCampaignId) REFERENCES MarketingCampaigns(Id),
    INDEX IX_MarketingCampaigns_Status (Status),
    INDEX IX_MarketingCampaigns_Type (CampaignType)
) ENGINE=InnoDB;

-- CampaignMetrics Table
CREATE TABLE IF NOT EXISTS CampaignMetrics (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CampaignId INT NOT NULL,
    MetricDate DATE NOT NULL,
    Impressions INT NOT NULL DEFAULT 0,
    Clicks INT NOT NULL DEFAULT 0,
    Conversions INT NOT NULL DEFAULT 0,
    Cost DECIMAL(18,2) NOT NULL DEFAULT 0,
    Revenue DECIMAL(18,2) NOT NULL DEFAULT 0,
    Leads INT NOT NULL DEFAULT 0,
    EmailsSent INT NOT NULL DEFAULT 0,
    EmailsOpened INT NOT NULL DEFAULT 0,
    EmailsClicked INT NOT NULL DEFAULT 0,
    Unsubscribes INT NOT NULL DEFAULT 0,
    Channel VARCHAR(100) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CampaignMetrics_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id) ON DELETE CASCADE,
    INDEX IX_CampaignMetrics_Date (MetricDate)
) ENGINE=InnoDB;

-- Opportunities Table
CREATE TABLE IF NOT EXISTS Opportunities (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(300) NOT NULL,
    Description TEXT NULL,
    OpportunityType INT NOT NULL DEFAULT 0,
    Priority INT NOT NULL DEFAULT 0,
    Amount DECIMAL(18,2) NULL,
    ExpectedRevenue DECIMAL(18,2) NULL,
    ActualRevenue DECIMAL(18,2) NULL,
    GrossProfit DECIMAL(18,2) NULL,
    Commission DECIMAL(18,2) NULL,
    CurrencyCode VARCHAR(10) NULL,
    Stage INT NOT NULL DEFAULT 0,
    StageChangedAt DATETIME NULL,
    DaysInStage INT NOT NULL DEFAULT 0,
    Probability DOUBLE NOT NULL DEFAULT 0,
    ForecastCategory INT NOT NULL DEFAULT 0,
    CloseDate DATETIME NULL,
    ExpectedCloseDate DATETIME NULL,
    ActualCloseDate DATETIME NULL,
    NextStep VARCHAR(500) NULL,
    NextStepDate DATETIME NULL,
    LeadSource VARCHAR(200) NULL,
    CustomerId INT NULL,
    ProductId INT NULL,
    PrimaryContactId INT NULL,
    AssignedToUserId INT NULL,
    TeamId INT NULL,
    CampaignId INT NULL,
    QuoteId INT NULL,
    CompetitorName VARCHAR(200) NULL,
    CompetitorStrengths VARCHAR(500) NULL,
    CompetitorWeaknesses VARCHAR(500) NULL,
    WinLossReason VARCHAR(500) NULL,
    LostToCompetitor VARCHAR(200) NULL,
    DecisionMakers VARCHAR(500) NULL,
    BudgetStatus VARCHAR(100) NULL,
    Authority VARCHAR(100) NULL,
    Need VARCHAR(100) NULL,
    Timeline VARCHAR(100) NULL,
    BANTScore INT NULL,
    RiskLevel INT NOT NULL DEFAULT 0,
    RiskNotes VARCHAR(500) NULL,
    LastActivityDate DATETIME NULL,
    LastActivityType VARCHAR(100) NULL,
    TotalActivities INT NOT NULL DEFAULT 0,
    Tags TEXT NULL,
    Notes TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Opportunities_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Opportunities_Product FOREIGN KEY (ProductId) REFERENCES Products(Id),
    CONSTRAINT FK_Opportunities_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Opportunities_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id),
    INDEX IX_Opportunities_Stage (Stage),
    INDEX IX_Opportunities_CloseDate (CloseDate),
    INDEX IX_Opportunities_CustomerId (CustomerId)
) ENGINE=InnoDB;

-- Contacts Table
CREATE TABLE IF NOT EXISTS Contacts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ContactType INT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(100) NULL,
    Prefix VARCHAR(20) NULL,
    Suffix VARCHAR(20) NULL,
    FullName VARCHAR(300) NULL,
    Nickname VARCHAR(100) NULL,
    EmailPrimary VARCHAR(255) NULL,
    EmailSecondary VARCHAR(255) NULL,
    EmailWork VARCHAR(255) NULL,
    PhonePrimary VARCHAR(50) NULL,
    PhoneMobile VARCHAR(50) NULL,
    PhoneWork VARCHAR(50) NULL,
    PhoneHome VARCHAR(50) NULL,
    Fax VARCHAR(50) NULL,
    JobTitle VARCHAR(150) NULL,
    Department VARCHAR(100) NULL,
    Company VARCHAR(200) NULL,
    ReportsTo VARCHAR(100) NULL,
    AssistantName VARCHAR(100) NULL,
    AssistantPhone VARCHAR(50) NULL,
    Address VARCHAR(500) NULL,
    AddressLine2 VARCHAR(500) NULL,
    City VARCHAR(100) NULL,
    State VARCHAR(100) NULL,
    ZipCode VARCHAR(20) NULL,
    Country VARCHAR(100) NULL,
    Region VARCHAR(100) NULL,
    Timezone VARCHAR(100) NULL,
    PreferredLanguage VARCHAR(20) NULL,
    PreferredContactMethod INT NOT NULL DEFAULT 0,
    LeadScore INT NULL,
    LeadSource VARCHAR(100) NULL,
    LeadStatus INT NULL,
    ConversionDate DATETIME NULL,
    IsKeyContact BOOLEAN NOT NULL DEFAULT FALSE,
    IsDecisionMaker BOOLEAN NOT NULL DEFAULT FALSE,
    Influence VARCHAR(50) NULL,
    BudgetAuthority BOOLEAN NOT NULL DEFAULT FALSE,
    DoNotCall BOOLEAN NOT NULL DEFAULT FALSE,
    DoNotEmail BOOLEAN NOT NULL DEFAULT FALSE,
    HasOptedOut BOOLEAN NOT NULL DEFAULT FALSE,
    OptOutDate DATETIME NULL,
    BirthDate DATE NULL,
    Anniversary DATE NULL,
    CustomerId INT NULL,
    AccountId INT NULL,
    OwnerId INT NULL,
    LastContactedDate DATETIME NULL,
    TotalInteractions INT NOT NULL DEFAULT 0,
    Tags TEXT NULL,
    Notes TEXT NULL,
    DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateModified DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Contacts_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Contacts_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id),
    INDEX IX_Contacts_Email (EmailPrimary),
    INDEX IX_Contacts_Company (Company)
) ENGINE=InnoDB;

-- SocialMediaLinks Table
CREATE TABLE IF NOT EXISTS SocialMediaLinks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ContactId INT NOT NULL,
    Platform VARCHAR(50) NOT NULL,
    ProfileUrl VARCHAR(500) NOT NULL,
    Username VARCHAR(100) NULL,
    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    FollowerCount INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SocialMediaLinks_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Interactions Table
CREATE TABLE IF NOT EXISTS Interactions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    InteractionType INT NOT NULL DEFAULT 0,
    Type VARCHAR(50) NOT NULL,
    Direction INT NOT NULL DEFAULT 0,
    Subject VARCHAR(300) NULL,
    Description TEXT NULL,
    InteractionDate DATETIME NOT NULL,
    StartTime DATETIME NULL,
    EndTime DATETIME NULL,
    DurationMinutes INT NULL,
    Outcome INT NOT NULL DEFAULT 0,
    OutcomeNotes VARCHAR(500) NULL,
    Sentiment INT NOT NULL DEFAULT 0,
    SentimentScore DOUBLE NULL,
    IsCompleted BOOLEAN NOT NULL DEFAULT FALSE,
    CompletedAt DATETIME NULL,
    CustomerId INT NULL,
    ContactId INT NULL,
    OpportunityId INT NULL,
    CampaignId INT NULL,
    CaseId INT NULL,
    AssignedToUserId INT NULL,
    CreatedByUserId INT NULL,
    FollowUpRequired BOOLEAN NOT NULL DEFAULT FALSE,
    FollowUpDate DATETIME NULL,
    FollowUpNotes VARCHAR(500) NULL,
    FollowUpCompleted BOOLEAN NOT NULL DEFAULT FALSE,
    Location VARCHAR(200) NULL,
    MeetingUrl VARCHAR(500) NULL,
    MeetingId VARCHAR(100) NULL,
    Attendees TEXT NULL,
    AttachmentCount INT NOT NULL DEFAULT 0,
    AttachmentUrls TEXT NULL,
    EmailMessageId VARCHAR(200) NULL,
    CallRecordingUrl VARCHAR(500) NULL,
    CallDisposition VARCHAR(100) NULL,
    Priority INT NOT NULL DEFAULT 0,
    Tags TEXT NULL,
    Notes TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Interactions_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Interactions_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id),
    CONSTRAINT FK_Interactions_Opportunity FOREIGN KEY (OpportunityId) REFERENCES Opportunities(Id),
    CONSTRAINT FK_Interactions_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id),
    CONSTRAINT FK_Interactions_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Interactions_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    INDEX IX_Interactions_Date (InteractionDate),
    INDEX IX_Interactions_CustomerId (CustomerId)
) ENGINE=InnoDB;

-- CrmTasks Table
CREATE TABLE IF NOT EXISTS CrmTasks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Subject VARCHAR(300) NOT NULL,
    Description TEXT NULL,
    TaskType INT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    Priority INT NOT NULL DEFAULT 0,
    DueDate DATETIME NULL,
    StartDate DATETIME NULL,
    CompletedDate DATETIME NULL,
    ReminderDate DATETIME NULL,
    ReminderSent BOOLEAN NOT NULL DEFAULT FALSE,
    PercentComplete INT NOT NULL DEFAULT 0,
    EstimatedMinutes INT NULL,
    ActualMinutes INT NULL,
    RecurrencePattern VARCHAR(100) NULL,
    RecurrenceEndDate DATETIME NULL,
    ParentTaskId INT NULL,
    IsAllDay BOOLEAN NOT NULL DEFAULT FALSE,
    IsBillable BOOLEAN NOT NULL DEFAULT FALSE,
    BillingRate DECIMAL(18,2) NULL,
    CustomerId INT NULL,
    ContactId INT NULL,
    OpportunityId INT NULL,
    CampaignId INT NULL,
    AssignedToUserId INT NULL,
    CreatedByUserId INT NULL,
    CompletedByUserId INT NULL,
    Tags TEXT NULL,
    Notes TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CrmTasks_Parent FOREIGN KEY (ParentTaskId) REFERENCES CrmTasks(Id),
    CONSTRAINT FK_CrmTasks_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_CrmTasks_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id),
    CONSTRAINT FK_CrmTasks_Opportunity FOREIGN KEY (OpportunityId) REFERENCES Opportunities(Id),
    CONSTRAINT FK_CrmTasks_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id),
    CONSTRAINT FK_CrmTasks_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id),
    CONSTRAINT FK_CrmTasks_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_CrmTasks_CompletedBy FOREIGN KEY (CompletedByUserId) REFERENCES Users(Id),
    INDEX IX_CrmTasks_DueDate (DueDate),
    INDEX IX_CrmTasks_Status (Status)
) ENGINE=InnoDB;

-- Notes Table
CREATE TABLE IF NOT EXISTS Notes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(300) NULL,
    Content TEXT NULL,
    Summary VARCHAR(500) NULL,
    NoteType INT NOT NULL DEFAULT 0,
    Visibility INT NOT NULL DEFAULT 0,
    IsPinned BOOLEAN NOT NULL DEFAULT FALSE,
    IsImportant BOOLEAN NOT NULL DEFAULT FALSE,
    IsArchived BOOLEAN NOT NULL DEFAULT FALSE,
    ParentNoteId INT NULL,
    CustomerId INT NULL,
    ContactId INT NULL,
    OpportunityId INT NULL,
    CampaignId INT NULL,
    TaskId INT NULL,
    InteractionId INT NULL,
    QuoteId INT NULL,
    CreatedByUserId INT NULL,
    LastModifiedByUserId INT NULL,
    AttachmentCount INT NOT NULL DEFAULT 0,
    AttachmentUrls TEXT NULL,
    Tags TEXT NULL,
    Metadata TEXT NULL,
    ViewCount INT NOT NULL DEFAULT 0,
    LastViewedAt DATETIME NULL,
    LastViewedByUserId INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Notes_Parent FOREIGN KEY (ParentNoteId) REFERENCES Notes(Id),
    CONSTRAINT FK_Notes_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Notes_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id),
    CONSTRAINT FK_Notes_Opportunity FOREIGN KEY (OpportunityId) REFERENCES Opportunities(Id),
    CONSTRAINT FK_Notes_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id),
    CONSTRAINT FK_Notes_Task FOREIGN KEY (TaskId) REFERENCES CrmTasks(Id),
    CONSTRAINT FK_Notes_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    INDEX IX_Notes_CustomerId (CustomerId),
    INDEX IX_Notes_CreatedAt (CreatedAt)
) ENGINE=InnoDB;

-- Quotes Table
CREATE TABLE IF NOT EXISTS Quotes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    QuoteNumber VARCHAR(50) NOT NULL,
    Name VARCHAR(300) NULL,
    Description TEXT NULL,
    Status INT NOT NULL DEFAULT 0,
    QuoteDate DATETIME NOT NULL,
    ExpirationDate DATETIME NULL,
    AcceptedDate DATETIME NULL,
    RejectedDate DATETIME NULL,
    Subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    Discount DECIMAL(18,2) NOT NULL DEFAULT 0,
    DiscountPercent DECIMAL(18,4) NULL,
    DiscountReason VARCHAR(200) NULL,
    Tax DECIMAL(18,2) NOT NULL DEFAULT 0,
    TaxRate DECIMAL(18,4) NULL,
    Shipping DECIMAL(18,2) NOT NULL DEFAULT 0,
    Total DECIMAL(18,2) NOT NULL DEFAULT 0,
    CurrencyCode VARCHAR(10) NULL,
    PaymentTerms VARCHAR(200) NULL,
    DeliveryTerms VARCHAR(200) NULL,
    ValidityDays INT NULL,
    TermsAndConditions TEXT NULL,
    BillingName VARCHAR(200) NULL,
    BillingAddress VARCHAR(500) NULL,
    BillingCity VARCHAR(100) NULL,
    BillingState VARCHAR(100) NULL,
    BillingZipCode VARCHAR(20) NULL,
    BillingCountry VARCHAR(100) NULL,
    ShippingName VARCHAR(200) NULL,
    ShippingAddress VARCHAR(500) NULL,
    ShippingCity VARCHAR(100) NULL,
    ShippingState VARCHAR(100) NULL,
    ShippingZipCode VARCHAR(20) NULL,
    ShippingCountry VARCHAR(100) NULL,
    CustomerId INT NULL,
    ContactId INT NULL,
    OpportunityId INT NULL,
    AssignedToUserId INT NULL,
    CreatedByUserId INT NULL,
    ApprovedByUserId INT NULL,
    ApprovedAt DATETIME NULL,
    SentAt DATETIME NULL,
    SentToEmail VARCHAR(255) NULL,
    ViewedAt DATETIME NULL,
    VersionNumber INT NOT NULL DEFAULT 1,
    ParentQuoteId INT NULL,
    PdfUrl VARCHAR(500) NULL,
    Tags TEXT NULL,
    Notes TEXT NULL,
    InternalNotes TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Quotes_Number UNIQUE (QuoteNumber),
    CONSTRAINT FK_Quotes_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Quotes_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id),
    CONSTRAINT FK_Quotes_Opportunity FOREIGN KEY (OpportunityId) REFERENCES Opportunities(Id),
    CONSTRAINT FK_Quotes_AssignedTo FOREIGN KEY (AssignedToUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Quotes_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Quotes_ApprovedBy FOREIGN KEY (ApprovedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Quotes_Parent FOREIGN KEY (ParentQuoteId) REFERENCES Quotes(Id),
    INDEX IX_Quotes_QuoteNumber (QuoteNumber),
    INDEX IX_Quotes_Status (Status)
) ENGINE=InnoDB;

-- Activities Table
CREATE TABLE IF NOT EXISTS Activities (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ActivityType INT NOT NULL DEFAULT 0,
    Title VARCHAR(300) NOT NULL,
    Description TEXT NULL,
    ActivityDate DATETIME NOT NULL,
    StartTime DATETIME NULL,
    EndTime DATETIME NULL,
    DurationMinutes INT NULL,
    UserId INT NULL,
    UserName VARCHAR(200) NULL,
    UserEmail VARCHAR(255) NULL,
    EntityType VARCHAR(100) NULL,
    EntityId INT NULL,
    EntityName VARCHAR(300) NULL,
    CustomerId INT NULL,
    ContactId INT NULL,
    OpportunityId INT NULL,
    CampaignId INT NULL,
    TaskId INT NULL,
    InteractionId INT NULL,
    OldValue TEXT NULL,
    NewValue TEXT NULL,
    FieldChanged VARCHAR(100) NULL,
    IpAddress VARCHAR(50) NULL,
    UserAgent VARCHAR(500) NULL,
    SessionId VARCHAR(200) NULL,
    IsSystemGenerated BOOLEAN NOT NULL DEFAULT FALSE,
    IsVisible BOOLEAN NOT NULL DEFAULT TRUE,
    Importance INT NOT NULL DEFAULT 0,
    Tags TEXT NULL,
    Metadata TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Activities_User FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_Activities_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
    CONSTRAINT FK_Activities_Contact FOREIGN KEY (ContactId) REFERENCES Contacts(Id),
    CONSTRAINT FK_Activities_Opportunity FOREIGN KEY (OpportunityId) REFERENCES Opportunities(Id),
    CONSTRAINT FK_Activities_Campaign FOREIGN KEY (CampaignId) REFERENCES MarketingCampaigns(Id),
    CONSTRAINT FK_Activities_Task FOREIGN KEY (TaskId) REFERENCES CrmTasks(Id),
    INDEX IX_Activities_Date (ActivityDate),
    INDEX IX_Activities_UserId (UserId),
    INDEX IX_Activities_EntityType (EntityType, EntityId)
) ENGINE=InnoDB;

-- =============================================
-- Workflow Tables
-- =============================================

-- Workflows Table
CREATE TABLE IF NOT EXISTS Workflows (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Description TEXT NULL,
    WorkflowType VARCHAR(50) NOT NULL,
    TriggerType VARCHAR(50) NOT NULL,
    TriggerEntity VARCHAR(100) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Priority INT NOT NULL DEFAULT 0,
    Version INT NOT NULL DEFAULT 1,
    ExecutionOrder INT NOT NULL DEFAULT 0,
    MaxExecutions INT NULL,
    CurrentExecutions INT NOT NULL DEFAULT 0,
    StartDate DATETIME NULL,
    EndDate DATETIME NULL,
    LastExecutedAt DATETIME NULL,
    NextExecutionAt DATETIME NULL,
    CreatedByUserId INT NULL,
    ModifiedByUserId INT NULL,
    Configuration TEXT NULL,
    ErrorHandling VARCHAR(500) NULL,
    NotifyOnError BOOLEAN NOT NULL DEFAULT TRUE,
    NotifyEmail VARCHAR(255) NULL,
    Tags TEXT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Workflows_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_Workflows_ModifiedBy FOREIGN KEY (ModifiedByUserId) REFERENCES Users(Id),
    INDEX IX_Workflows_IsActive (IsActive),
    INDEX IX_Workflows_TriggerType (TriggerType)
) ENGINE=InnoDB;

-- WorkflowRules Table
CREATE TABLE IF NOT EXISTS WorkflowRules (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WorkflowId INT NOT NULL,
    Name VARCHAR(200) NOT NULL,
    Description VARCHAR(500) NULL,
    RuleOrder INT NOT NULL DEFAULT 0,
    ActionType VARCHAR(100) NOT NULL,
    ActionConfiguration TEXT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    StopOnSuccess BOOLEAN NOT NULL DEFAULT FALSE,
    StopOnFailure BOOLEAN NOT NULL DEFAULT FALSE,
    RetryCount INT NOT NULL DEFAULT 0,
    RetryInterval INT NOT NULL DEFAULT 60,
    TimeoutSeconds INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_WorkflowRules_Workflow FOREIGN KEY (WorkflowId) REFERENCES Workflows(Id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- WorkflowRuleConditions Table
CREATE TABLE IF NOT EXISTS WorkflowRuleConditions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WorkflowRuleId INT NOT NULL,
    ConditionOrder INT NOT NULL DEFAULT 0,
    FieldName VARCHAR(100) NOT NULL,
    Operator VARCHAR(50) NOT NULL,
    Value VARCHAR(500) NULL,
    ValueType VARCHAR(50) NULL,
    LogicalOperator VARCHAR(10) NOT NULL DEFAULT 'AND',
    ParentConditionId INT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_WorkflowRuleConditions_Rule FOREIGN KEY (WorkflowRuleId) REFERENCES WorkflowRules(Id) ON DELETE CASCADE,
    CONSTRAINT FK_WorkflowRuleConditions_Parent FOREIGN KEY (ParentConditionId) REFERENCES WorkflowRuleConditions(Id)
) ENGINE=InnoDB;

-- WorkflowExecutions Table
CREATE TABLE IF NOT EXISTS WorkflowExecutions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WorkflowId INT NOT NULL,
    WorkflowRuleId INT NULL,
    EntityType VARCHAR(100) NOT NULL,
    EntityId INT NOT NULL,
    Status VARCHAR(50) NOT NULL,
    StartedAt DATETIME NOT NULL,
    CompletedAt DATETIME NULL,
    Duration INT NULL,
    ErrorMessage TEXT NULL,
    ErrorStack TEXT NULL,
    RetryCount INT NOT NULL DEFAULT 0,
    InputData TEXT NULL,
    OutputData TEXT NULL,
    ExecutedByUserId INT NULL,
    IsManual BOOLEAN NOT NULL DEFAULT FALSE,
    ParentExecutionId INT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_WorkflowExecutions_Workflow FOREIGN KEY (WorkflowId) REFERENCES Workflows(Id),
    CONSTRAINT FK_WorkflowExecutions_Rule FOREIGN KEY (WorkflowRuleId) REFERENCES WorkflowRules(Id),
    CONSTRAINT FK_WorkflowExecutions_User FOREIGN KEY (ExecutedByUserId) REFERENCES Users(Id),
    CONSTRAINT FK_WorkflowExecutions_Parent FOREIGN KEY (ParentExecutionId) REFERENCES WorkflowExecutions(Id),
    INDEX IX_WorkflowExecutions_Status (Status),
    INDEX IX_WorkflowExecutions_StartedAt (StartedAt)
) ENGINE=InnoDB;

-- =============================================
-- Performance Indexes
-- =============================================

CREATE INDEX IX_Users_IsActive ON Users (IsActive);
CREATE INDEX IX_Users_Role ON Users (Role);
CREATE INDEX IX_Customers_Company ON Customers (Company);
CREATE INDEX IX_Customers_LifecycleStage ON Customers (LifecycleStage);
CREATE INDEX IX_Customers_AssignedTo ON Customers (AssignedToUserId);

-- =============================================
-- Initial Data
-- =============================================

-- Note: Admin user and sample data should be created using the CRM.DatabaseSeeder application
