#!/usr/bin/env python3
"""Batch 23: Fortune 100 Companies — Accounts & Contacts.

Creates realistic accounts and linked contacts for top Fortune 100 companies:
Microsoft, Apple, Amazon, Alphabet (Google), JPMorgan Chase, Berkshire Hathaway,
ExxonMobil, UnitedHealth Group, Walmart, Chevron, Johnson & Johnson, Meta,
Tesla, Visa, Mastercard, Procter & Gamble, Home Depot, Bank of America,
Pfizer, Comcast, AbbVie, Costco, Ford, Lockheed Martin, General Electric.
Each account gets 4 contacts linked to it.
"""
from __future__ import annotations
import sys, os, time
sys.path.insert(0, os.path.dirname(__file__))
from loader_utils import ApiClient, RunLogger, save_ids, load_ids


# ── Fortune 100 company definitions ─────────────────────────────────────────
FORTUNE100_COMPANIES = [
    {
        "company": "Microsoft Corporation",
        "industry": "Technology",
        "website": "https://www.microsoft.com",
        "phone": "+1-425-882-8080",
        "email": "enterprise@microsoft.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 211900000000,
        "numberOfEmployees": 221000,
        "description": "Multinational technology corporation — cloud, software, devices.",
        "billingStreet": "One Microsoft Way",
        "billingCity": "Redmond",
        "billingState": "WA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Satya",     "lastName": "Nadella",    "email": "satya.nadella@microsoft.com",    "phone": "+1-425-882-8001", "title": "Chief Executive Officer",  "dept": "Executive"},
            {"firstName": "Amy",       "lastName": "Hood",       "email": "amy.hood@microsoft.com",         "phone": "+1-425-882-8002", "title": "Chief Financial Officer",  "dept": "Finance"},
            {"firstName": "Brad",      "lastName": "Smith",      "email": "brad.smith@microsoft.com",       "phone": "+1-425-882-8003", "title": "President & Vice Chair",   "dept": "Legal"},
            {"firstName": "Charles",   "lastName": "Lamanna",    "email": "charles.lamanna@microsoft.com",  "phone": "+1-425-882-8004", "title": "VP Copilot & AI Products", "dept": "AI"},
        ],
    },
    {
        "company": "Apple Inc.",
        "industry": "Technology",
        "website": "https://www.apple.com",
        "phone": "+1-408-996-1010",
        "email": "enterprise@apple.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 383285000000,
        "numberOfEmployees": 161000,
        "description": "Consumer electronics, software, and online services.",
        "billingStreet": "One Apple Park Way",
        "billingCity": "Cupertino",
        "billingState": "CA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Tim",       "lastName": "Cook",       "email": "tim.cook@apple.com",         "phone": "+1-408-996-1001", "title": "Chief Executive Officer",         "dept": "Executive"},
            {"firstName": "Luca",      "lastName": "Maestri",    "email": "luca.maestri@apple.com",     "phone": "+1-408-996-1002", "title": "Chief Financial Officer",         "dept": "Finance"},
            {"firstName": "Jeff",      "lastName": "Williams",   "email": "jeff.williams@apple.com",    "phone": "+1-408-996-1003", "title": "Chief Operating Officer",         "dept": "Operations"},
            {"firstName": "Eddy",      "lastName": "Cue",        "email": "eddy.cue@apple.com",         "phone": "+1-408-996-1004", "title": "SVP Services",                    "dept": "Services"},
        ],
    },
    {
        "company": "Amazon.com Inc.",
        "industry": "Technology",
        "website": "https://www.amazon.com",
        "phone": "+1-206-266-1000",
        "email": "enterprise@amazon.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 514000000000,
        "numberOfEmployees": 1540000,
        "description": "E-commerce, cloud computing (AWS), and digital streaming.",
        "billingStreet": "410 Terry Ave N",
        "billingCity": "Seattle",
        "billingState": "WA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Andy",      "lastName": "Jassy",      "email": "andy.jassy@amazon.com",       "phone": "+1-206-266-1001", "title": "President & CEO",             "dept": "Executive"},
            {"firstName": "Brian",     "lastName": "Olsavsky",   "email": "brian.olsavsky@amazon.com",   "phone": "+1-206-266-1002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Adam",      "lastName": "Selipsky",   "email": "adam.selipsky@amazon.com",    "phone": "+1-206-266-1003", "title": "CEO Amazon Web Services",      "dept": "AWS"},
            {"firstName": "Dave",      "lastName": "Limp",       "email": "dave.limp@amazon.com",        "phone": "+1-206-266-1004", "title": "SVP Devices & Services",       "dept": "Devices"},
        ],
    },
    {
        "company": "Alphabet Inc. (Google)",
        "industry": "Technology",
        "website": "https://abc.xyz",
        "phone": "+1-650-253-0000",
        "email": "enterprise@google.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 307394000000,
        "numberOfEmployees": 182381,
        "description": "Parent company of Google — search, cloud, advertising, AI.",
        "billingStreet": "1600 Amphitheatre Pkwy",
        "billingCity": "Mountain View",
        "billingState": "CA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Sundar",    "lastName": "Pichai",     "email": "sundar.pichai@google.com",     "phone": "+1-650-253-0001", "title": "CEO Alphabet & Google",        "dept": "Executive"},
            {"firstName": "Ruth",      "lastName": "Porat",      "email": "ruth.porat@google.com",        "phone": "+1-650-253-0002", "title": "President & CIO",              "dept": "Finance"},
            {"firstName": "Thomas",    "lastName": "Kurian",     "email": "thomas.kurian@google.com",     "phone": "+1-650-253-0003", "title": "CEO Google Cloud",             "dept": "Cloud"},
            {"firstName": "Prabhakar", "lastName": "Raghavan",   "email": "prabhakar.raghavan@google.com","phone": "+1-650-253-0004", "title": "VP Search & Ads",              "dept": "Search"},
        ],
    },
    {
        "company": "JPMorgan Chase & Co.",
        "industry": "Financial Services",
        "website": "https://www.jpmorganchase.com",
        "phone": "+1-212-270-6000",
        "email": "enterprise@jpmorgan.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 158103000000,
        "numberOfEmployees": 293723,
        "description": "Global financial services firm — banking, asset management.",
        "billingStreet": "383 Madison Ave",
        "billingCity": "New York",
        "billingState": "NY",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Jamie",     "lastName": "Dimon",      "email": "jamie.dimon@jpmorgan.com",     "phone": "+1-212-270-6001", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Jeremy",    "lastName": "Barnum",     "email": "jeremy.barnum@jpmorgan.com",   "phone": "+1-212-270-6002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Daniel",    "lastName": "Pinto",      "email": "daniel.pinto@jpmorgan.com",    "phone": "+1-212-270-6003", "title": "President & COO",              "dept": "Operations"},
            {"firstName": "Mary",      "lastName": "Callahan",   "email": "mary.callahan@jpmorgan.com",   "phone": "+1-212-270-6004", "title": "Chief Human Resources Officer","dept": "HR"},
        ],
    },
    {
        "company": "Berkshire Hathaway Inc.",
        "industry": "Financial Services",
        "website": "https://www.berkshirehathaway.com",
        "phone": "+1-402-346-1400",
        "email": "enterprise@berkshirehathaway.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 364482000000,
        "numberOfEmployees": 365000,
        "description": "Multinational conglomerate — insurance, energy, railroads, finance.",
        "billingStreet": "3555 Farnam St",
        "billingCity": "Omaha",
        "billingState": "NE",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Warren",    "lastName": "Buffett",    "email": "warren.buffett@berkshirehathaway.com", "phone": "+1-402-346-1401", "title": "Chairman & CEO",          "dept": "Executive"},
            {"firstName": "Charlie",   "lastName": "Munger",     "email": "charlie.munger@berkshirehathaway.com", "phone": "+1-402-346-1402", "title": "Vice Chairman",           "dept": "Executive"},
            {"firstName": "Greg",      "lastName": "Abel",       "email": "greg.abel@berkshirehathaway.com",      "phone": "+1-402-346-1403", "title": "Vice Chairman Non-Insurance", "dept": "Operations"},
            {"firstName": "Marc",      "lastName": "Hamburg",    "email": "marc.hamburg@berkshirehathaway.com",   "phone": "+1-402-346-1404", "title": "Chief Financial Officer", "dept": "Finance"},
        ],
    },
    {
        "company": "ExxonMobil Corporation",
        "industry": "Energy",
        "website": "https://www.exxonmobil.com",
        "phone": "+1-972-940-6000",
        "email": "enterprise@exxonmobil.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 398674000000,
        "numberOfEmployees": 62000,
        "description": "Multinational oil and gas corporation.",
        "billingStreet": "5959 Las Colinas Blvd",
        "billingCity": "Irving",
        "billingState": "TX",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Darren",    "lastName": "Woods",      "email": "darren.woods@exxonmobil.com",  "phone": "+1-972-940-6001", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Kathryn",   "lastName": "Mikells",    "email": "kathryn.mikells@exxonmobil.com","phone": "+1-972-940-6002", "title": "Chief Financial Officer",     "dept": "Finance"},
            {"firstName": "Neil",      "lastName": "Chapman",    "email": "neil.chapman@exxonmobil.com",  "phone": "+1-972-940-6003", "title": "SVP Chemical & Refining",      "dept": "Operations"},
            {"firstName": "Jack",      "lastName": "Williams",   "email": "jack.williams@exxonmobil.com", "phone": "+1-972-940-6004", "title": "VP Corporate Strategy",        "dept": "Strategy"},
        ],
    },
    {
        "company": "UnitedHealth Group Inc.",
        "industry": "Healthcare",
        "website": "https://www.unitedhealthgroup.com",
        "phone": "+1-952-936-1300",
        "email": "enterprise@unitedhealthgroup.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 371622000000,
        "numberOfEmployees": 400000,
        "description": "Diversified managed care and healthcare company.",
        "billingStreet": "9900 Bren Road E",
        "billingCity": "Minnetonka",
        "billingState": "MN",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Andrew",    "lastName": "Witty",      "email": "andrew.witty@uhg.com",          "phone": "+1-952-936-1301", "title": "CEO UnitedHealth Group",       "dept": "Executive"},
            {"firstName": "John",      "lastName": "Rex",        "email": "john.rex@uhg.com",              "phone": "+1-952-936-1302", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Dirk",      "lastName": "McMahon",    "email": "dirk.mcmahon@uhg.com",          "phone": "+1-952-936-1303", "title": "President & COO",              "dept": "Operations"},
            {"firstName": "Tim",       "lastName": "Noel",       "email": "tim.noel@uhg.com",              "phone": "+1-952-936-1304", "title": "CEO UnitedHealthcare",         "dept": "Insurance"},
        ],
    },
    {
        "company": "Walmart Inc.",
        "industry": "Retail",
        "website": "https://www.walmart.com",
        "phone": "+1-479-273-4000",
        "email": "enterprise@walmart.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 648125000000,
        "numberOfEmployees": 2100000,
        "description": "Multinational retail corporation — largest company by revenue.",
        "billingStreet": "702 SW 8th St",
        "billingCity": "Bentonville",
        "billingState": "AR",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Doug",      "lastName": "McMillon",   "email": "doug.mcmillon@walmart.com",     "phone": "+1-479-273-4001", "title": "President & CEO",              "dept": "Executive"},
            {"firstName": "John",      "lastName": "Rainey",     "email": "john.rainey@walmart.com",       "phone": "+1-479-273-4002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Suresh",    "lastName": "Kumar",      "email": "suresh.kumar@walmart.com",      "phone": "+1-479-273-4003", "title": "CTO & CDO",                    "dept": "Technology"},
            {"firstName": "Tom",       "lastName": "Ward",       "email": "tom.ward@walmart.com",          "phone": "+1-479-273-4004", "title": "EVP Walmart US",               "dept": "Operations"},
        ],
    },
    {
        "company": "Chevron Corporation",
        "industry": "Energy",
        "website": "https://www.chevron.com",
        "phone": "+1-925-842-1000",
        "email": "enterprise@chevron.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 236000000000,
        "numberOfEmployees": 43800,
        "description": "Integrated energy and chemicals company.",
        "billingStreet": "6001 Bollinger Canyon Rd",
        "billingCity": "San Ramon",
        "billingState": "CA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Mike",      "lastName": "Wirth",      "email": "mike.wirth@chevron.com",        "phone": "+1-925-842-1001", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Pierre",    "lastName": "Breber",     "email": "pierre.breber@chevron.com",     "phone": "+1-925-842-1002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Nigel",     "lastName": "Hearne",     "email": "nigel.hearne@chevron.com",      "phone": "+1-925-842-1003", "title": "EVP Oil, Products & Gas",      "dept": "Operations"},
            {"firstName": "Al",        "lastName": "Williams",   "email": "al.williams@chevron.com",       "phone": "+1-925-842-1004", "title": "EVP Technology & Services",    "dept": "Technology"},
        ],
    },
    {
        "company": "Johnson & Johnson",
        "industry": "Healthcare",
        "website": "https://www.jnj.com",
        "phone": "+1-732-524-0400",
        "email": "enterprise@jnj.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 93775000000,
        "numberOfEmployees": 156700,
        "description": "Medical devices, pharmaceuticals, and consumer health products.",
        "billingStreet": "One Johnson & Johnson Plaza",
        "billingCity": "New Brunswick",
        "billingState": "NJ",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Joaquin",   "lastName": "Duato",      "email": "joaquin.duato@jnj.com",         "phone": "+1-732-524-0401", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Joseph",    "lastName": "Wolk",       "email": "joseph.wolk@jnj.com",           "phone": "+1-732-524-0402", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "John",      "lastName": "Tafuri",     "email": "john.tafuri@jnj.com",           "phone": "+1-732-524-0403", "title": "Chief Technical Officer",      "dept": "Technology"},
            {"firstName": "Kathryn",   "lastName": "Wengel",     "email": "kathryn.wengel@jnj.com",        "phone": "+1-732-524-0404", "title": "Chief Global Supply Chain",    "dept": "Supply Chain"},
        ],
    },
    {
        "company": "Meta Platforms Inc.",
        "industry": "Technology",
        "website": "https://www.meta.com",
        "phone": "+1-650-543-4800",
        "email": "enterprise@meta.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 134902000000,
        "numberOfEmployees": 86482,
        "description": "Social media, AR/VR, and AI — Facebook, Instagram, WhatsApp.",
        "billingStreet": "1 Hacker Way",
        "billingCity": "Menlo Park",
        "billingState": "CA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Mark",      "lastName": "Zuckerberg", "email": "mark.zuckerberg@meta.com",      "phone": "+1-650-543-4801", "title": "Founder & CEO",                "dept": "Executive"},
            {"firstName": "Susan",     "lastName": "Li",         "email": "susan.li@meta.com",             "phone": "+1-650-543-4802", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Javier",    "lastName": "Olivan",     "email": "javier.olivan@meta.com",        "phone": "+1-650-543-4803", "title": "Chief Operating Officer",      "dept": "Operations"},
            {"firstName": "Andrew",    "lastName": "Bosworth",   "email": "andrew.bosworth@meta.com",      "phone": "+1-650-543-4804", "title": "CTO & VP Reality Labs",        "dept": "Technology"},
        ],
    },
    {
        "company": "Tesla Inc.",
        "industry": "Automotive",
        "website": "https://www.tesla.com",
        "phone": "+1-650-681-5000",
        "email": "enterprise@tesla.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 96773000000,
        "numberOfEmployees": 140473,
        "description": "Electric vehicles, energy storage, and solar power.",
        "billingStreet": "13101 Tesla Rd",
        "billingCity": "Austin",
        "billingState": "TX",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Elon",      "lastName": "Musk",       "email": "elon.musk@tesla.com",           "phone": "+1-650-681-5001", "title": "CEO & Product Architect",      "dept": "Executive"},
            {"firstName": "Vaibhav",   "lastName": "Taneja",     "email": "vaibhav.taneja@tesla.com",      "phone": "+1-650-681-5002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Tom",       "lastName": "Zhu",        "email": "tom.zhu@tesla.com",             "phone": "+1-650-681-5003", "title": "SVP Automotive",               "dept": "Engineering"},
            {"firstName": "Ashok",     "lastName": "Elluswamy",  "email": "ashok.elluswamy@tesla.com",     "phone": "+1-650-681-5004", "title": "VP Autopilot Engineering",     "dept": "AI"},
        ],
    },
    {
        "company": "Visa Inc.",
        "industry": "Financial Services",
        "website": "https://www.visa.com",
        "phone": "+1-650-432-3200",
        "email": "enterprise@visa.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 32654000000,
        "numberOfEmployees": 26500,
        "description": "Global payment technology company.",
        "billingStreet": "900 Metro Center Blvd",
        "billingCity": "Foster City",
        "billingState": "CA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Ryan",      "lastName": "McInerney",  "email": "ryan.mcinerney@visa.com",       "phone": "+1-650-432-3201", "title": "President & CEO",              "dept": "Executive"},
            {"firstName": "Chris",     "lastName": "Suh",        "email": "chris.suh@visa.com",            "phone": "+1-650-432-3202", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Jack",      "lastName": "Forestell",  "email": "jack.forestell@visa.com",       "phone": "+1-650-432-3203", "title": "EVP & CTO",                    "dept": "Technology"},
            {"firstName": "Julie",     "lastName": "Rottler",    "email": "julie.rottler@visa.com",        "phone": "+1-650-432-3204", "title": "Chief People Officer",         "dept": "HR"},
        ],
    },
    {
        "company": "Mastercard Incorporated",
        "industry": "Financial Services",
        "website": "https://www.mastercard.com",
        "phone": "+1-914-249-2000",
        "email": "enterprise@mastercard.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 25098000000,
        "numberOfEmployees": 33000,
        "description": "Global technology company connecting financial institutions.",
        "billingStreet": "2000 Purchase St",
        "billingCity": "Purchase",
        "billingState": "NY",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Michael",   "lastName": "Miebach",    "email": "michael.miebach@mastercard.com", "phone": "+1-914-249-2001", "title": "President & CEO",             "dept": "Executive"},
            {"firstName": "Sachin",    "lastName": "Mehra",      "email": "sachin.mehra@mastercard.com",    "phone": "+1-914-249-2002", "title": "Chief Financial Officer",     "dept": "Finance"},
            {"firstName": "Raj",       "lastName": "Seshadri",   "email": "raj.seshadri@mastercard.com",    "phone": "+1-914-249-2003", "title": "President, North America",    "dept": "Sales"},
            {"firstName": "Edward",    "lastName": "McLaughlin", "email": "edward.mclaughlin@mastercard.com","phone": "+1-914-249-2004", "title": "President, Cyber & Intelligence","dept": "Security"},
        ],
    },
    {
        "company": "Procter & Gamble Co.",
        "industry": "Consumer Goods",
        "website": "https://us.pg.com",
        "phone": "+1-513-983-1100",
        "email": "enterprise@pg.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 82006000000,
        "numberOfEmployees": 107000,
        "description": "Multinational consumer goods corporation — household brands.",
        "billingStreet": "1 Procter & Gamble Plaza",
        "billingCity": "Cincinnati",
        "billingState": "OH",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Jon",       "lastName": "Moeller",    "email": "jon.moeller@pg.com",            "phone": "+1-513-983-1101", "title": "Chairman, President & CEO",    "dept": "Executive"},
            {"firstName": "Andre",     "lastName": "Schulten",   "email": "andre.schulten@pg.com",         "phone": "+1-513-983-1102", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Shailesh",  "lastName": "Jejurikar",  "email": "shailesh.jejurikar@pg.com",     "phone": "+1-513-983-1103", "title": "COO",                          "dept": "Operations"},
            {"firstName": "Carolyn",   "lastName": "Tastad",     "email": "carolyn.tastad@pg.com",         "phone": "+1-513-983-1104", "title": "Group President North America","dept": "Sales"},
        ],
    },
    {
        "company": "The Home Depot Inc.",
        "industry": "Retail",
        "website": "https://www.homedepot.com",
        "phone": "+1-770-433-8211",
        "email": "enterprise@homedepot.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 157403000000,
        "numberOfEmployees": 475000,
        "description": "Home improvement retail chain.",
        "billingStreet": "2455 Paces Ferry Rd NW",
        "billingCity": "Atlanta",
        "billingState": "GA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Ted",       "lastName": "Decker",     "email": "ted.decker@homedepot.com",      "phone": "+1-770-433-8201", "title": "Chair, President & CEO",       "dept": "Executive"},
            {"firstName": "Richard",   "lastName": "McPhail",    "email": "richard.mcphail@homedepot.com", "phone": "+1-770-433-8202", "title": "Executive VP & CFO",           "dept": "Finance"},
            {"firstName": "Ann-Marie", "lastName": "Campbell",   "email": "ann.campbell@homedepot.com",    "phone": "+1-770-433-8203", "title": "EVP - U.S. Stores",            "dept": "Operations"},
            {"firstName": "Matt",      "lastName": "Carey",      "email": "matt.carey@homedepot.com",      "phone": "+1-770-433-8204", "title": "EVP & CIO",                    "dept": "Technology"},
        ],
    },
    {
        "company": "Bank of America Corporation",
        "industry": "Financial Services",
        "website": "https://www.bankofamerica.com",
        "phone": "+1-704-386-5681",
        "email": "enterprise@bankofamerica.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 102217000000,
        "numberOfEmployees": 213000,
        "description": "Multinational investment bank and financial services corporation.",
        "billingStreet": "100 N Tryon St",
        "billingCity": "Charlotte",
        "billingState": "NC",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Brian",     "lastName": "Moynihan",   "email": "brian.moynihan@bofa.com",       "phone": "+1-704-386-5601", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Alastair",  "lastName": "Borthwick",  "email": "alastair.borthwick@bofa.com",   "phone": "+1-704-386-5602", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Andy",      "lastName": "Sieg",       "email": "andy.sieg@bofa.com",            "phone": "+1-704-386-5603", "title": "President Merrill Lynch",      "dept": "Wealth"},
            {"firstName": "Dean",      "lastName": "Athanasia",  "email": "dean.athanasia@bofa.com",       "phone": "+1-704-386-5604", "title": "President Consumer Banking",   "dept": "Retail Banking"},
        ],
    },
    {
        "company": "Pfizer Inc.",
        "industry": "Healthcare",
        "website": "https://www.pfizer.com",
        "phone": "+1-212-733-2323",
        "email": "enterprise@pfizer.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 100330000000,
        "numberOfEmployees": 83000,
        "description": "Multinational pharmaceutical and biotechnology corporation.",
        "billingStreet": "66 Hudson Blvd E",
        "billingCity": "New York",
        "billingState": "NY",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Albert",    "lastName": "Bourla",     "email": "albert.bourla@pfizer.com",      "phone": "+1-212-733-2301", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "David",     "lastName": "Denton",     "email": "david.denton@pfizer.com",       "phone": "+1-212-733-2302", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Mikael",    "lastName": "Dolsten",    "email": "mikael.dolsten@pfizer.com",     "phone": "+1-212-733-2303", "title": "Chief Scientific Officer",     "dept": "R&D"},
            {"firstName": "Angela",    "lastName": "Hwang",      "email": "angela.hwang@pfizer.com",       "phone": "+1-212-733-2304", "title": "Group President Biopharma",    "dept": "Commercial"},
        ],
    },
    {
        "company": "Comcast Corporation",
        "industry": "Telecommunications",
        "website": "https://corporate.comcast.com",
        "phone": "+1-215-286-1700",
        "email": "enterprise@comcast.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 121572000000,
        "numberOfEmployees": 186000,
        "description": "Telecommunications and media conglomerate — NBCUniversal.",
        "billingStreet": "1701 JFK Blvd",
        "billingCity": "Philadelphia",
        "billingState": "PA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Brian",     "lastName": "Roberts",    "email": "brian.roberts@comcast.com",     "phone": "+1-215-286-1701", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Jason",     "lastName": "Armstrong",  "email": "jason.armstrong@comcast.com",   "phone": "+1-215-286-1702", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Mike",      "lastName": "Cavanagh",   "email": "mike.cavanagh@comcast.com",     "phone": "+1-215-286-1703", "title": "President",                    "dept": "Operations"},
            {"firstName": "Jeff",      "lastName": "Shell",      "email": "jeff.shell@comcast.com",        "phone": "+1-215-286-1704", "title": "CEO NBCUniversal",             "dept": "Media"},
        ],
    },
    {
        "company": "AbbVie Inc.",
        "industry": "Healthcare",
        "website": "https://www.abbvie.com",
        "phone": "+1-847-932-7900",
        "email": "enterprise@abbvie.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 58054000000,
        "numberOfEmployees": 50000,
        "description": "Biopharmaceutical company — immunology and oncology.",
        "billingStreet": "1 Waukegan Rd",
        "billingCity": "North Chicago",
        "billingState": "IL",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Richard",   "lastName": "Gonzalez",   "email": "richard.gonzalez@abbvie.com",   "phone": "+1-847-932-7901", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Scott",     "lastName": "Reents",     "email": "scott.reents@abbvie.com",       "phone": "+1-847-932-7902", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Roopal",    "lastName": "Thakkar",    "email": "roopal.thakkar@abbvie.com",     "phone": "+1-847-932-7903", "title": "Chief Medical Officer",        "dept": "Medical"},
            {"firstName": "Azita",     "lastName": "Saleki-Gerhardt", "email": "azita.saleki@abbvie.com", "phone": "+1-847-932-7904", "title": "EVP Operations",               "dept": "Operations"},
        ],
    },
    {
        "company": "Costco Wholesale Corporation",
        "industry": "Retail",
        "website": "https://www.costco.com",
        "phone": "+1-425-313-8100",
        "email": "enterprise@costco.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 238351000000,
        "numberOfEmployees": 316000,
        "description": "Membership-only big-box retail warehouses.",
        "billingStreet": "999 Lake Dr",
        "billingCity": "Issaquah",
        "billingState": "WA",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Ron",       "lastName": "Vachris",    "email": "ron.vachris@costco.com",        "phone": "+1-425-313-8101", "title": "President & CEO",              "dept": "Executive"},
            {"firstName": "Gary",      "lastName": "Millerchip", "email": "gary.millerchip@costco.com",    "phone": "+1-425-313-8102", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Ron",       "lastName": "Griswold",   "email": "ron.griswold@costco.com",       "phone": "+1-425-313-8103", "title": "EVP International Operations", "dept": "International"},
            {"firstName": "Paul",      "lastName": "Moulton",    "email": "paul.moulton@costco.com",       "phone": "+1-425-313-8104", "title": "EVP Information Systems",      "dept": "Technology"},
        ],
    },
    {
        "company": "Ford Motor Company",
        "industry": "Automotive",
        "website": "https://www.ford.com",
        "phone": "+1-313-322-3000",
        "email": "enterprise@ford.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 176191000000,
        "numberOfEmployees": 174000,
        "description": "Multinational automobile manufacturer — Ford and Lincoln brands.",
        "billingStreet": "1 American Road",
        "billingCity": "Dearborn",
        "billingState": "MI",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Jim",       "lastName": "Farley",     "email": "jim.farley@ford.com",           "phone": "+1-313-322-3001", "title": "President & CEO",              "dept": "Executive"},
            {"firstName": "John",      "lastName": "Lawler",     "email": "john.lawler@ford.com",          "phone": "+1-313-322-3002", "title": "Vice Chair & CFO",             "dept": "Finance"},
            {"firstName": "Lisa",      "lastName": "Drake",      "email": "lisa.drake@ford.com",           "phone": "+1-313-322-3003", "title": "VP & CIO",                     "dept": "Technology"},
            {"firstName": "Kumar",      "lastName": "Galhotra",  "email": "kumar.galhotra@ford.com",       "phone": "+1-313-322-3004", "title": "President, Ford Blue",         "dept": "Vehicle Business"},
        ],
    },
    {
        "company": "Lockheed Martin Corporation",
        "industry": "Aerospace & Defense",
        "website": "https://www.lockheedmartin.com",
        "phone": "+1-301-897-6000",
        "email": "enterprise@lmco.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 67571000000,
        "numberOfEmployees": 116000,
        "description": "Aerospace, defense, and security company.",
        "billingStreet": "6801 Rockledge Dr",
        "billingCity": "Bethesda",
        "billingState": "MD",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Jim",       "lastName": "Taiclet",    "email": "jim.taiclet@lmco.com",          "phone": "+1-301-897-6001", "title": "Chairman, President & CEO",    "dept": "Executive"},
            {"firstName": "Jesus",     "lastName": "Malave",     "email": "jesus.malave@lmco.com",         "phone": "+1-301-897-6002", "title": "Executive VP & CFO",           "dept": "Finance"},
            {"firstName": "Frank",     "lastName": "St. John",   "email": "frank.stjohn@lmco.com",         "phone": "+1-301-897-6003", "title": "COO",                          "dept": "Operations"},
            {"firstName": "Greg",      "lastName": "Ulmer",      "email": "greg.ulmer@lmco.com",           "phone": "+1-301-897-6004", "title": "EVP Aeronautics",              "dept": "Aeronautics"},
        ],
    },
    {
        "company": "General Electric Company",
        "industry": "Industrial",
        "website": "https://www.ge.com",
        "phone": "+1-617-443-3000",
        "email": "enterprise@ge.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 68019000000,
        "numberOfEmployees": 172000,
        "description": "Industrial conglomerate — aviation, power, renewable energy.",
        "billingStreet": "901 Main Ave",
        "billingCity": "Norwalk",
        "billingState": "CT",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Larry",     "lastName": "Culp",       "email": "larry.culp@ge.com",             "phone": "+1-617-443-3001", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Carolina",  "lastName": "Dybeck",     "email": "carolina.dybeck@ge.com",        "phone": "+1-617-443-3002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Russell",   "lastName": "Stokes",     "email": "russell.stokes@ge.com",         "phone": "+1-617-443-3003", "title": "VP Corporate Operations",      "dept": "Operations"},
            {"firstName": "Mohamed",   "lastName": "Ali",        "email": "mohamed.ali@ge.com",            "phone": "+1-617-443-3004", "title": "CEO GE Digital",               "dept": "Digital"},
        ],
    },
    {
        "company": "Citigroup Inc.",
        "industry": "Financial Services",
        "website": "https://www.citigroup.com",
        "phone": "+1-212-559-1000",
        "email": "enterprise@citi.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 86000000000,
        "numberOfEmployees": 237000,
        "description": "Multinational investment bank and financial services corporation.",
        "billingStreet": "388 Greenwich St",
        "billingCity": "New York",
        "billingState": "NY",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "Jane",      "lastName": "Fraser",     "email": "jane.fraser@citi.com",          "phone": "+1-212-559-1001", "title": "Chief Executive Officer",      "dept": "Executive"},
            {"firstName": "Mark",      "lastName": "Mason",      "email": "mark.mason@citi.com",           "phone": "+1-212-559-1002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "Sunil",     "lastName": "Garg",       "email": "sunil.garg@citi.com",           "phone": "+1-212-559-1003", "title": "CEO Institutional Clients",    "dept": "Institutional"},
            {"firstName": "David",     "lastName": "Livingstone","email": "david.livingstone@citi.com",    "phone": "+1-212-559-1004", "title": "CEO International",           "dept": "International"},
        ],
    },
    {
        "company": "Goldman Sachs Group Inc.",
        "industry": "Financial Services",
        "website": "https://www.goldmansachs.com",
        "phone": "+1-212-902-1000",
        "email": "enterprise@gs.com",
        "accountType": 1,
        "category": 1,
        "annualRevenue": 54792000000,
        "numberOfEmployees": 44300,
        "description": "Multinational investment bank and financial services company.",
        "billingStreet": "200 West St",
        "billingCity": "New York",
        "billingState": "NY",
        "billingCountry": "US",
        "contacts": [
            {"firstName": "David",     "lastName": "Solomon",    "email": "david.solomon@gs.com",          "phone": "+1-212-902-1001", "title": "Chairman & CEO",               "dept": "Executive"},
            {"firstName": "Denis",     "lastName": "Coleman",    "email": "denis.coleman@gs.com",          "phone": "+1-212-902-1002", "title": "Chief Financial Officer",      "dept": "Finance"},
            {"firstName": "John",      "lastName": "Waldron",    "email": "john.waldron@gs.com",           "phone": "+1-212-902-1003", "title": "President & COO",              "dept": "Operations"},
            {"firstName": "Marc",      "lastName": "Nachmann",   "email": "marc.nachmann@gs.com",          "phone": "+1-212-902-1004", "title": "Global Head Asset Management", "dept": "Asset Management"},
        ],
    },
]


def run(api: ApiClient, log: RunLogger) -> None:
    log.section("BATCH 23: Fortune 100 Companies — Accounts & Contacts")

    fortune100_acct_ids: list[int] = []
    fortune100_contact_ids: list[int] = []

    for company in FORTUNE100_COMPANIES:
        company_name = company["company"]
        log.section(f"  Company: {company_name}")

        # Extract contacts list before building account payload
        contacts_data = company.pop("contacts", [])

        # ── Create Account ────────────────────────────────────────────────────
        acct_id = api.create_and_track("accounts", "/api/accounts", company)

        # Restore contacts list in case of re-runs (defensive)
        company["contacts"] = contacts_data

        if not acct_id:
            log.section(f"  SKIP contacts for {company_name} — account creation failed")
            continue

        fortune100_acct_ids.append(acct_id)

        # ── Create Contacts and link to Account ───────────────────────────────
        company_contact_ids: list[int] = []
        for c in contacts_data:
            contact_payload = {
                "firstName": c["firstName"],
                "lastName":  c["lastName"],
                "emailPrimary": c["email"],
                "phonePrimary": c["phone"],
                "jobTitle":  c["title"],
                "department": c.get("dept", ""),
                "contactType": "Customer",
            }
            cid = api.create_and_track("contacts", "/api/contacts", contact_payload)
            if cid:
                company_contact_ids.append(cid)
                fortune100_contact_ids.append(cid)

                # Link contact to account
                api.post(f"/api/accounts/{acct_id}/contacts", {"contactId": cid})

    # ── Persist IDs for downstream batches ────────────────────────────────────
    save_ids("fortune100_accounts", fortune100_acct_ids)
    save_ids("fortune100_contacts", fortune100_contact_ids)

    # Also append to main accounts/contacts so later batches can reference them
    existing_acct_ids = load_ids("accounts") or []
    existing_contact_ids = load_ids("contacts") or []
    save_ids("accounts", existing_acct_ids + fortune100_acct_ids)
    save_ids("contacts", existing_contact_ids + fortune100_contact_ids)

    print(
        f"  Batch 23 done: {len(fortune100_acct_ids)} Fortune 100 accounts, "
        f"{len(fortune100_contact_ids)} contacts created and linked. "
        f"{log.summary_line()}"
    )
