#!/bin/bash
# =============================================================================
# CRM Solution - Unified Build & Deploy Script
# Always builds on 192.168.0.9, updates version.json, resets UI settings
# =============================================================================

set -e

# Configuration
BUILD_HOST="192.168.0.9"
BUILD_USER="${BUILD_USER:-root}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
VERSION_FILE="${PROJECT_DIR}/version.json"
KUBE_NAMESPACE="crm-app"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Helper functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${CYAN}[STEP]${NC} $1"; }

print_banner() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║         CRM Solution - Build & Deploy Pipeline                   ║"
    echo "║              Build Server: 192.168.0.9                          ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""
}

# Get current version from version.json
get_version() {
    if [ -f "$VERSION_FILE" ]; then
        MAJOR=$(grep -o '"major": *[0-9]*' "$VERSION_FILE" | grep -o '[0-9]*')
        MINOR=$(grep -o '"minor": *[0-9]*' "$VERSION_FILE" | grep -o '[0-9]*')
        PATCH=$(grep -o '"patch": *[0-9]*' "$VERSION_FILE" | grep -o '[0-9]*')
        echo "${MAJOR}.${MINOR}.${PATCH}"
    else
        echo "1.0.0"
    fi
}

# Increment version (patch by default, or major/minor if specified)
increment_version() {
    local type="${1:-patch}"
    local current=$(get_version)
    
    MAJOR=$(echo "$current" | cut -d. -f1)
    MINOR=$(echo "$current" | cut -d. -f2)
    PATCH=$(echo "$current" | cut -d. -f3)
    
    case "$type" in
        major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
        minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
        patch)
            PATCH=$((PATCH + 1))
            ;;
    esac
    
    echo "${MAJOR}.${MINOR}.${PATCH}"
}

# Update version.json with new version and build info
update_version_json() {
    local new_version="${1:-$(increment_version patch)}"
    local build_date=$(date +%Y-%m-%d)
    local build_time=$(date +%H:%M:%S)
    local git_hash=$(git -C "$PROJECT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    local git_branch=$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown")
    
    # Get current image tags from K8s if available
    local api_build=$(ssh ${BUILD_USER}@${BUILD_HOST} "kubectl get deployment crm-api -n ${KUBE_NAMESPACE} -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null" | grep -o 'v[0-9]*$' || echo "v1")
    local frontend_build=$(ssh ${BUILD_USER}@${BUILD_HOST} "kubectl get deployment crm-frontend -n ${KUBE_NAMESPACE} -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null" | grep -o 'v[0-9]*$' || echo "v1")
    
    # Increment build numbers
    local api_build_num=$(echo "$api_build" | tr -d 'v')
    local frontend_build_num=$(echo "$frontend_build" | tr -d 'v')
    api_build_num=$((api_build_num + 1))
    frontend_build_num=$((frontend_build_num + 1))
    
    # Get ZIP code stats from DB if available
    local zip_count=$(ssh ${BUILD_USER}@${BUILD_HOST} "kubectl exec deployment/crm-db -n ${KUBE_NAMESPACE} -- mariadb -u root -pRootPass@Dev2024 crm_db -sN -e 'SELECT COUNT(*) FROM ZipCodes' 2>/dev/null" || echo "0")
    local country_count=$(ssh ${BUILD_USER}@${BUILD_HOST} "kubectl exec deployment/crm-db -n ${KUBE_NAMESPACE} -- mariadb -u root -pRootPass@Dev2024 crm_db -sN -e 'SELECT COUNT(DISTINCT CountryCode) FROM ZipCodes' 2>/dev/null" || echo "0")
    
    MAJOR=$(echo "$new_version" | cut -d. -f1)
    MINOR=$(echo "$new_version" | cut -d. -f2)
    PATCH=$(echo "$new_version" | cut -d. -f3)
    
    cat > "$VERSION_FILE" << EOF
{
  "major": ${MAJOR},
  "minor": ${MINOR},
  "patch": ${PATCH},
  "lastUpdate": "${build_date}",
  "description": "Auto-generated by build-and-deploy.sh",
  "git": {
    "branch": "${git_branch}",
    "commit": "${git_hash}"
  },
  "components": {
    "api": {
      "version": "${new_version}",
      "build": "v${api_build_num}",
      "lastDeployed": "${build_date}T${build_time}"
    },
    "frontend": {
      "version": "${new_version}",
      "build": "v${frontend_build_num}",
      "lastDeployed": "${build_date}T${build_time}"
    },
    "database": {
      "version": "${new_version}",
      "schema": "EF Core Migrations",
      "zipCodes": ${zip_count:-0},
      "countries": ${country_count:-0}
    }
  },
  "buildServer": "${BUILD_HOST}",
  "buildTime": "${build_date}T${build_time}"
}
EOF
    
    log_success "Updated version.json to ${new_version}"
    
    # Export for use in build
    export API_BUILD_TAG="v${api_build_num}"
    export FRONTEND_BUILD_TAG="v${frontend_build_num}"
    export APP_VERSION="${new_version}"
}

# Check SSH connectivity
check_ssh() {
    log_step "Checking SSH connectivity to ${BUILD_HOST}..."
    if ! ssh -o ConnectTimeout=5 -o BatchMode=yes ${BUILD_USER}@${BUILD_HOST} "echo 'SSH OK'" &>/dev/null; then
        log_error "Cannot connect to ${BUILD_HOST}. Please check SSH configuration."
        log_info "Hint: Run 'ssh-copy-id ${BUILD_USER}@${BUILD_HOST}' to setup SSH keys"
        exit 1
    fi
    log_success "SSH connectivity verified"
}

# Sync source code to build server
sync_source() {
    log_step "Syncing source code to ${BUILD_HOST}..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} "mkdir -p /opt/crm/source"
    
    rsync -avz --delete \
        --exclude 'node_modules' \
        --exclude 'bin' \
        --exclude 'obj' \
        --exclude '.git' \
        --exclude 'coverage' \
        --exclude 'build' \
        "${PROJECT_DIR}/" ${BUILD_USER}@${BUILD_HOST}:/opt/crm/source/
    
    log_success "Source code synced"
}

# Build Docker images on remote server
build_images() {
    log_step "Building Docker images on ${BUILD_HOST}..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << BUILD_SCRIPT
        set -e
        cd /opt/crm/source
        
        echo "=== Building Backend API (${API_BUILD_TAG}) ==="
        docker build -f docker/Dockerfile.backend -t crm-backend:${API_BUILD_TAG} .
        
        echo "=== Building Frontend (${FRONTEND_BUILD_TAG}) ==="
        docker build -f docker/Dockerfile.frontend -t crm-frontend:${FRONTEND_BUILD_TAG} \
            --build-arg REACT_APP_VERSION=${APP_VERSION} \
            --build-arg REACT_APP_BUILD_DATE=$(date +%Y-%m-%d) .
        
        echo "=== Images built successfully ==="
        docker images | grep -E "crm-(backend|frontend):${API_BUILD_TAG}|crm-(backend|frontend):${FRONTEND_BUILD_TAG}" || true
BUILD_SCRIPT
    
    log_success "Docker images built"
}

# Deploy using Docker Compose
deploy_docker_compose() {
    log_step "Deploying with Docker Compose on ${BUILD_HOST}..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << 'DEPLOY_SCRIPT'
        set -e
        cd /opt/crm/source
        
        echo "=== Stopping existing containers ==="
        docker stop crm-api crm-frontend 2>/dev/null || true
        docker rm crm-api crm-frontend 2>/dev/null || true
        
        echo "=== Starting API container ==="
        docker run -d --name crm-api \
            --restart unless-stopped \
            --network crm-database-network \
            -p 5000:5000 \
            -v /opt/crm/data:/app/data \
            -v /opt/crm/ssl:/app/ssl:ro \
            -e ASPNETCORE_ENVIRONMENT=Production \
            -e "ASPNETCORE_URLS=http://+:5000" \
            -e "ConnectionStrings__DefaultConnection=Server=crm-mariadb;Port=3306;Database=crm_db;User=crm_user;Password=CrmPass@Dev2024!;" \
            -e "Jwt__Secret=CrmSuperSecretKey2024ForJwtTokenGenerationMinimum32Chars" \
            -e "Jwt__Issuer=CrmApi" \
            -e "Jwt__Audience=CrmClient" \
            -e "Jwt__ExpirationMinutes=1440" \
            -e "Cors__AllowedOrigins=http://192.168.0.9,http://localhost:3000,http://localhost" \
            -e "AllowedHosts=*" \
            --health-cmd="curl -f http://localhost:5000/api/health || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            crm-backend:v2
        
        echo "=== Starting Frontend container ==="
        docker run -d --name crm-frontend \
            --restart unless-stopped \
            --network crm-database-network \
            -p 80:80 \
            --health-cmd="curl -f http://localhost/ || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            crm-frontend:v2
        
        echo "=== Waiting for containers to be healthy ==="
        sleep 5
        
        echo "=== Container Status ==="
        docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "crm-api|crm-frontend|NAMES"
DEPLOY_SCRIPT
    
    log_success "Docker Compose deployment complete"
}

# Deploy to Kubernetes (if available)
deploy_kubernetes() {
    log_step "Deploying to Kubernetes on ${BUILD_HOST}..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << DEPLOY_SCRIPT
        set -e
        
        echo "=== Updating API deployment ==="
        kubectl set image deployment/crm-api crm-api=crm-backend:${API_BUILD_TAG} -n ${KUBE_NAMESPACE}
        kubectl rollout status deployment/crm-api -n ${KUBE_NAMESPACE} --timeout=120s
        
        echo "=== Updating Frontend deployment ==="
        kubectl set image deployment/crm-frontend crm-frontend=crm-frontend:${FRONTEND_BUILD_TAG} -n ${KUBE_NAMESPACE}
        kubectl rollout status deployment/crm-frontend -n ${KUBE_NAMESPACE} --timeout=120s
        
        echo "=== Deployment Status ==="
        kubectl get pods -n ${KUBE_NAMESPACE}
DEPLOY_SCRIPT
    
    log_success "Kubernetes deployment complete"
}

# Reset UI settings to defaults
reset_ui_settings() {
    log_step "Resetting UI settings to defaults..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << RESET_SCRIPT
        kubectl exec deployment/crm-db -n ${KUBE_NAMESPACE} -- mariadb -u root -pRootPass@Dev2024 crm_db << 'SQL'
-- Reset Navigation Settings to Default (all visible, proper order)
UPDATE NavigationSettings SET 
    IsVisible = 1,
    IsEnabled = 1
WHERE 1=1;

-- Reset Module Configurations (all enabled)
UPDATE ModuleConfigurations SET 
    IsEnabled = 1,
    IsVisible = 1
WHERE 1=1;

-- Reset Feature Flags (all enabled)
UPDATE FeatureFlags SET 
    IsEnabled = 1
WHERE 1=1;

-- Reset User Preferences to defaults (clear custom nav orders)
UPDATE UserPreferences SET 
    PreferenceValue = NULL
WHERE PreferenceKey LIKE '%nav%order%' OR PreferenceKey LIKE '%navigation%';

SELECT 'UI Settings Reset Complete' as Status;
SQL
RESET_SCRIPT
    
    log_success "UI settings reset to defaults"
}

# Run database migrations
run_migrations() {
    log_step "Running database migrations..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << MIGRATE
        kubectl exec deployment/crm-api -n ${KUBE_NAMESPACE} -- dotnet ef database update --context CrmDbContext 2>/dev/null || echo "Migrations applied or not needed"
MIGRATE
    
    log_success "Database migrations complete"
}

# Verify deployment
verify_deployment() {
    log_step "Verifying deployment..."
    
    ssh ${BUILD_USER}@${BUILD_HOST} << VERIFY
        echo "=== Container Status ==="
        docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "crm-|NAMES"
        
        echo ""
        echo "=== Health Check ==="
        sleep 3
        curl -s http://localhost:5000/api/health 2>/dev/null && echo "" || echo "API health check pending..."
        curl -s -o /dev/null -w "Frontend: HTTP %{http_code}\n" http://localhost/ 2>/dev/null || echo "Frontend check pending..."
        
        echo ""
        echo "=== Access URLs ==="
        echo "  API:      http://192.168.0.9:5000"
        echo "  Frontend: http://192.168.0.9"
        echo "  Adminer:  http://192.168.0.9:8080"
VERIFY
    
    log_success "Deployment verification complete"
}

# Main execution
main() {
    print_banner
    
    local version_type="${1:-patch}"
    
    log_info "Build Type: ${version_type}"
    log_info "Current Version: $(get_version)"
    
    check_ssh
    
    # Update version before build
    update_version_json "$(increment_version $version_type)"
    log_info "New Version: $(get_version)"
    log_info "API Build: ${API_BUILD_TAG}"
    log_info "Frontend Build: ${FRONTEND_BUILD_TAG}"
    
    sync_source
    build_images
    deploy_docker_compose
    # run_migrations  # Disabled - migrations handled separately
    # reset_ui_settings  # Disabled - not needed for Docker Compose
    verify_deployment
    
    echo ""
    log_success "╔══════════════════════════════════════════════════════════════════╗"
    log_success "║                    Build & Deploy Complete!                      ║"
    log_success "║  Version: $(get_version)  |  API: ${API_BUILD_TAG}  |  Frontend: ${FRONTEND_BUILD_TAG}  ║"
    log_success "╚══════════════════════════════════════════════════════════════════╝"
}

# Parse command line arguments
case "$1" in
    major|minor|patch)
        main "$1"
        ;;
    reset-ui)
        check_ssh
        reset_ui_settings
        ;;
    version)
        echo "Current version: $(get_version)"
        ;;
    *)
        echo "Usage: $0 [major|minor|patch|reset-ui|version]"
        echo ""
        echo "Commands:"
        echo "  patch    - Increment patch version and deploy (default)"
        echo "  minor    - Increment minor version and deploy"
        echo "  major    - Increment major version and deploy"
        echo "  reset-ui - Reset UI settings to defaults only"
        echo "  version  - Show current version"
        exit 0
        ;;
esac
