-- Create WorkflowInstances table with correct schema
CREATE TABLE IF NOT EXISTS WorkflowInstances (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WorkflowDefinitionId INT NOT NULL,
    WorkflowVersionId INT NOT NULL,
    CorrelationId VARCHAR(100) NOT NULL,
    EntityType VARCHAR(100) NOT NULL,
    EntityId INT NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    CurrentNodeId INT NULL,
    StartedAt DATETIME(6) NULL,
    CompletedAt DATETIME(6) NULL,
    ScheduledAt DATETIME(6) NULL,
    Priority INT NOT NULL DEFAULT 100,
    TriggerEvent VARCHAR(100) NULL,
    TriggeredById INT NULL,
    InputData LONGTEXT NULL,
    StateData LONGTEXT NULL,
    OutputData LONGTEXT NULL,
    ErrorMessage LONGTEXT NULL,
    ErrorStackTrace LONGTEXT NULL,
    RetryCount INT NOT NULL DEFAULT 0,
    MaxRetries INT NOT NULL DEFAULT 3,
    NextRetryAt DATETIME(6) NULL,
    TimeoutAt DATETIME(6) NULL,
    IsCancelled TINYINT(1) NOT NULL DEFAULT 0,
    CancellationReason VARCHAR(500) NULL,
    ParentInstanceId INT NULL,
    CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UpdatedAt DATETIME(6) NULL,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    INDEX IX_WorkflowInstances_WorkflowDefinitionId (WorkflowDefinitionId),
    INDEX IX_WorkflowInstances_WorkflowVersionId (WorkflowVersionId),
    INDEX IX_WorkflowInstances_Status (Status),
    INDEX IX_WorkflowInstances_CorrelationId (CorrelationId),
    INDEX IX_WorkflowInstances_EntityType_EntityId (EntityType, EntityId)
);

-- Create WorkflowNodeInstances table
CREATE TABLE IF NOT EXISTS WorkflowNodeInstances (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WorkflowInstanceId INT NOT NULL,
    WorkflowNodeId INT NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    EnteredAt DATETIME(6) NULL,
    StartedAt DATETIME(6) NULL,
    CompletedAt DATETIME(6) NULL,
    InputData LONGTEXT NULL,
    OutputData LONGTEXT NULL,
    ErrorMessage LONGTEXT NULL,
    ErrorStackTrace LONGTEXT NULL,
    RetryCount INT NOT NULL DEFAULT 0,
    MaxRetries INT NOT NULL DEFAULT 3,
    NextRetryAt DATETIME(6) NULL,
    TimeoutAt DATETIME(6) NULL,
    ExecutedById INT NULL,
    SelectedTransitionId INT NULL,
    CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UpdatedAt DATETIME(6) NULL,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    INDEX IX_WorkflowNodeInstances_WorkflowInstanceId (WorkflowInstanceId),
    INDEX IX_WorkflowNodeInstances_WorkflowNodeId (WorkflowNodeId),
    INDEX IX_WorkflowNodeInstances_Status (Status)
);
