#!/bin/bash
# =============================================================================
# CRM Solution - Test Gap Generator
# =============================================================================
# This script analyzes the test gaps identified in the comprehensive test
# strategy and generates stub tests for the missing coverage areas.
#
# Usage:
#   ./scripts/generate-gap-tests.sh              # Generate all gap tests
#   ./scripts/generate-gap-tests.sh --backend    # Generate backend tests only
#   ./scripts/generate-gap-tests.sh --frontend   # Generate frontend tests only
#   ./scripts/generate-gap-tests.sh --e2e        # Generate E2E tests only
# =============================================================================

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[CREATED]${NC} $1"
}

# =============================================================================
# Generate Backend Controller Tests
# =============================================================================

generate_contacts_controller_tests() {
    local file="${PROJECT_ROOT}/CRM.Backend/tests/Controllers/ContactsControllerTests.cs"
    
    if [[ -f "$file" ]]; then
        log_info "ContactsControllerTests.cs already exists, skipping..."
        return
    fi
    
    cat > "$file" << 'EOF'
// CRM Solution - Contacts Controller Tests
// Generated by gap test generator

using Xunit;
using Moq;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc;
using CRM.Api.Controllers;
using CRM.Core.Interfaces;
using CRM.Core.Dtos;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CRM.Tests.Controllers;

/// <summary>
/// Unit tests for ContactsController
/// </summary>
public class ContactsControllerTests
{
    private readonly Mock<IContactsService> _mockContactsService;
    private readonly ContactsController _controller;

    public ContactsControllerTests()
    {
        _mockContactsService = new Mock<IContactsService>();
        _controller = new ContactsController(_mockContactsService.Object);
    }

    #region GetAll Tests

    [Fact]
    public async Task GetAll_ReturnsOkWithContacts()
    {
        // Arrange
        var contacts = new List<ContactDto>
        {
            new ContactDto { Id = 1, FirstName = "John", LastName = "Doe" },
            new ContactDto { Id = 2, FirstName = "Jane", LastName = "Smith" }
        };
        _mockContactsService.Setup(s => s.GetAllAsync()).ReturnsAsync(contacts);

        // Act
        var result = await _controller.GetAll();

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var returnedContacts = okResult.Value.Should().BeAssignableTo<IEnumerable<ContactDto>>().Subject;
        returnedContacts.Should().HaveCount(2);
    }

    [Fact]
    public async Task GetAll_ReturnsEmptyListWhenNoContacts()
    {
        // Arrange
        _mockContactsService.Setup(s => s.GetAllAsync()).ReturnsAsync(new List<ContactDto>());

        // Act
        var result = await _controller.GetAll();

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var returnedContacts = okResult.Value.Should().BeAssignableTo<IEnumerable<ContactDto>>().Subject;
        returnedContacts.Should().BeEmpty();
    }

    #endregion

    #region GetById Tests

    [Fact]
    public async Task GetById_WithValidId_ReturnsContact()
    {
        // Arrange
        var contact = new ContactDto { Id = 1, FirstName = "John", LastName = "Doe" };
        _mockContactsService.Setup(s => s.GetByIdAsync(1)).ReturnsAsync(contact);

        // Act
        var result = await _controller.GetById(1);

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var returnedContact = okResult.Value.Should().BeOfType<ContactDto>().Subject;
        returnedContact.Id.Should().Be(1);
    }

    [Fact]
    public async Task GetById_WithInvalidId_ReturnsNotFound()
    {
        // Arrange
        _mockContactsService.Setup(s => s.GetByIdAsync(999)).ReturnsAsync((ContactDto?)null);

        // Act
        var result = await _controller.GetById(999);

        // Assert
        result.Result.Should().BeOfType<NotFoundResult>();
    }

    #endregion

    #region Create Tests

    [Fact]
    public async Task Create_WithValidContact_ReturnsCreatedContact()
    {
        // Arrange
        var createDto = new ContactDto { FirstName = "New", LastName = "Contact", Email = "new@example.com" };
        var createdContact = new ContactDto { Id = 1, FirstName = "New", LastName = "Contact", Email = "new@example.com" };
        _mockContactsService.Setup(s => s.CreateAsync(createDto)).ReturnsAsync(createdContact);

        // Act
        var result = await _controller.Create(createDto);

        // Assert
        var createdResult = result.Result.Should().BeOfType<CreatedAtActionResult>().Subject;
        var returnedContact = createdResult.Value.Should().BeOfType<ContactDto>().Subject;
        returnedContact.Id.Should().Be(1);
    }

    [Fact]
    public async Task Create_WithNullDto_ReturnsBadRequest()
    {
        // Act
        var result = await _controller.Create(null!);

        // Assert
        result.Result.Should().BeOfType<BadRequestResult>();
    }

    #endregion

    #region Update Tests

    [Fact]
    public async Task Update_WithValidContact_ReturnsOk()
    {
        // Arrange
        var updateDto = new ContactDto { Id = 1, FirstName = "Updated", LastName = "Contact" };
        _mockContactsService.Setup(s => s.UpdateAsync(updateDto)).ReturnsAsync(updateDto);

        // Act
        var result = await _controller.Update(1, updateDto);

        // Assert
        result.Result.Should().BeOfType<OkObjectResult>();
    }

    [Fact]
    public async Task Update_WithMismatchedId_ReturnsBadRequest()
    {
        // Arrange
        var updateDto = new ContactDto { Id = 2, FirstName = "Test" };

        // Act
        var result = await _controller.Update(1, updateDto);

        // Assert
        result.Result.Should().BeOfType<BadRequestResult>();
    }

    #endregion

    #region Delete Tests

    [Fact]
    public async Task Delete_WithValidId_ReturnsNoContent()
    {
        // Arrange
        _mockContactsService.Setup(s => s.DeleteAsync(1)).ReturnsAsync(true);

        // Act
        var result = await _controller.Delete(1);

        // Assert
        result.Should().BeOfType<NoContentResult>();
    }

    [Fact]
    public async Task Delete_WithInvalidId_ReturnsNotFound()
    {
        // Arrange
        _mockContactsService.Setup(s => s.DeleteAsync(999)).ReturnsAsync(false);

        // Act
        var result = await _controller.Delete(999);

        // Assert
        result.Should().BeOfType<NotFoundResult>();
    }

    #endregion
}
EOF

    log_success "$file"
}

generate_leads_controller_tests() {
    local file="${PROJECT_ROOT}/CRM.Backend/tests/Controllers/LeadsControllerTests.cs"
    
    if [[ -f "$file" ]]; then
        log_info "LeadsControllerTests.cs already exists, skipping..."
        return
    fi
    
    cat > "$file" << 'EOF'
// CRM Solution - Leads Controller Tests
// Generated by gap test generator

using Xunit;
using Moq;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc;
using CRM.Api.Controllers;
using CRM.Core.Interfaces;
using CRM.Core.Dtos;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CRM.Tests.Controllers;

/// <summary>
/// Unit tests for LeadsController
/// </summary>
public class LeadsControllerTests
{
    private readonly Mock<ILeadService> _mockLeadService;
    private readonly LeadsController _controller;

    public LeadsControllerTests()
    {
        _mockLeadService = new Mock<ILeadService>();
        _controller = new LeadsController(_mockLeadService.Object);
    }

    #region GetAll Tests

    [Fact]
    public async Task GetAll_ReturnsOkWithLeads()
    {
        // Arrange
        var leads = new List<LeadDto>
        {
            new LeadDto { Id = 1, FirstName = "Lead", LastName = "One" },
            new LeadDto { Id = 2, FirstName = "Lead", LastName = "Two" }
        };
        _mockLeadService.Setup(s => s.GetAllAsync()).ReturnsAsync(leads);

        // Act
        var result = await _controller.GetAll();

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var returnedLeads = okResult.Value.Should().BeAssignableTo<IEnumerable<LeadDto>>().Subject;
        returnedLeads.Should().HaveCount(2);
    }

    #endregion

    #region GetById Tests

    [Fact]
    public async Task GetById_WithValidId_ReturnsLead()
    {
        // Arrange
        var lead = new LeadDto { Id = 1, FirstName = "Test", LastName = "Lead" };
        _mockLeadService.Setup(s => s.GetByIdAsync(1)).ReturnsAsync(lead);

        // Act
        var result = await _controller.GetById(1);

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        okResult.Value.Should().BeOfType<LeadDto>();
    }

    [Fact]
    public async Task GetById_WithInvalidId_ReturnsNotFound()
    {
        // Arrange
        _mockLeadService.Setup(s => s.GetByIdAsync(999)).ReturnsAsync((LeadDto?)null);

        // Act
        var result = await _controller.GetById(999);

        // Assert
        result.Result.Should().BeOfType<NotFoundResult>();
    }

    #endregion

    #region Create Tests

    [Fact]
    public async Task Create_WithValidLead_ReturnsCreatedLead()
    {
        // Arrange
        var createDto = new LeadDto { FirstName = "New", LastName = "Lead", Email = "lead@example.com" };
        var createdLead = new LeadDto { Id = 1, FirstName = "New", LastName = "Lead" };
        _mockLeadService.Setup(s => s.CreateAsync(createDto)).ReturnsAsync(createdLead);

        // Act
        var result = await _controller.Create(createDto);

        // Assert
        var createdResult = result.Result.Should().BeOfType<CreatedAtActionResult>().Subject;
        createdResult.Value.Should().BeOfType<LeadDto>();
    }

    #endregion

    #region Lead Conversion Tests

    [Fact]
    public async Task ConvertToOpportunity_WithValidLead_ReturnsOpportunity()
    {
        // Arrange
        var opportunityDto = new OpportunityDto { Id = 1, Name = "Converted Lead" };
        _mockLeadService.Setup(s => s.ConvertToOpportunityAsync(1)).ReturnsAsync(opportunityDto);

        // Act
        var result = await _controller.ConvertToOpportunity(1);

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        okResult.Value.Should().BeOfType<OpportunityDto>();
    }

    [Fact]
    public async Task ConvertToOpportunity_WithInvalidLead_ReturnsNotFound()
    {
        // Arrange
        _mockLeadService.Setup(s => s.ConvertToOpportunityAsync(999)).ReturnsAsync((OpportunityDto?)null);

        // Act
        var result = await _controller.ConvertToOpportunity(999);

        // Assert
        result.Result.Should().BeOfType<NotFoundResult>();
    }

    #endregion
}
EOF

    log_success "$file"
}

generate_auth_controller_tests() {
    local file="${PROJECT_ROOT}/CRM.Backend/tests/Controllers/AuthControllerTests.cs"
    
    if [[ -f "$file" ]]; then
        log_info "AuthControllerTests.cs already exists, skipping..."
        return
    fi
    
    cat > "$file" << 'EOF'
// CRM Solution - Auth Controller Tests
// Generated by gap test generator

using Xunit;
using Moq;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc;
using CRM.Api.Controllers;
using CRM.Core.Interfaces;
using CRM.Core.Dtos;
using System.Threading.Tasks;

namespace CRM.Tests.Controllers;

/// <summary>
/// Unit tests for AuthController - focusing on gap areas:
/// - Password setup flow
/// - Password reset flow
/// - OAuth login
/// - 2FA flows
/// </summary>
public class AuthControllerTests
{
    private readonly Mock<IAuthenticationService> _mockAuthService;
    private readonly AuthController _controller;

    public AuthControllerTests()
    {
        _mockAuthService = new Mock<IAuthenticationService>();
        _controller = new AuthController(_mockAuthService.Object);
    }

    #region Login Tests

    [Fact]
    public async Task Login_WithValidCredentials_ReturnsToken()
    {
        // Arrange
        var request = new LoginRequest { Email = "admin@crm.local", Password = "Admin@123" };
        var response = new AuthResponse { Success = true, AccessToken = "valid-token" };
        _mockAuthService.Setup(s => s.LoginAsync(request.Email, request.Password, null))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.Login(request);

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var authResponse = okResult.Value.Should().BeOfType<AuthResponse>().Subject;
        authResponse.AccessToken.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public async Task Login_WithInvalidCredentials_ReturnsUnauthorized()
    {
        // Arrange
        var request = new LoginRequest { Email = "invalid@example.com", Password = "wrong" };
        var response = new AuthResponse { Success = false, Error = "Invalid credentials" };
        _mockAuthService.Setup(s => s.LoginAsync(request.Email, request.Password, null))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.Login(request);

        // Assert
        result.Result.Should().BeOfType<UnauthorizedObjectResult>();
    }

    [Fact]
    public async Task Login_WithPasswordNeverSet_ReturnsRequiresPasswordSetup()
    {
        // Arrange
        var request = new LoginRequest { Email = "newuser@example.com", Password = "" };
        var response = new AuthResponse 
        { 
            Success = true, 
            RequiresPasswordSetup = true,
            PasswordSetupToken = "setup-token"
        };
        _mockAuthService.Setup(s => s.LoginAsync(request.Email, request.Password, null))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.Login(request);

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var authResponse = okResult.Value.Should().BeOfType<AuthResponse>().Subject;
        authResponse.RequiresPasswordSetup.Should().BeTrue();
        authResponse.PasswordSetupToken.Should().NotBeNullOrEmpty();
    }

    #endregion

    #region Password Setup Tests

    [Fact]
    public async Task SetupPassword_WithValidToken_ReturnsSuccess()
    {
        // Arrange
        var request = new SetupPasswordRequest 
        { 
            Token = "valid-token", 
            NewPassword = "NewPassword123!" 
        };
        var response = new AuthResponse { Success = true };
        _mockAuthService.Setup(s => s.SetupPasswordAsync(request.Token, request.NewPassword))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.SetupPassword(request);

        // Assert
        result.Result.Should().BeOfType<OkObjectResult>();
    }

    [Fact]
    public async Task SetupPassword_WithInvalidToken_ReturnsBadRequest()
    {
        // Arrange
        var request = new SetupPasswordRequest 
        { 
            Token = "invalid-token", 
            NewPassword = "NewPassword123!" 
        };
        var response = new AuthResponse { Success = false, Error = "Invalid token" };
        _mockAuthService.Setup(s => s.SetupPasswordAsync(request.Token, request.NewPassword))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.SetupPassword(request);

        // Assert
        result.Result.Should().BeOfType<BadRequestObjectResult>();
    }

    [Fact]
    public async Task SetupPassword_WithWeakPassword_ReturnsBadRequest()
    {
        // Arrange
        var request = new SetupPasswordRequest 
        { 
            Token = "valid-token", 
            NewPassword = "123" // Too weak
        };
        var response = new AuthResponse { Success = false, Error = "Password does not meet requirements" };
        _mockAuthService.Setup(s => s.SetupPasswordAsync(request.Token, request.NewPassword))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.SetupPassword(request);

        // Assert
        result.Result.Should().BeOfType<BadRequestObjectResult>();
    }

    #endregion

    #region Password Reset Tests

    [Fact]
    public async Task ForgotPassword_WithValidEmail_ReturnsOk()
    {
        // Arrange
        var request = new ForgotPasswordRequest { Email = "user@example.com" };
        _mockAuthService.Setup(s => s.SendPasswordResetEmailAsync(request.Email))
            .ReturnsAsync(true);

        // Act
        var result = await _controller.ForgotPassword(request);

        // Assert
        result.Should().BeOfType<OkObjectResult>();
    }

    [Fact]
    public async Task ForgotPassword_WithNonExistentEmail_StillReturnsOk()
    {
        // Arrange - Always return OK to prevent email enumeration
        var request = new ForgotPasswordRequest { Email = "nonexistent@example.com" };
        _mockAuthService.Setup(s => s.SendPasswordResetEmailAsync(request.Email))
            .ReturnsAsync(false);

        // Act
        var result = await _controller.ForgotPassword(request);

        // Assert - Should still return OK for security
        result.Should().BeOfType<OkObjectResult>();
    }

    [Fact]
    public async Task ResetPassword_WithValidToken_ReturnsSuccess()
    {
        // Arrange
        var request = new ResetPasswordRequest 
        { 
            Token = "valid-reset-token", 
            NewPassword = "NewSecurePassword123!" 
        };
        var response = new AuthResponse { Success = true };
        _mockAuthService.Setup(s => s.ResetPasswordAsync(request.Token, request.NewPassword))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.ResetPassword(request);

        // Assert
        result.Result.Should().BeOfType<OkObjectResult>();
    }

    #endregion

    #region 2FA Tests

    [Fact]
    public async Task Enable2FA_ReturnsQRCodeAndSecret()
    {
        // Arrange
        var response = new TwoFactorSetupResponse 
        { 
            QrCodeUrl = "data:image/png;base64,...",
            Secret = "JBSWY3DPEHPK3PXP"
        };
        _mockAuthService.Setup(s => s.EnableTwoFactorAsync(It.IsAny<int>()))
            .ReturnsAsync(response);

        // Act
        var result = await _controller.Enable2FA();

        // Assert
        var okResult = result.Result.Should().BeOfType<OkObjectResult>().Subject;
        var setupResponse = okResult.Value.Should().BeOfType<TwoFactorSetupResponse>().Subject;
        setupResponse.QrCodeUrl.Should().NotBeNullOrEmpty();
        setupResponse.Secret.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public async Task Verify2FA_WithValidCode_ReturnsSuccess()
    {
        // Arrange
        var request = new Verify2FARequest { Code = "123456" };
        _mockAuthService.Setup(s => s.VerifyTwoFactorAsync(It.IsAny<int>(), request.Code))
            .ReturnsAsync(true);

        // Act
        var result = await _controller.Verify2FA(request);

        // Assert
        result.Should().BeOfType<OkResult>();
    }

    [Fact]
    public async Task Verify2FA_WithInvalidCode_ReturnsBadRequest()
    {
        // Arrange
        var request = new Verify2FARequest { Code = "000000" };
        _mockAuthService.Setup(s => s.VerifyTwoFactorAsync(It.IsAny<int>(), request.Code))
            .ReturnsAsync(false);

        // Act
        var result = await _controller.Verify2FA(request);

        // Assert
        result.Should().BeOfType<BadRequestObjectResult>();
    }

    #endregion
}

// DTOs for tests (may need to match actual implementation)
public record LoginRequest { public string Email { get; init; } = ""; public string Password { get; init; } = ""; }
public record SetupPasswordRequest { public string Token { get; init; } = ""; public string NewPassword { get; init; } = ""; }
public record ForgotPasswordRequest { public string Email { get; init; } = ""; }
public record ResetPasswordRequest { public string Token { get; init; } = ""; public string NewPassword { get; init; } = ""; }
public record Verify2FARequest { public string Code { get; init; } = ""; }
public record TwoFactorSetupResponse { public string QrCodeUrl { get; init; } = ""; public string Secret { get; init; } = ""; }
EOF

    log_success "$file"
}

# =============================================================================
# Generate E2E Tests
# =============================================================================

generate_password_setup_e2e_tests() {
    local file="${PROJECT_ROOT}/e2e-tests/tests/auth/password-setup.spec.ts"
    
    if [[ -f "$file" ]]; then
        log_info "password-setup.spec.ts already exists, skipping..."
        return
    fi
    
    mkdir -p "${PROJECT_ROOT}/e2e-tests/tests/auth"
    
    cat > "$file" << 'EOF'
/**
 * CRM Solution - Password Setup E2E Tests
 * Tests for first-time password setup flow
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://192.168.0.9';
const API_URL = `${BASE_URL.replace(':80', '')}:5000`;

test.describe('Password Setup Flow', () => {
  
  test.describe('First-Time User Password Setup', () => {
    
    test('PSE-001: User with no password is redirected to setup page', async ({ request, page }) => {
      // This test requires a user with PasswordNeverSet = true
      // The login response should include RequiresPasswordSetup = true
      
      const response = await request.post(`${API_URL}/api/auth/login`, {
        data: { email: 'newuser@crm.local', password: '' }
      });
      
      // If user exists with PasswordNeverSet, should get RequiresPasswordSetup
      const data = await response.json();
      
      if (data.requiresPasswordSetup) {
        expect(data.passwordSetupToken).toBeTruthy();
        
        // Navigate to setup password page
        await page.goto(`${BASE_URL}/setup-password?token=${data.passwordSetupToken}`);
        
        // Should see password setup form
        await expect(page.locator('input[name="password"]')).toBeVisible();
        await expect(page.locator('input[name="confirmPassword"]')).toBeVisible();
      }
    });

    test('PSE-002: Password setup with valid password succeeds', async ({ page }) => {
      // Navigate directly to setup page (requires valid token)
      await page.goto(`${BASE_URL}/setup-password?token=test-token`);
      
      // Fill in password form
      await page.fill('input[name="password"]', 'NewSecurePassword123!');
      await page.fill('input[name="confirmPassword"]', 'NewSecurePassword123!');
      
      // Submit
      await page.click('button[type="submit"]');
      
      // Should redirect to login or dashboard
      await expect(page).toHaveURL(/\/(login|dashboard)/);
    });

    test('PSE-003: Password setup with weak password shows error', async ({ page }) => {
      await page.goto(`${BASE_URL}/setup-password?token=test-token`);
      
      // Try weak password
      await page.fill('input[name="password"]', '123');
      await page.fill('input[name="confirmPassword"]', '123');
      
      await page.click('button[type="submit"]');
      
      // Should show validation error
      await expect(page.locator('.error-message, .MuiFormHelperText-root.Mui-error')).toBeVisible();
    });

    test('PSE-004: Password setup with mismatched passwords shows error', async ({ page }) => {
      await page.goto(`${BASE_URL}/setup-password?token=test-token`);
      
      await page.fill('input[name="password"]', 'SecurePassword123!');
      await page.fill('input[name="confirmPassword"]', 'DifferentPassword123!');
      
      await page.click('button[type="submit"]');
      
      // Should show mismatch error
      await expect(page.locator('text=/passwords.*match|mismatch/i')).toBeVisible();
    });

  });

  test.describe('Admin-Forced Password Reset', () => {
    
    test('PSE-005: User with MustResetPassword is redirected to setup', async ({ request }) => {
      // Login attempt for user with MustResetPassword = true
      const response = await request.post(`${API_URL}/api/auth/login`, {
        data: { email: 'resetuser@crm.local', password: 'OldPassword123!' }
      });
      
      const data = await response.json();
      
      // Should indicate password change required
      expect(data.mustChangePassword || data.requiresPasswordSetup).toBeTruthy();
    });

  });

});

test.describe('Password Reset Flow', () => {
  
  test('PRE-001: Forgot password sends email for valid user', async ({ page }) => {
    await page.goto(`${BASE_URL}/forgot-password`);
    
    await page.fill('input[name="email"]', 'admin@crm.local');
    await page.click('button[type="submit"]');
    
    // Should show success message (always shown for security)
    await expect(page.locator('text=/email.*sent|check.*email/i')).toBeVisible({ timeout: 10000 });
  });

  test('PRE-002: Forgot password shows success even for invalid email', async ({ page }) => {
    await page.goto(`${BASE_URL}/forgot-password`);
    
    await page.fill('input[name="email"]', 'nonexistent@example.com');
    await page.click('button[type="submit"]');
    
    // Should still show success (prevent email enumeration)
    await expect(page.locator('text=/email.*sent|check.*email/i')).toBeVisible({ timeout: 10000 });
  });

  test('PRE-003: Reset password with valid token succeeds', async ({ page }) => {
    // Navigate to reset page with token
    await page.goto(`${BASE_URL}/reset-password?token=valid-reset-token`);
    
    await page.fill('input[name="password"]', 'NewSecurePassword123!');
    await page.fill('input[name="confirmPassword"]', 'NewSecurePassword123!');
    
    await page.click('button[type="submit"]');
    
    // Should redirect to login
    await expect(page).toHaveURL(/\/login/);
  });

});
EOF

    log_success "$file"
}

generate_oauth_e2e_tests() {
    local file="${PROJECT_ROOT}/e2e-tests/tests/auth/oauth.spec.ts"
    
    if [[ -f "$file" ]]; then
        log_info "oauth.spec.ts already exists, skipping..."
        return
    fi
    
    cat > "$file" << 'EOF'
/**
 * CRM Solution - OAuth E2E Tests
 * Tests for Google OAuth login flow
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://192.168.0.9';
const API_URL = `${BASE_URL.replace(':80', '')}:5000`;

test.describe('OAuth Login Flow', () => {

  test.describe('Google OAuth', () => {
    
    test('OAUTH-001: Google login button is visible', async ({ page }) => {
      await page.goto(`${BASE_URL}/login`);
      
      // Check for Google login button
      const googleButton = page.locator('button:has-text("Google"), [data-testid="google-login"]');
      
      // Button should exist (may be disabled if OAuth not configured)
      await expect(googleButton).toBeVisible();
    });

    test('OAUTH-002: Clicking Google login redirects to Google', async ({ page }) => {
      await page.goto(`${BASE_URL}/login`);
      
      const googleButton = page.locator('button:has-text("Google"), [data-testid="google-login"]');
      
      // Skip if button is disabled (OAuth not configured)
      const isDisabled = await googleButton.isDisabled();
      test.skip(isDisabled, 'Google OAuth is not configured');
      
      // Click and check redirect
      await googleButton.click();
      
      // Should redirect to Google or show OAuth popup
      await expect(page).toHaveURL(/accounts\.google\.com|googleapis\.com/);
    });

    test('OAUTH-003: OAuth callback with valid code succeeds', async ({ request }) => {
      // Simulate OAuth callback with authorization code
      // Note: This requires a mock OAuth server or test credentials
      
      const response = await request.post(`${API_URL}/api/auth/google/callback`, {
        data: { code: 'test-auth-code' }
      });
      
      // Should return 200 or 400 depending on configuration
      expect(response.status()).toBeLessThan(500);
    });

    test('OAUTH-004: OAuth callback with invalid code fails gracefully', async ({ request }) => {
      const response = await request.post(`${API_URL}/api/auth/google/callback`, {
        data: { code: 'invalid-code' }
      });
      
      // Should return 400 or 401, not 500
      expect(response.status()).toBeLessThan(500);
    });

  });

  test.describe('OAuth User Creation', () => {
    
    test('OAUTH-005: New OAuth user is created in system', async ({ request }) => {
      // This test verifies that a new user is created when logging in via OAuth for the first time
      // Requires mock OAuth flow
      test.skip(true, 'Requires mock OAuth server');
    });

    test('OAUTH-006: Existing OAuth user is linked correctly', async ({ request }) => {
      // This test verifies that an existing user logging in via OAuth is linked correctly
      test.skip(true, 'Requires mock OAuth server');
    });

  });

});
EOF

    log_success "$file"
}

# =============================================================================
# Generate Frontend Component Tests
# =============================================================================

generate_setup_password_page_tests() {
    local file="${PROJECT_ROOT}/CRM.Frontend/src/__tests__/SetupPasswordPage.test.tsx"
    
    if [[ -f "$file" ]]; then
        log_info "SetupPasswordPage.test.tsx already exists, skipping..."
        return
    fi
    
    cat > "$file" << 'EOF'
/**
 * CRM Solution - SetupPasswordPage Tests
 * Tests for the password setup page component
 */

import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';

// Mock the auth context
const mockSetupPassword = jest.fn();
const mockNavigate = jest.fn();

jest.mock('../contexts/AuthContext', () => ({
  useAuth: () => ({
    setupPassword: mockSetupPassword,
    isAuthenticated: false,
  }),
}));

jest.mock('react-router-dom', () => ({
  ...jest.requireActual('react-router-dom'),
  useNavigate: () => mockNavigate,
  useSearchParams: () => [new URLSearchParams('token=test-token')],
}));

describe('SetupPasswordPage', () => {
  
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Form Structure', () => {
    
    it('should render password input field', () => {
      const passwordField = { name: 'password', type: 'password' };
      expect(passwordField.type).toBe('password');
    });

    it('should render confirm password input field', () => {
      const confirmField = { name: 'confirmPassword', type: 'password' };
      expect(confirmField.type).toBe('password');
    });

    it('should render submit button', () => {
      const submitButton = { text: 'Set Password', type: 'submit' };
      expect(submitButton.type).toBe('submit');
    });

  });

  describe('Password Validation', () => {
    
    it('should validate minimum length', () => {
      const password = '1234567';
      const minLength = 8;
      expect(password.length).toBeLessThan(minLength);
    });

    it('should validate maximum length', () => {
      const password = 'a'.repeat(129);
      const maxLength = 128;
      expect(password.length).toBeGreaterThan(maxLength);
    });

    it('should validate uppercase requirement', () => {
      const hasUppercase = (password: string) => /[A-Z]/.test(password);
      expect(hasUppercase('password123!')).toBeFalsy();
      expect(hasUppercase('Password123!')).toBeTruthy();
    });

    it('should validate lowercase requirement', () => {
      const hasLowercase = (password: string) => /[a-z]/.test(password);
      expect(hasLowercase('PASSWORD123!')).toBeFalsy();
      expect(hasLowercase('Password123!')).toBeTruthy();
    });

    it('should validate number requirement', () => {
      const hasNumber = (password: string) => /\d/.test(password);
      expect(hasNumber('Password!')).toBeFalsy();
      expect(hasNumber('Password123!')).toBeTruthy();
    });

    it('should validate special character requirement', () => {
      const hasSpecial = (password: string) => /[!@#$%^&*(),.?":{}|<>]/.test(password);
      expect(hasSpecial('Password123')).toBeFalsy();
      expect(hasSpecial('Password123!')).toBeTruthy();
    });

  });

  describe('Password Matching', () => {
    
    it('should detect matching passwords', () => {
      const password = 'SecurePassword123!';
      const confirmPassword = 'SecurePassword123!';
      expect(password).toBe(confirmPassword);
    });

    it('should detect mismatched passwords', () => {
      const password = 'SecurePassword123!';
      const confirmPassword = 'DifferentPassword123!';
      expect(password).not.toBe(confirmPassword);
    });

  });

  describe('Form Submission', () => {
    
    it('should call setupPassword on valid submission', async () => {
      mockSetupPassword.mockResolvedValue({ success: true });
      
      // Simulate successful submission
      await mockSetupPassword('test-token', 'SecurePassword123!');
      
      expect(mockSetupPassword).toHaveBeenCalledWith('test-token', 'SecurePassword123!');
    });

    it('should navigate to dashboard on success', async () => {
      mockSetupPassword.mockResolvedValue({ success: true });
      
      await mockSetupPassword('test-token', 'SecurePassword123!');
      mockNavigate('/dashboard');
      
      expect(mockNavigate).toHaveBeenCalledWith('/dashboard');
    });

    it('should show error message on failure', async () => {
      mockSetupPassword.mockResolvedValue({ 
        success: false, 
        error: 'Invalid token' 
      });
      
      const result = await mockSetupPassword('invalid-token', 'SecurePassword123!');
      
      expect(result.success).toBeFalsy();
      expect(result.error).toBe('Invalid token');
    });

  });

  describe('Password Strength Indicator', () => {
    
    it('should show weak strength for simple passwords', () => {
      const calculateStrength = (password: string): string => {
        let score = 0;
        if (password.length >= 8) score++;
        if (/[A-Z]/.test(password)) score++;
        if (/[a-z]/.test(password)) score++;
        if (/\d/.test(password)) score++;
        if (/[!@#$%^&*(),.?":{}|<>]/.test(password)) score++;
        
        if (score <= 2) return 'weak';
        if (score <= 3) return 'fair';
        if (score <= 4) return 'good';
        return 'strong';
      };
      
      expect(calculateStrength('12345678')).toBe('weak');
      expect(calculateStrength('password')).toBe('weak');
    });

    it('should show strong strength for complex passwords', () => {
      const calculateStrength = (password: string): string => {
        let score = 0;
        if (password.length >= 8) score++;
        if (/[A-Z]/.test(password)) score++;
        if (/[a-z]/.test(password)) score++;
        if (/\d/.test(password)) score++;
        if (/[!@#$%^&*(),.?":{}|<>]/.test(password)) score++;
        
        if (score <= 2) return 'weak';
        if (score <= 3) return 'fair';
        if (score <= 4) return 'good';
        return 'strong';
      };
      
      expect(calculateStrength('SecurePassword123!')).toBe('strong');
    });

  });

});
EOF

    log_success "$file"
}

# =============================================================================
# Main Execution
# =============================================================================

main() {
    echo ""
    echo "=============================================="
    echo "   CRM Solution - Test Gap Generator"
    echo "=============================================="
    echo ""
    
    log_info "Generating missing test files..."
    echo ""
    
    # Backend Controller Tests
    log_info "Generating Backend Controller Tests..."
    generate_contacts_controller_tests
    generate_leads_controller_tests
    generate_auth_controller_tests
    
    # E2E Tests
    log_info "Generating E2E Tests..."
    generate_password_setup_e2e_tests
    generate_oauth_e2e_tests
    
    # Frontend Component Tests
    log_info "Generating Frontend Component Tests..."
    generate_setup_password_page_tests
    
    echo ""
    log_info "Test gap generation complete!"
    echo ""
    echo "Generated test files:"
    echo "  - Controllers/ContactsControllerTests.cs"
    echo "  - Controllers/LeadsControllerTests.cs"
    echo "  - Controllers/AuthControllerTests.cs"
    echo "  - e2e-tests/tests/auth/password-setup.spec.ts"
    echo "  - e2e-tests/tests/auth/oauth.spec.ts"
    echo "  - CRM.Frontend/src/__tests__/SetupPasswordPage.test.tsx"
    echo ""
    echo "Next steps:"
    echo "  1. Review generated test files"
    echo "  2. Adjust to match actual implementation"
    echo "  3. Run tests: ./scripts/run-all-tests.sh"
}

main "$@"
