-- Migration: Add RowVersion columns for optimistic concurrency control
-- Run with: docker exec crm-mariadb sh -c "mariadb -ucrm_user -pCrmPass@Dev2024 crm_db < /tmp/migration.sql"

ALTER TABLE Customers ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Contacts ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Leads ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Opportunities ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Products ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Quotes ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE MarketingCampaigns ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE ServiceRequests ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Notes ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Interactions ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE CrmTasks ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Activities ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE CustomerContacts ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Addresses ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE UserGroups ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Departments ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE OpportunityProducts ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE WorkflowDefinitions ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE WorkflowTasks ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE UserProfiles ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE WorkflowInstances ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;
ALTER TABLE WorkflowNodes ADD COLUMN IF NOT EXISTS RowVersion BINARY(8) NULL DEFAULT NULL;

-- Initialize existing records with RowVersion = 1
UPDATE Customers SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Contacts SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Leads SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Opportunities SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Products SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Quotes SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE MarketingCampaigns SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE ServiceRequests SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Notes SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Users SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Interactions SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE CrmTasks SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Activities SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE CustomerContacts SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Addresses SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE UserGroups SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Departments SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE OpportunityProducts SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE WorkflowDefinitions SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE WorkflowTasks SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE Accounts SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE UserProfiles SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE WorkflowInstances SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;
UPDATE WorkflowNodes SET RowVersion = UNHEX('0000000000000001') WHERE RowVersion IS NULL;

SELECT 'Migration completed successfully' as Status;
