-- Create ServiceRequestTypes table if not exists
CREATE TABLE IF NOT EXISTS ServiceRequestTypes (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(200) NOT NULL,
  RequestType varchar(50) NOT NULL,
  DetailedDescription varchar(2000) DEFAULT NULL,
  WorkflowName varchar(200) DEFAULT NULL,
  PossibleResolutions varchar(4000) DEFAULT NULL,
  FinalCustomerResolutions varchar(2000) DEFAULT NULL,
  CategoryId int(11) NOT NULL,
  SubcategoryId int(11) NOT NULL,
  DisplayOrder int(11) NOT NULL,
  IsActive tinyint(1) NOT NULL,
  DefaultPriority int(11) DEFAULT NULL,
  ResponseTimeHours int(11) DEFAULT NULL,
  ResolutionTimeHours int(11) DEFAULT NULL,
  Tags varchar(500) DEFAULT NULL,
  CreatedAt datetime(6) NOT NULL,
  UpdatedAt datetime(6) DEFAULT NULL,
  IsDeleted tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (Id),
  KEY IX_ServiceRequestTypes_CategoryId (CategoryId),
  KEY IX_ServiceRequestTypes_SubcategoryId (SubcategoryId),
  CONSTRAINT FK_ServiceRequestTypes_ServiceRequestCategories_CategoryId FOREIGN KEY (CategoryId) REFERENCES ServiceRequestCategories (Id) ON DELETE CASCADE,
  CONSTRAINT FK_ServiceRequestTypes_ServiceRequestSubcategories_SubcategoryId FOREIGN KEY (SubcategoryId) REFERENCES ServiceRequestSubcategories (Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
