-- ============================================================================
-- CRM Solution Database Schema - Orders and Order Line Items
-- Version: 1.0
-- Date: 2026-02-17
-- Description: Sales orders and line items for quote-to-cash
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------------------------------------------------------
-- Table: Orders
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Orders` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `OrderNumber` varchar(50) NOT NULL,
  `ExternalOrderId` varchar(100) DEFAULT NULL,
  `CustomerPONumber` varchar(100) DEFAULT NULL,
  `ReferenceNumber` varchar(100) DEFAULT NULL,
  `Name` varchar(200) NOT NULL,
  `Description` varchar(2000) DEFAULT NULL,
  `Status` int(11) NOT NULL DEFAULT 0,
  `OrderType` int(11) NOT NULL DEFAULT 0,
  `FulfillmentMethod` int(11) NOT NULL DEFAULT 0,
  `Priority` int(11) NOT NULL DEFAULT 0,
  `OrderDate` datetime(6) NOT NULL,
  `ApprovedDate` datetime(6) DEFAULT NULL,
  `RequestedDeliveryDate` datetime(6) DEFAULT NULL,
  `PromisedDeliveryDate` datetime(6) DEFAULT NULL,
  `ShippedDate` datetime(6) DEFAULT NULL,
  `DeliveredDate` datetime(6) DEFAULT NULL,
  `CompletedDate` datetime(6) DEFAULT NULL,
  `CancelledDate` datetime(6) DEFAULT NULL,
  `ContractStartDate` datetime(6) DEFAULT NULL,
  `ContractEndDate` datetime(6) DEFAULT NULL,
  `Subtotal` decimal(18,4) NOT NULL DEFAULT 0,
  `DiscountAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(18,4) NOT NULL DEFAULT 0,
  `DiscountReason` varchar(500) DEFAULT NULL,
  `TaxAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `TaxRate` decimal(18,4) NOT NULL DEFAULT 0,
  `ShippingAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `HandlingAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `TotalAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `CurrencyCode` varchar(3) NOT NULL DEFAULT 'USD',
  `ExchangeRate` decimal(18,6) DEFAULT NULL,
  `BaseCurrencyAmount` decimal(18,4) DEFAULT NULL,
  `MRR` decimal(18,4) DEFAULT NULL,
  `ARR` decimal(18,4) DEFAULT NULL,
  `TCV` decimal(18,4) DEFAULT NULL,
  `ACV` decimal(18,4) DEFAULT NULL,
  `OneTimeRevenue` decimal(18,4) DEFAULT NULL,
  `RecurringRevenue` decimal(18,4) DEFAULT NULL,
  `BillingName` varchar(200) DEFAULT NULL,
  `BillingCompany` varchar(200) DEFAULT NULL,
  `BillingStreet` varchar(500) DEFAULT NULL,
  `BillingCity` varchar(100) DEFAULT NULL,
  `BillingState` varchar(100) DEFAULT NULL,
  `BillingPostalCode` varchar(50) DEFAULT NULL,
  `BillingCountry` varchar(100) DEFAULT NULL,
  `BillingPhone` varchar(50) DEFAULT NULL,
  `BillingEmail` varchar(255) DEFAULT NULL,
  `ShippingName` varchar(200) DEFAULT NULL,
  `ShippingCompany` varchar(200) DEFAULT NULL,
  `ShippingStreet` varchar(500) DEFAULT NULL,
  `ShippingCity` varchar(100) DEFAULT NULL,
  `ShippingState` varchar(100) DEFAULT NULL,
  `ShippingPostalCode` varchar(50) DEFAULT NULL,
  `ShippingCountry` varchar(100) DEFAULT NULL,
  `ShippingPhone` varchar(50) DEFAULT NULL,
  `ShippingEmail` varchar(255) DEFAULT NULL,
  `ShippingInstructions` varchar(1000) DEFAULT NULL,
  `ShippingMethod` varchar(100) DEFAULT NULL,
  `TrackingNumber` varchar(100) DEFAULT NULL,
  `TrackingUrl` varchar(500) DEFAULT NULL,
  `ShippingWeight` decimal(18,4) DEFAULT NULL,
  `PackageCount` int(11) DEFAULT NULL,
  `PaymentTerms` varchar(100) DEFAULT NULL,
  `PaymentMethod` varchar(100) DEFAULT NULL,
  `AmountInvoiced` decimal(18,4) NOT NULL DEFAULT 0,
  `AmountPaid` decimal(18,4) NOT NULL DEFAULT 0,
  `QuoteId` int(11) DEFAULT NULL,
  `AccountId` int(11) NOT NULL,
  `ContactId` int(11) DEFAULT NULL,
  `OpportunityId` int(11) DEFAULT NULL,
  `OwnerId` int(11) DEFAULT NULL,
  `SalesRepId` int(11) DEFAULT NULL,
  `ApprovedById` int(11) DEFAULT NULL,
  `ParentOrderId` int(11) DEFAULT NULL,
  `InternalNotes` varchar(2000) DEFAULT NULL,
  `SpecialInstructions` varchar(2000) DEFAULT NULL,
  `CancellationReason` varchar(500) DEFAULT NULL,
  `TermsAndConditions` longtext DEFAULT NULL,
  `SubmittedDate` datetime(6) DEFAULT NULL,
  `FulfilledDate` datetime(6) DEFAULT NULL,
  `HoldReason` varchar(500) DEFAULT NULL,
  `HoldDate` datetime(6) DEFAULT NULL,
  `RejectionReason` varchar(500) DEFAULT NULL,
  `ReturnReason` varchar(500) DEFAULT NULL,
  `DiscountCode` varchar(50) DEFAULT NULL,
  `CouponCode` varchar(50) DEFAULT NULL,
  `Source` varchar(100) DEFAULT NULL,
  `SourceIpAddress` varchar(50) DEFAULT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IX_Orders_OrderNumber` (`OrderNumber`),
  KEY `IX_Orders_AccountId` (`AccountId`),
  KEY `IX_Orders_QuoteId` (`QuoteId`),
  KEY `IX_Orders_Status` (`Status`),
  KEY `IX_Orders_OrderDate` (`OrderDate`),
  KEY `IX_Orders_OwnerId` (`OwnerId`),
  KEY `IX_Orders_ParentOrderId` (`ParentOrderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------------------------------------------------------
-- Table: OrderLineItems
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrderLineItems` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `LineNumber` int(11) NOT NULL DEFAULT 1,
  `ExternalLineId` varchar(100) DEFAULT NULL,
  `Name` varchar(200) NOT NULL,
  `Description` varchar(2000) DEFAULT NULL,
  `SKU` varchar(100) DEFAULT NULL,
  `ProductCode` varchar(100) DEFAULT NULL,
  `Quantity` decimal(18,4) NOT NULL DEFAULT 1,
  `UnitOfMeasure` varchar(50) DEFAULT NULL,
  `UnitPrice` decimal(18,4) NOT NULL DEFAULT 0,
  `UnitCost` decimal(18,4) DEFAULT NULL,
  `DiscountAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `DiscountPercent` decimal(18,4) NOT NULL DEFAULT 0,
  `ExtendedAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `TaxAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `TotalAmount` decimal(18,4) NOT NULL DEFAULT 0,
  `QuantityShipped` decimal(18,4) NOT NULL DEFAULT 0,
  `QuantityInvoiced` decimal(18,4) NOT NULL DEFAULT 0,
  `QuantityReturned` decimal(18,4) NOT NULL DEFAULT 0,
  `FulfilledQuantity` decimal(18,4) NOT NULL DEFAULT 0,
  `FulfilledDate` datetime(6) DEFAULT NULL,
  `ReturnedQuantity` decimal(18,4) NOT NULL DEFAULT 0,
  `ReturnReason` varchar(500) DEFAULT NULL,
  `FulfillmentStatus` int(11) NOT NULL DEFAULT 0,
  `EstimatedShipDate` datetime(6) DEFAULT NULL,
  `ShippedDate` datetime(6) DEFAULT NULL,
  `BillingFrequency` int(11) DEFAULT NULL,
  `ServiceStartDate` datetime(6) DEFAULT NULL,
  `ServiceEndDate` datetime(6) DEFAULT NULL,
  `TermLengthMonths` int(11) DEFAULT NULL,
  `AutoRenew` tinyint(1) NOT NULL DEFAULT 0,
  `OrderId` int(11) NOT NULL,
  `ProductId` int(11) DEFAULT NULL,
  `QuoteLineItemId` int(11) DEFAULT NULL,
  `ParentLineItemId` int(11) DEFAULT NULL,
  `Notes` varchar(2000) DEFAULT NULL,
  `InternalNotes` varchar(2000) DEFAULT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `RowVersion` binary(8) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_OrderLineItems_OrderId` (`OrderId`),
  KEY `IX_OrderLineItems_ProductId` (`ProductId`),
  KEY `IX_OrderLineItems_QuoteLineItemId` (`QuoteLineItemId`),
  KEY `IX_OrderLineItems_ParentLineItemId` (`ParentLineItemId`),
  CONSTRAINT `FK_OrderLineItems_Orders` FOREIGN KEY (`OrderId`) REFERENCES `Orders` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_OrderLineItems_Products` FOREIGN KEY (`ProductId`) REFERENCES `Products` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `FK_OrderLineItems_QuoteLineItems` FOREIGN KEY (`QuoteLineItemId`) REFERENCES `QuoteLineItems` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `FK_OrderLineItems_ParentLineItems` FOREIGN KEY (`ParentLineItemId`) REFERENCES `OrderLineItems` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;
