// CRM Solution - Customer Relationship Management System
// Copyright (C) 2024-2026 Abhishek Lal
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// <auto-generated />
using System;
using CRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260216T100000_AddWebhookTablesForIntegration")]
    partial class AddWebhookTablesForIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRM.Core.Entities.ITSM.WebhookSubscription", b =>
                {
                    b.Property<int>("WebhookSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WebhookSubscriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb4");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("[]");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventTypes"), "utf8mb4");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("{}");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Headers"), "utf8mb4");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("rowversion");

                    b.Property<string>("Secret")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Secret"), "utf8mb4");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TargetUrl"), "utf8mb4");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("WebhookSubscriptionId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_WebhookSubscriptions_CreatedByUserId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_WebhookSubscriptions_IsActive");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_WebhookSubscriptions_IsDeleted");

                    b.HasIndex("LastTriggeredAt")
                        .HasDatabaseName("IX_WebhookSubscriptions_LastTriggeredAt");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("CRM.Core.Entities.ITSM.WebhookDelivery", b =>
                {
                    b.Property<int>("WebhookDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WebhookDeliveryId"));

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ErrorMessage"), "utf8mb4");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventType"), "utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("RequestBody")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RequestBody"), "utf8mb4");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("longtext");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ResponseBody"), "utf8mb4");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("rowversion");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TargetUrl"), "utf8mb4");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WebhookSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("WebhookDeliveryId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_WebhookDeliveries_EventType");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_WebhookDeliveries_IsDeleted");

                    b.HasIndex("WebhookSubscriptionId")
                        .HasDatabaseName("IX_WebhookDeliveries_WebhookSubscriptionId");

                    b.HasIndex(new[] { "Success", "CreatedAt" })
                        .HasDatabaseName("IX_WebhookDeliveries_Success_CreatedAt");

                    b.HasIndex(new[] { "WebhookSubscriptionId", "Success" })
                        .HasDatabaseName("IX_WebhookDeliveries_WebhookSubscriptionId_Success");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("CRM.Core.Entities.ITSM.WebhookDelivery", b =>
                {
                    b.HasOne("CRM.Core.Entities.ITSM.WebhookSubscription", "Subscription")
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CRM.Core.Entities.ITSM.WebhookSubscription", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
